### ISSUE TITLE
UI & Design Issues 2022-04

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#1000]
<details><summary>OG issue by KP</summary>

- [x] Report Content

- Couldn't see the text field until I cranked up the brightness
- Weird red box when typing
- The footer is distracting
- The radio distance (not shown here) was reduced from the default, but I think it's too close in mobile to be comfortable for touch.
    - <img width="266" alt="image" src="https://user-images.githubusercontent.com/64950861/156179733-6293d632-f5ad-4e32-862e-40c21e2936cb.png">  <img width="263" alt="image" src="https://user-images.githubusercontent.com/64950861/156179832-6516f402-6575-48bc-b63d-44ced538b5ca.png">
- The "Back" and "Next" buttons feel a bit too small.  They normally it looks bigger ... or maybe it's just a font problem?
    - <img width="188" alt="image" src="https://user-images.githubusercontent.com/64950861/156179961-514966fe-2e0f-4d2a-9086-896219cf2bf0.png">
</details>

**Comment by toshokanneko** [comment]
Fixed, but I'll keep this thread open for future issue reports.
