### ISSUE TITLE
`A homepage and language translations...` also appears if the language is already switched

### ISSUE THREAD

**Issue by Abwasserrohr** [OdyseeTeam/odysee-frontend#1011]
**Bug**
> A homepage and language translations are available for your location! Do you want to switch?

The nag message appears also if the language is already switched.
I think the message should only appear if the homepage/language is not already set to the one of the location.

**To reproduce**
1. Open a browser in German, maybe vpn needed?
2. Visit odysee.com, the site already is automatically German,
3. The nag message appears anyway and clicking it doesn't change anything at all.
There is also another nag message that overlaps this one and has no opacity, but I have a issue for that open already: #914 

**Describe alternatives you've considered**
Do not show that message if the language and homepage are already set to the one the nag message wants to switch the user.
It might have problems with `de_de` -> `de`?

**Additional context**
The problem occured in Chrome and Firefox for me. Both logged in and logged out.
![image](https://user-images.githubusercontent.com/44294954/156395439-131c0f12-4f85-448b-8c4e-9c61eabc718f.png)

**Comment by tzarebczan** [comment]
Hmm, I had reported this as a bug and thought it was fixed. @saltrafael can you take a look?
