### ISSUE TITLE
Pass file page thumbnails through image proxy also

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#1019]
- [ ] If you load a file page or embed, those are not sent through the proxy. Don't optimize those. 
- [ ] Same for Banners/Cover pages, double check that's sent through also. 
- [ ] GIF support should be coming shortly too.

**Comment by infinite-persistence** [comment]
For an image file page like 
https://player.odycdn.com/api/v4/streams/free/anders-jilden-PXdBkNF8rlk-unsplash/e2b640950a3f3e75506d69b13a2d8eea8411028d/628d48, 
the url is already pointing to the player's 
https://player.odycdn.com/api/v4/streams/free/anders-jilden-PXdBkNF8rlk-unsplash/e2b640950a3f3e75506d69b13a2d8eea8411028d/628d48 
and not user's own link.  Do we still have to pass this through the proxy?

For thumbnails, they seem to be coming from `thumbsnail.odycdn` or `spee.ch` -- these count as proxied too, right?

**Comment by infinite-persistence** [comment]
For an image file page like 
https://odysee.com/@videofree:c/anders-jilden-PXdBkNF8rlk-unsplash:e
the url is already pointing to the player's 
https://player.odycdn.com/api/v4/streams/free/anders-jilden-PXdBkNF8rlk-unsplash/e2b640950a3f3e75506d69b13a2d8eea8411028d/628d48 
- [ ] Do we also have to pass this through the proxy? (I think no, but just to be sure)

- [ ] For thumbnails, those coming from `spee.ch` is considered proxied, right?
- [ ] We currently skip the proxy if the src is from `spee.ch`, but not skipping if coming from `thumbnails.odycdn`. Should we do that too?  See `getThumbnailCdnUrl`

**Comment by tzarebczan** [comment]
1) no need to pass through proxy, nothing is leaked
2) yep
3) safe to skip also, these are effectively already proxied

**Comment by infinite-persistence** [comment]
Unless I misunderstood, seems like items 1 and 2 is already going through the proxy.
