### ISSUE TITLE
memberships fall out and feedback

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#1021]
- [ ] better text formating/styling on confirmation - new lines / bolding channel / price / membership
- [ ] #2010
- [x] allow channel selection on the purchase confirmation modal
- [x] #2009
- [x] circle back on any performance-related items with calling the check api
- [x] automatically go back to membership page after adding a card
- [x] Sidebar styling is a bit weird
    - ![image](https://user-images.githubusercontent.com/7200471/157500407-9ea2e044-0b4a-4e37-8942-e686d80b0b1e.png)

**Comment by infinite-persistence** [comment]
- [ ]  Concatenated and template-literal strings will not be localizable. Adding `__()` alone doesn't help.  Holding off putting them into app-strings.json for now.
Few of many examples:
    ```
    'Your badge will be shown for your ' +
    userChannelName +
    ' channel in all areas of the app, and can be added to two additional channels in the future for free. '
    ```
    ```
    `label={__('Join via ' + price.recurring.interval + 'ly membership')}`
    ```
- [ ] There are still many strings without the i18n macro
    ```
    <b>Interval:</b>
    ```
- [ ] When all components are cleaned up, add strings to app-string.json

**Comment by Abwasserrohr** [comment]
- [ ] The button for the premium explanation is fixed, causing problems with localized versions:

https://user-images.githubusercontent.com/44294954/159714766-12819f7b-a8cc-41ba-aade-b3dc97ba791f.mp4
