### ISSUE TITLE
UI fall out

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#1030]
- [x] <img width="200" alt="image" src="https://user-images.githubusercontent.com/64950861/156768209-7637e855-7b6a-4e30-b1f5-cc130eb41710.png">
- [x] <img width="200" alt="image" src="https://user-images.githubusercontent.com/64950861/156377987-e175026e-f31b-41ed-98b4-c7038ff94db5.png">

**Comment by keikari** [comment]
Thing with the progress bar text seemed related, so adding here
![upload-bar](https://user-images.githubusercontent.com/34790748/156828198-82c248ec-7e4d-4423-b08b-8df7d5ca0d1d.png)

**Comment by infinite-persistence** [comment]
- [ ] Medium layout reflow -- additional left margin + lack of top margin for "Sort By":
    - <img width="431" alt="image" src="https://user-images.githubusercontent.com/64950861/157178868-0c3c1644-5f08-42f9-9d44-f5a5141a9903.png">

**Comment by infinite-persistence** [comment]
- [ ] Autofill causes wunderbar icon to go white.  Linux Mint cinnamon + chrome.
    - https://user-images.githubusercontent.com/64950861/157378889-c7ca0563-7916-479d-b691-33a3f392ed72.mp4

**Comment by keikari** [comment]
- [ ] Profile image can show wider than expected on list page 
https://odysee.com/$/list/f988b7e34d5a81bc136d062376ebcffe38f437e0
![list](https://user-images.githubusercontent.com/34790748/158066827-0d55d3c5-b79e-4102-a3b8-7aa012398f6e.png)

Example from odysee discord, or maybe this was fixed for it already
https://discord.com/channels/721806979928162404/936318782085935155/952571646743547914
https://odysee.com/$/list/aa2aede7dc635668a76374b130824de4135bccdc

**Comment by Abwasserrohr** [comment]
- [ ] The MoreVertical icon is misaligned for reposts in the [uploads menu](https://odysee.com/$/uploads).

**To Reproduce**
1. Repost something
2. Go to https://odysee.com/$/uploads
3. The MoreVertical icon is not where it is usually for normal uploads

**Screenshots**
![image](https://user-images.githubusercontent.com/44294954/158078132-fa926648-692b-4001-abff-ec1a093651fc.png)
![image](https://user-images.githubusercontent.com/44294954/158078223-b4c8bcf9-a06a-4b60-90da-18ca4aefe991.png)

**System Configuration**
Chrome 99.0.4844.51 on Windows

**Comment by infinite-persistence** [comment]
- [ ] After purchasing an image
    - <img width="376" alt="image" src="https://user-images.githubusercontent.com/64950861/158291863-8a9b716e-1419-45cc-95f9-f68e143f579c.png">

**Comment by infinite-persistence** [comment]
- [ ] The reposter name in the Repost Ribbon is no longer centered
    - ![image](https://user-images.githubusercontent.com/64950861/158322180-098604e2-87fb-4e6f-ab9f-e59884a6ef38.png)

**Comment by Abwasserrohr** [comment]
- [ ] Notification bubble is too small for more than 2 characters (max out at 9+?)
![image](https://user-images.githubusercontent.com/44294954/158387412-02b1f5d5-1ab3-4070-9ad9-fda9911acd6b.png)

**Comment by Abwasserrohr** [comment]
- [ ] Creator Tools menu title color is not switched in light mode:
![image](https://user-images.githubusercontent.com/44294954/158464052-106affa0-8214-4c5e-a8ab-6b0b80ee351f.png)

**Comment by keikari** [comment]
* [ ] Post preview is transparent. Original text showing behind it
![post_preview](https://user-images.githubusercontent.com/34790748/160257183-a6660a2c-0ba5-4f34-959f-33e72f661cd6.png)

**Comment by tzarebczan** [comment]
this may be in another issue, not  sure - longer channel names cut off
![image](https://user-images.githubusercontent.com/8120721/160719666-d4b604f2-f335-44d3-904f-40ce6ea6ec12.png)

**Comment by infinite-persistence** [comment]
- [ ] Membership help segment expander -- button location hardcoded?
  - <img width="375" alt="image" src="https://user-images.githubusercontent.com/64950861/160980517-789ba6e4-3b11-4bf3-8dac-4a4b1c90f774.png">

**Comment by infinite-persistence** [comment]
- [ ] "Join Odysee Premium" in "you can't livestream" component (`livestreamSetup/view.jsx`) hardcoded to a very specific `238px`.  It breaks localization.
  - <img width="259" alt="image" src="https://user-images.githubusercontent.com/64950861/160986439-1f0cd7cf-8ca6-47bb-9d5a-e4f8c076b1a2.png">
  - <img width="249" alt="image" src="https://user-images.githubusercontent.com/64950861/160986720-ae392b3e-1a29-434b-91c6-d87096789b9b.png">

**Comment by infinite-persistence** [comment]
- [ ] Minor misalignment with the "$" symbol. Potentially due to how the symbol is created/defined, since buttons look ok.
  - <img width="300" alt="image" src="https://user-images.githubusercontent.com/64950861/161007248-5ee84c48-e1b6-4a46-b2a5-ada870be9668.png">
  - <img width="300" alt="image" src="https://user-images.githubusercontent.com/64950861/161007503-5b8fb007-801b-4093-835f-a3a740fff7d9.png">

**Comment by infinite-persistence** [comment]
- [ ] <img width="309" alt="image" src="https://user-images.githubusercontent.com/64950861/161799775-3a99dbd3-0cd5-4d9d-a1a8-4cccd04e9c98.png">

**Comment by infinite-persistence** [comment]
- [ ] Not sure how best to handle the design (split 50/50 + use ellipsis?).  Passing to Rave.
  - In past projects, we usually ask the translators to shorten to given space.
  - <img width="322" alt="image" src="https://user-images.githubusercontent.com/64950861/161800686-a38ef294-9a1f-4898-8401-4069f8a53916.png">

**Comment by saltrafael** [comment]
drag and drop

![image](https://user-images.githubusercontent.com/76502841/161983603-cc116c54-6d5a-4c71-97f1-7e1982bcaec8.png)

**Comment by infinite-persistence** [comment]
- [ ] `/$/library`
  - <img width="203" alt="image" src="https://user-images.githubusercontent.com/64950861/162256844-ef14b528-75fd-4175-88d4-d435ccd19694.png">

**Comment by keikari** [comment]
* [ ] mature-tags used to be different color than other tags

![mature-tag](https://user-images.githubusercontent.com/34790748/162461921-84ce7150-0eed-4aae-bf05-d537335fbf46.png)
![mature-tag-on-page](https://user-images.githubusercontent.com/34790748/162461934-5b61f714-7492-4301-80f0-e4f50b9d785c.png)

**Comment by keikari** [comment]
* [ ] white text on white background on sync page
![youtube_white](https://user-images.githubusercontent.com/34790748/162848925-5204b717-f33c-4a21-b351-156f405d465e.png)

**Comment by infinite-persistence** [comment]
- [ ] <img width="786" alt="image" src="https://user-images.githubusercontent.com/64950861/162970489-1f86f587-84b3-40f9-8167-277d16635113.png">

**Comment by infinite-persistence** [comment]
- [ ] Overflow in medium 
<img width="329" alt="image" src="https://user-images.githubusercontent.com/64950861/162970721-9b9bccd6-add9-40dc-ad21-652b52d3f2c8.png">

**Comment by infinite-persistence** [comment]
- [ ] Text slightly off centered in medium layout
<img width="343" alt="image" src="https://user-images.githubusercontent.com/64950861/163116586-b7684871-7917-4520-a7bb-d0c4f41af3b7.png">

**Comment by toshokanneko** [comment]
Some issues still need to be patched, but I had to secure PR #1337 for my legacy.
