### ISSUE TITLE
`A homepage and language translations...` appears on localized site if a direct link to a subpage is opened

### ISSUE THREAD

**Issue by Abwasserrohr** [OdyseeTeam/odysee-frontend#1032]
**Bug**
Similar to #1011, but this time the nag message only appears if I'm on a subpage.

**To Reproduce**

1. Go to https://odysee.com/$/settings on a browser that triggers the nag message while not logged in
2. Site is in the localized language, but nag message appears until the homepage is loaded
3. Also, if the page is loaded, the nag message is flickering for a short amount of time on the homepage, it's not bad but would be cool if it is off by default, so it doesn't flicker?

**Expected behavior**
Don't show nag message if the page is already localized, also if the page is directly loaded.

**Screenshots**
![image](https://user-images.githubusercontent.com/44294954/156770001-d86cd65f-ce11-4322-949b-340fd603e439.png)

The flickering, not bad, but would be cool if it would appear if required, but not by default:
![3948759053454](https://user-images.githubusercontent.com/44294954/156771247-ddee97f0-80a1-4027-bbdc-c7c168f99fd2.gif)

**System Configuration**
Chrome 98.0.4758.102

**Comment by tzarebczan** [comment]
Thanks for filing this!
