### ISSUE TITLE
Hide email addresses by default

### ISSUE THREAD

**Issue by belikor** [OdyseeTeam/odysee-frontend#1039]
**Is your feature request related to a problem? Please describe.**
On Discord one user is complaining about the email addresses shown in the "Invites" page. He says he wants to protect the privacy of his users, so he doesn't want to see any email address.

**Describe the solution you'd like**
Maybe the email addresses could be obfuscated further, like making them all a fixed size of 12 characters plus the domain name.

**Describe alternatives you've considered**
By default the obfuscated email addresses could be hidden, and only shown when a button is pressed.

**Additional context**
I understand that some people want to know if their invites worked, but other people would like to avoid seeing the addresses of their users to keep utmost privacy.

**Comment by tzarebczan** [comment]
They are already obfuscated after a few characters...
