### ISSUE TITLE
Don't suggest PWA, suggest Android app if user doesn't have it installed (mobile)

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#1042]
user/me will return web/android device types. If android not present, and we can detect they are on an android device, prompt install of Android app on mobile

Desktop can still prompt PWA if possible, if not, no biggue.

**Comment by toshokanneko** [comment]
https://github.com/OdyseeTeam/odysee-frontend/commit/a2b567889efbf919e3f8fefa731fe135d16fdbe9
