### ISSUE TITLE
Re-think threads, especially on mobile (allow more back/forth)

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#1044]
We probably should do something better on mobile eventually where we don't show all the threads: 
![image](https://user-images.githubusercontent.com/8120721/157074200-d739181f-f682-4edd-a94a-687afd538af4.png)

**Comment by tzarebczan** [comment]
Another scenario: 
![image](https://user-images.githubusercontent.com/8120721/157524335-ec5f1979-f8fb-4db8-b302-69db118e954c.png)


https://odysee.com/@Odysee:8/premium:1?lc=13d84081112e59970bc20b1958967cabee71bd948ea934d6a1a7ef2f1ff43b94

**Comment by saltrafael** [comment]
>We probably should do something better on mobile eventually where we don't show all the threads

Probably for each say 4 threads that fit on screen, the next could open on a new "page", kinda like youtube replies or reddit thread replies, and you can go back to all comments or keep moving deeper

**Comment by tzarebczan** [comment]
Yep, I think we should take a closer look at this next week.

**Comment by tzarebczan** [comment]
This is probably also worth looking into after some of the other design issues.

Goal would be to allow more threaded convos, and improve display especially on mobile.
