### ISSUE TITLE
Broken Autorotate from Horizontal

### ISSUE THREAD

**Issue by Chiramisu** [OdyseeTeam/odysee-frontend#1062]
I reported this also in the app.

**Bug**
Auto screen rotation does not work properly on my fully updated Pixel 5. This is the case in both the native so and the SPA app in my Brave Browser, though slightly different behavior is observed. The common issue is that after rotating the screen horizontally, it correctly switches to full screen, but rotating back to vertical does not work properly. In the app, it remains stuck in horizontal mode, even upon manually exiting full screen, until the end of the video. In the SPA (I use gestures rather than on screen buttons), I have to carefully swipe in from the physical bottom or top edge of the screen to exit full screen, and only then can I return to vertical mode; simply flipping my phone vertically while in full screen does not work. This is an extremely disruptive bug resulting in a very unpleasant UX. Cheers!

**To Reproduce**

1. Play any video.
2. Rotate the phone horizontally (it will enter full screen and rotate the video).
3. Rotate the phone back to vertical (it will remain stuck in the horizontal orientation until the video ends)
4. (in the native app) Manually exit full screen while in horizontal orientation, repeat the previous step, and observe the same behavior.

**Expected behavior**
Similar to YouTube which has an excellent UX (aside from blatant censorship 😉), when flipping the phone horizontally, it should automatically change to full screen and flip the orientation of the video to fill the screen. Conversely, when flipping back to vertical, it should exit full screen and rotate back.

**System Configuration**

- LBRY App version: 0.0.23
- Operating system: Android v12

**Comment by tzarebczan** [comment]
Please try the 0.25 update and see if that helps on the Android app. 

In the PWA app, there's a small hint that pops up about the dragging. You can also tap the player + exit full screen using the button in the bottom right. Not sure if we can improve this yet, will take a look and open a separate issue for that.
