### ISSUE TITLE
notifying followers on community tab post

### ISSUE THREAD

**Issue by somedu7** [OdyseeTeam/odysee-frontend#1070]
It would be really cool that when you post something in community
tab that all followers get notified about it.
Then you could start to use odysee like a social network.

PLEASE do it.
i just tested it with a friend and it doesnt work this way right now.
he had to click on my community tab because i told him not because of notification although he follows me

**Comment by Abwasserrohr** [comment]
This is already a thing, but people need to not just subscribe, but also click the bell for that to happen. 👍

**Comment by somedu7** [comment]
> This is already a thing, but people need to not just subscribe/follow, but also click the bell (enable notifications) for that to happen. 👍

its not .. i tried with a friend. he has the bell on and didnt receive a notification

**Comment by Abwasserrohr** [comment]
Weird, it did work for me in my test.

**Comment by somedu7** [comment]
my friend tested on web and mobile.. no notification at all...

**Comment by tzarebczan** [comment]
Send us an email at hello@odysee.com with more details of what channels are being tested, this should definitely work. Also works anytime the creator comments on their content. Main level, not replies.
