### ISSUE TITLE
Limit tiles shown in horizontal mode, option to show all

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#1071]
We recently added it to the playlists page, and if you have lots of items in a playlist, it becomes a bit laggy. 

Not sure what happens when you have lots of playlists, I think we limit there too, but may want to more on mobile.

**Comment by infinite-persistence** [comment]
Hm ... 
- **Watch Later and Favourites:** only display 6 tiles
- **Playlists**: only display 12 tiles

I don't think number of items in the playlist would affect it, but will double-check -- maybe the preview overlay is looping through all of them despite only showing 2.

**Comment by infinite-persistence** [comment]
Ah, confirmed that is the case.

**Comment by infinite-persistence** [comment]
I think the performance issue you are seeing is also due to the missed batch-resolve.  
Asad fixed one part of it, I'll take a look at the other part.
