### ISSUE TITLE
[mobile] homepage + active livestreams - 1 getting filtered

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#1074]
If you have 2 active livestreams on your homepage, 1 gets filtered, so only 1 shows. It briefly shows and then disappears. Works on following page where we have the horizontal view.

**Comment by infinite-persistence** [comment]
What's missing in my steps?  The livestream still shows:

https://user-images.githubusercontent.com/64950861/157999162-d5a0122c-141a-4382-902a-8b38ee8555fe.mp4

**Comment by tzarebczan** [comment]
Sorry, should have been more specific about mobile mode. But i also had another case where it looked like it may have been working. Will try to repro again tomorrow.

**Comment by tzarebczan** [comment]
I think this may be related to the ad being hidden and therefore the tile also. Similar to the fix you made in the other area? 

Have 5 streams on desktop, and only 4 on mobile, still 2nd one hidden.
