### ISSUE TITLE
handle comments/ comment reactions account wide (i.e. only a single channel can react)

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#1075]
Some users manipulate votes from multiple channels. Show reaction status regardless of what channel was used, or disallow if already reacted to from another channel.

**Comment by infinite-persistence** [comment]
Brainstorm:
- Just reactions, or everything like blocked lists, timeout, etc.?  SBL can benefit from the simplification.

**Comment by tzarebczan** [comment]
I think it can be everything.

**Comment by tzarebczan** [comment]
I think we should also apply this to comments, outside of the creators own channels potentially? So if I have multiple channels, I can't comment as multiple on a single claim unless it's my own.
