### ISSUE TITLE
Support geoblocking channels/videos [comments?] [ support claim ids]

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#1079]
In some cases, Odysee may need to geoblock entire channels or specific videos in certain regions. 

Similar to the livestream geoblocking, it will have various options. 

A backend API is being created to pass this info vs using the local server, will provide info once it's live. 

 - [ ] not sure about comments, but will probably apply too at channel level.

**Comment by somedu7** [comment]
and who decides that? some idiot mod like on YT?

**Comment by tzarebczan** [comment]
Usually the creators themselves, i.e. RT DE would otherwise not be able to broadcast if it's not geoblocked, and they would get fined, or government agencies that have the power to fully block odysee.com in an entire country - we wouldn't want that right? So that's the compromise. Those who want to see the information will know what tools are available to do so.

**Comment by tzarebczan** [comment]
API: https://api.odysee.com/geo/blocked_list?auth_token=xxx

Sample: 
```

{
  "success": true,
  "error": null,
  "data": {
    "livestreams": {
      "745d1223c66aaaa810fd58241304ef54b28c95f2": {
        "countries": [
          {
            "id": "US",
            "trigger": "US Government",
            "reason": "law",
            "message": "US Government said it's a no no. "
          }
        ],
        "continents": [
          {
            "id": "EU",
            "trigger": "Europe leader",
            "reason": "law",
            "message": "Europe said no no. Livestreams blocked only"
          }
        ]
      },
      "e23e889c6c0e06b3f59602061cee513067b506b6": {
        "specials": [
          {
            "id": "EU-ONLY",
            "trigger": "creator",
            "reason": "law",
            "message": "RTDE has requested we block this livestream in the European Union"
          }
        ]
      }
    },
    "videos": {
      "745d1223c66aaaa810fd58241304ef54b28c95f2": {
        "countries": [
          {
            "id": "GB",
            "trigger": "UK Government",
            "reason": "law",
            "message": "US Government said it's a no no. Livestream OK "
          }
        ]
      }
    }
  }
}
```

**Comment by infinite-persistence** [comment]
Can `message` be cleaned up so the app can use directly without another set of mappings? 
"no no" is fine, but "Livestreams blocked only"  and "Livestream OK" seems weird?

**Comment by tzarebczan** [comment]
Yes, those were just some quick samples. App should definitely show the message included.

**Comment by tzarebczan** [comment]
The latter...not sure if we need to yet, will need to confirm.

**Comment by tzarebczan** [comment]
Will open a new issue for next steps, thank you!
