### ISSUE TITLE
Anúncios na odysee e odysee Premium 

### ISSUE THREAD

**Issue by Monarquialivre** [OdyseeTeam/odysee-frontend#1081]
**Bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System Configuration**

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Additional context**
Gostaria de saber como vai funcionar os anuncios da odysee?
Terá remuneração ao produtor de conteúdo? 
Será pago em LBC as propagandas ? 
Investir em propaganda na odysee será por LBC? 
Existe data para o pagamento ou vai recebendo LBC conforme os anúncios são anunciados nos vídeos? 
Ou o sistema de anúncios será em dólar? 
Se for em dólar como um produtor de conteúdo do Brazil receberá ?

**Comment by tzarebczan** [comment]
We're aware of the euro but in BR, will be fixed later today.
