### ISSUE TITLE
What is the official Odysee Repo?

### ISSUE THREAD

**Issue by juanpc2018** [OdyseeTeam/odysee-frontend#1084]
this:
https://github.com/OdyseeTeam/odysee-frontend/

or this:
https://github.com/yandex/odyssey/

????
Anyway i have a BUG....
#1.
when a Video link is posted on Telegram, 
does Not have a Preview Window, like YouTube.

#2. Keys 1,2,3,4,5,6,7,8,9,0 in YouTube jump Timeline 10%, 20%, 30%, ... 0%

Odysee only has J & L
Spacebar
F

**Comment by tzarebczan** [comment]
This is.

That's a feature telegram has to implement, ours already supports it. We've tried to reach out to no avail, but feel free to try.
