### ISSUE TITLE
Ad on home page replaces one claim

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/odysee-frontend#1086]
**Bug**
Ad on home page replaces one claim(Wasn't sure if intentional, on category pages the whole page re-draws when add appears, but claim isn't over written.)

On recording at first you can see the Odysee post at the end of second row.  
Then after resizing the window and reloading, the ad appears in where the claim should be, but instead of pushing it away, it overwrites it.  

Also there is some strange re-ordering at 4th row.( Didn't noticed when recording.)
Seems to happen quite consistently when ad appears in 3rd row.

https://user-images.githubusercontent.com/34790748/158045860-3f6469d8-b615-4796-a21e-74e774f9cf65.mp4

**Comment by tzarebczan** [comment]
This is intentional for now and the easiest way to make it work.

**Comment by tzarebczan** [comment]
@infinite-persistence this came up for another user who had adblocker, so the claim would just disappear and he was confused why a channel he followed wasn't on his homepage. Can we at least fix that case if it's easier? Ultimately it would be nice not to replace, but I know it makes the sizing more complicated.

**Comment by mayeaux** [comment]
I think a nice approach here would be to run the original adblock detection code and then save the result globally on the window to be used to check against per our earlier discussions KP
