### ISSUE TITLE
Blacklist certain email providers visually on front end

### ISSUE THREAD

**Issue by Abwasserrohr** [OdyseeTeam/odysee-frontend#1091]
**Is your feature request related to a problem? Please describe.**
There are certain email providers that cause issues like posteo.de and since it seems this will be a longer issue, it might be interesting to have some kind of filter that blocks the submit for the form if a blacklisted email provider is being used with explanation why it's not supported right now.

**Describe the solution you'd like**
Check if the email field contains `posteo.de` and disable the submit button and show a message there that says something like: `This email provider does not support emails by Odysee, please choose another email provider.` There is no need to make this on the backend, just preventing it on the front end would be enough I think.

**Describe alternatives you've considered**
In the best case, all mail providers would just work, but I guess there will always be some that have problems.

![image](https://user-images.githubusercontent.com/44294954/158218081-b72f1f67-5298-4e06-9362-0062ac54b8b2.png)

**Comment by tzarebczan** [comment]
Most do work, it's only some right? We should really reach out to posteo and the others that have trouble...

**Comment by Abwasserrohr** [comment]
Maybe posteo will fix it, but if not it looks like the issue is on our end.

**Comment by Abwasserrohr** [comment]
I tried to get in touch with posteo through their support, abuse contact and their press office, they're ghosting me and others that have issues with their mail regarding Odysee...

**Comment by tzarebczan** [comment]
Closing this for now, think we should use a different mail server if the problem creeps up again.
