### ISSUE TITLE
Remove already watched videos from recommendations.

### ISSUE THREAD

**Issue by T2Player** [OdyseeTeam/odysee-frontend#1097]
I have a trouble with the service. Videos that I’ve already watched stay in the General section and confusing me sometimes (because there is no any sign (like bottom red line in YouTube) about this content is already watched). It would be nice if watched videos would be removed from recommendations. And, yeah, add something about red line at the bottom for watched videos. Thanks.

**Comment by tzarebczan** [comment]
These are your followed list of content, not recommendations. We will be working on a watch history feature in the next couple of months, and recommendations are also coming (which take into account watched history). https://github.com/OdyseeTeam/odysee-frontend/issues/168
