### ISSUE TITLE
Additional goeblocking support

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#1100]
- All:
  - [x] comments
    - <sub>_Closed by #1564</sub>
- Special (will add a new flag to API, i..e German laws related to antisemitism)
  - [x] Related content
    - <sub>_Closed by #1552_</sub>
  - [x] Search results
    - <sub>_Closed by #1552_</sub>
  - [x] If channel, entire channel page (even showing titles, etc would be against the law)
    - <sub>_Closed by #1552_</sub>
  - [x] if content, hide on channel page
    - <sub>_Closed by #1552_</sub>
  - [x] if I own the content, allow livestream/video/channel to display, but show geoblock warning + same message
    - <sub>_Closed by #1566</sub>

Will think about this some more to make sure we didn't miss anything.

**Comment by Abwasserrohr** [comment]
Comment embedded content that is going to be played by the miniplayer is also blocked or would that be a bypass?

**Comment by tzarebczan** [comment]
That should be blocked today, or it always when I last tested it. You'll see a similar message.

**Comment by tzarebczan** [comment]
First part we should at least do now: 

- [ ] remove from channel page if it hits the geoblock conditions 

If not too hard - also block on search page  / related content.

**Comment by tzarebczan** [comment]
@Abwasserrohr noticed it doesn't work for anonymous claims: c5a03d775230a611ae4a5f3a0471631598542859

Also, don't think it's applied on the search page, only wunderbar?

**Comment by infinite-persistence** [comment]
Fixed the anonymous case (will push in a bit)

> _Also, don't think it's applied on the search page, only wunderbar?_

It does (just re-tested), except due to the anonymous bug above.  If there is a specific example, let me know.

**Comment by tzarebczan** [comment]
Must have been that, ty!
