### ISSUE TITLE
Video: disable open-on-hover for Quality and Speed Selector

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#1133]
- [x] Every time I try to seek towards the end with the mouse, these popups appear because the mouse went past these buttons.
They should probably only appear after clicked.
  - <sub>Closed by #1637</sub>

**Comment by Abwasserrohr** [comment]
I'll add this here, since it's also about hover stuff on the player: The volume hover seems to not load properly until clicked:

https://user-images.githubusercontent.com/44294954/158994790-52b7ecb4-c86b-4640-bba9-065170a503a7.mp4
