### ISSUE TITLE
Profile links have the embedded video player instead of a website card on Twitter

### ISSUE THREAD

**Issue by Abwasserrohr** [OdyseeTeam/odysee-frontend#1147]
**Bug**
Channel links should not embed like a video on Twitter.

**To Reproduce**
1. Go to twitter and post a profile link
2. The tweet will have a embed that is not working, since it links to a channel.

**Expected behavior**
There should be a channel preview like for usual websites instead of the embedded player.

**Screenshots**
![image](https://user-images.githubusercontent.com/44294954/158993859-3c4fe87a-a6fa-4b33-97c2-5aecb081764e.png)

**System Configuration**
Chrome 99.0.4844.74 on Windows

**Comment by tzarebczan** [comment]
Nice catch, thank you! This should be fixed soon, old links may still be cached.
