### ISSUE TITLE
Recommended For You "Not Interested" button out-of-sync

### ISSUE THREAD

**Issue by jbn** [OdyseeTeam/odysee-frontend#1154]
Immanuel pointed this out to me earlier in slack. Sometimes pressing the not interested `x` button brings up a different video. For example, I click this one,

![image](https://user-images.githubusercontent.com/78835/159098953-e935bafc-82fb-494a-ae01-38bbffd44589.png)

which brings up,

![image](https://user-images.githubusercontent.com/78835/159098966-ba683127-8bf5-49dc-ac48-f826de7465bf.png)

However, (and also credit to Immanuel whose github handle I don't know), if you expand the three dots below the video and press not interested from the drop down, 

![image](https://user-images.githubusercontent.com/78835/159099029-a73def7d-6ad9-444c-a3bd-811d5343fde9.png)

it shows the correct video,

 
![image](https://user-images.githubusercontent.com/78835/159099037-4af5f1f4-5d67-45c9-a5a1-de1752193b16.png)

**Comment by infinite-persistence** [comment]
@tzarebczan, when it happens, the results from the batch-resolve is messed up.  
Screenshot is showing network results of `resolve`, with the left side showing incorrect data (the `claim_id` itself is wrong). 
SDK problem?

<img width="400" alt="image" src="https://user-images.githubusercontent.com/64950861/159155744-92535e9a-9a58-4c72-8818-c237e5f9a5f3.png">

[good.txt](https://github.com/OdyseeTeam/odysee-frontend/files/8310908/good.txt)

[bad.txt](https://github.com/OdyseeTeam/odysee-frontend/files/8310909/bad.txt)

**Comment by tzarebczan** [comment]
And this only happens when resolving in batch mode? Reproducible each time? Can you paste the request? So the batched ones are the ones we're showing on the homepage (I know they weren't batched, but maybe you fixed this), and then correct one later when trying to mark?
