### ISSUE TITLE
Membership: make showing the premium badge optional

### ISSUE THREAD

**Issue by belikor** [OdyseeTeam/odysee-frontend#1155]
**Is your feature request related to a problem? Please describe.**
Some users have bought the premium membership but don't want to see a badge attached to their name.

Make showing of the badge optional in the settings.

**Describe the solution you'd like**
A checkbox in the settings page to enable or disable the display of the badge.

**Additional context**
This has been requested by users on Discord and also in the comment section of some videos.

**Comment by tzarebczan** [comment]
They should have purchased it anonymously. Anyone who wants this can email us at hello@odysee.com to remove from the channel.

**Comment by belikor** [comment]
I think the badge is about bragging rights. Sometimes you want to show the badge and brag about it, and sometimes not, so putting this in the settings would avoid having to email Odysee.

**Comment by Abwasserrohr** [comment]
>Sometimes you want to show the badge and brag about it, and sometimes not

You mean one comment should have a badge and the next one shouldn't?
I think enabling/disabling on account level (settings) would just switch it for the entire account/channel.

What about some kind of invisible tag for comments to turn it off separately for one specific comment, but maybe that's not good? 
![image](https://user-images.githubusercontent.com/44294954/159126483-5ef96202-7b15-4e8c-9e3e-8c0eeb4c4895.png)

**Comment by tzarebczan** [comment]
Eventually it will be channel level, just not anytime soon..
Working on other things like creator memberships and their badges, so that's when you'll be able to choose / customize.
