### ISSUE TITLE
Bug to close the app and no way of choosing the video resolution

### ISSUE THREAD

**Issue by VALERYRAMIREZ** [OdyseeTeam/odysee-frontend#1158]
Hi all. I'm using the odyssey app versión 0.0.26 on Android 9 and at least to me is impossible to close the app by pressing the back button, the other problem is that I can't choose the video resolution and this is an important one since I play a lot of videos on metered conections so it could be killing for my bill.

Thanks for the support.

**Comment by tzarebczan** [comment]
Replied to you in the Google review. The app has background playback so it minimizes when you close. Not all content has resolutions available, only more popular ones and we'll try to add more.

**Comment by VALERYRAMIREZ** [comment]
Yes, thanks for your answer but I will ask you again about the posibility to close the app because i've tried several times to close the app and I couldn't close it in any way, presing the back button any number of times doesn't have any outcome, not close or minimize the app, in fact I have to enter the config of the device to close the app then I don't know If I'm doing something wrong
