### ISSUE TITLE
Wallet send > channel confusing, clicking channel goes to channel page

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#1236]
When you first type a channel, you may want to click it to select, but this takes you to the channel page. 
![image](https://user-images.githubusercontent.com/8120721/160720369-20e89760-74c5-4a78-9811-82c5c7fe5902.png)

Noticed the search didn't work nicely either, but we have that filed under: https://github.com/OdyseeTeam/odysee-frontend/issues/810

**Comment by pedro-deleon** [comment]
how it should work , like a selectize?

**Comment by tzarebczan** [comment]
It would probably use the channel mention selector from https://github.com/OdyseeTeam/odysee-frontend/issues/810 and then not navigate when clicking.

**Comment by tzarebczan** [comment]
This is fixed now.
