### ISSUE TITLE
the comment filtering is a little buggy

### ISSUE THREAD

**Issue by coolpuke** [OdyseeTeam/odysee-frontend#1259]
in the first image https://img001.prntscr.com/file/img001/IbwsyUxJRUWWINvmiqKlpg.png, in the controversia rab. their 2 comment in the photo but those aren't the most slimed comments these are https://img001.prntscr.com/file/img001/IdcIHaDWSHyhIV7sYTlSjw.png
so i was wondering if that's like a glitch or something you can help rectify?

**Comment by tzarebczan** [comment]
Controversial= mix of slime and fire
