### ISSUE TITLE
Clicks While Page Loads are in Wrong Location

### ISSUE THREAD

**Issue by cahlenlee** [OdyseeTeam/odysee-frontend#126]
**Bug**
Clicking links while the page is loading on an Android device causes links somewhere else on the page to be activated. The window of time that this can happen can be 10 seconds or more on a slow connection. 

**To Reproduce**
1. Go to any video using Android
2. Refresh page
3. Click the first link you see

**Expected behavior**
The link you clicked is activated

**Screenshots**
https://user-images.githubusercontent.com/30788194/138770695-108f90bb-522e-4eaf-a4f7-a08fd2c5ba42.mp4

**Comment by tzarebczan** [comment]
Let us know if things feel smoother with the recent performance improvements and redesign. There's probably a bit more we can do, will continue to focus on performance as part of other issues.
