### ISSUE TITLE
Paginate on upload page FormField not setting state back to null

### ISSUE THREAD

**Issue by antoniodebaca** [OdyseeTeam/odysee-frontend#1280]
**Bug**
On upload page the "Go to Page:" at the bottom of the Paginate not setting to null after hitting return

1. Go to 'upload page'
3. Scroll down to 'the bottom of the page and click into the "Go to page:" input form', just right of the Paginate component.
4. Input a page where you would like go to.
5. See error the value that you inputted does not reset.

**Expected behavior**
The FormField to be cleared after function is called

**Comment by antoniodebaca** [comment]
I would like to be assigned this as my first issue on odysee, a simple setTextValue(""); on line 49 of the handlePaginateKeyUp function would fix this. Not sure how i go about getting assigned to this and making a push for it.

**Comment by tzarebczan** [comment]
Just saw this, sorry! Tag, you're it!

**Comment by antoniodebaca** [comment]
I created a pull request #7567, tzarebczan I'm not sure if i did everything correct. I made a fork, then I cloned it, update my changes on my fork, then i created a pull request. I couldn't find the changelog.md, let me know what else i need to change. Thank you.

**Comment by antoniodebaca** [comment]
Thomas,
I think i tried to pull request to the wrong repo.
https://github.com/lbryio/lbry-desktop/pull/7567
Not sure, do you have any documentation that might help me with the correct
repo.
