### ISSUE TITLE
AirPlay button enhancements

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#1288]
- [ ] Size doesn't match the rest of the icons (probably same re-work as Chromecast button)
- [ ] Move it to the same slot as Chromecast if possible?

<img width="447" alt="image" src="https://user-images.githubusercontent.com/64950861/161792503-a054fa36-5642-4506-ab1d-b5ae365cec74.png">

**Comment by tzarebczan** [comment]
On smaller screens, it also hides the full screen button.

Eventually it will be time to consolidate the options into a menu.
