### ISSUE TITLE
Mark "Already watched"

### ISSUE THREAD

**Issue by myfirstnameispaul** [OdyseeTeam/odysee-frontend#1298]
**Is your feature request related to a problem? Please describe.**
I can see that across devices, the interface will mark a video watch progress via the magenta bar under the video thumbnail. However, it only marks watch progress for a video watched on the device, not videos watched while logged into the account, so other devices do not show the magenta bar under all videos watched.

**Describe the solution you'd like**
Option to "Mark watched" which will add a complete full magenta bar under the thumbnail for the device.

**Describe alternatives you've considered**
Account tracking of videos watched and progress bars across all logged in devices.

**Comment by tzarebczan** [comment]
There's a separate issue filed for cross device support, hopefully come in the next couple of months.
