### ISSUE TITLE
Unload popup on Settings page is unclear about saving

### ISSUE THREAD

**Issue by vintprox** [OdyseeTeam/odysee-frontend#1305]
**Bug**

"Settings" page triggers an annoying `unload` listener that I believe was supposed to prevent settings to be saved by confirmation. But there is no confirmation button anywhere, and many options just get saved right from the bat (which I think is actually nice).

Some code in `unload` listener basically locks you on the page unless you explicitly signal browser to "**Leave/Reload**" by clicking the prominent button.

Another, but quite related, problem is that I don't see how my preferences transfer between browsers. It seems to me that, for example, when I toggle "*24-hour clock*", it saves value in either LocalStorage or Cookies. I can't find a separate key for settings though in both storage types. There are also no network requests for settings.

We need a visual feedback of saving too.

**To Reproduce**

1. Go to "Settings".
2. Change any preference, like by toggling "*24-hour clock*".
3. Try to leave a page.
4. Be welcomed by an annoying `unload` popup.

   Firefox
   ```
   This page is asking you to confirm that you want to leave — information you’ve entered may not be saved.
   [Stay on page] [Leave page]
   ```

   Chrome
   ```
   Changes you made may not be saved.
   [Cancel] [Leave]
   ```

5. Leave the page and reopen the "Settings".
6. Ensure that your preference, in fact, was saved.

**Expected behavior**

1. Get a clear feedback whenever my preference is saved.
2. Not be welcomed by any popups when leaving/reloading the page.

**Screenshots**

![image](https://user-images.githubusercontent.com/5708819/162150065-c088c5ce-1092-4515-9c67-b7f2c43d36ab.png)

**System Configuration**

- LBRY App version: Current. Otherwise, I can't know, because there is no "About" link.
- Browsers: Firefox, Chrome.

**Additional context**

Some settings are still quirky, but it's for another issue.

**Comment by tzarebczan** [comment]
There's some settings that aren't saved right away (on purpose), and won't be unless you click save or navigate away.

**Comment by vintprox** [comment]
> There's some settings that aren't saved right away (on purpose), and won't be unless you click save or navigate away.

This statement is off the mark. I already raised few concerns:

1. There is no "Save" button to begin with.
2. There is no reason to show a popup intervening with leaving the page. `unload` confirmation has place for editors and alike, not the settings page.
3. This issue doesn't necessarily cover the semantics of asynchronous/batch saving. Users don't concern themselves about whether they have "Save" button or settings getting saved right away.
4. There is just no proper indication of the saving process itself. Just tell the user whether something gets saved or not: without making them to reload and reassure.

**Comment by infinite-persistence** [comment]
<img width="777" alt="image" src="https://user-images.githubusercontent.com/64950861/162430938-29a87d0e-f366-4e05-95c1-7241818998d1.png">

**Comment by vintprox** [comment]
I see. It's a subtle one, if I had to search on top left, really.

Then why settings like "24-hour clock" are saved regardless of pressing it? It's inconsistent.

**Comment by vintprox** [comment]
Issue not solved.
