### ISSUE TITLE
FYP: filter deleted content?

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#1308]
`claim_id:  d5eac2b2c5995ad60a87ea65ef7852bb3ace5f02`

<img width="516" alt="image" src="https://user-images.githubusercontent.com/64950861/162345542-3b1eebb3-f146-4255-b17c-b0cd4f05bf0f.png">

Can filter at app side, but would it be more efficient if FYP does it?

**Comment by tzarebczan** [comment]
Believe Johnny has this on his list..doesn't happen too often, but should be handled there. Can't hurt for us to improve if it's quick also
