### ISSUE TITLE
Logged-out but app is showing logged-in state

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#1319]
Rave and I are seeing this.

- Not sure how to reproduce, but the 2 times that I saw this, I didn't realize I was logged out (or didn't consciously log out)
- On the second time, I did a refresh multiple times and I was back in the logged-in state.

<img width="595" alt="image" src="https://user-images.githubusercontent.com/64950861/162650706-cdeed9de-f97e-4492-9ff6-425128a32a4f.png">

**Comment by keikari** [comment]
This seems same https://github.com/lbryio/lbry-desktop/issues/7030
(Not sure if steps are 100% consistent for repro)

**Comment by infinite-persistence** [comment]
Thanks, forgotten about that issue.

Suspect `user/signout` failed or timed out.  Will try moving the cleanup to a `finally` block instead.

```
      Lbryio.call('user', 'signout')
        .then(doSignOutCleanup)
        .then(() => {
          // @if TARGET='web'
          window.persistor.purge();
          // @endif
        })
        .then(() => {
          setTimeout(() => {
            location.reload();
          });
        })
        .catch(() => location.reload());
```

**Comment by keikari** [comment]
This can happen again. 
Chrome and Firefox. Following while logged out. 
![following-logged-out](https://user-images.githubusercontent.com/34790748/170818509-640f1197-5b5a-4e9c-be95-1241f8677b1e.png)
