### ISSUE TITLE
Don't repeatedly call claim search on failure

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#1320]
It should retry a few times ,but at some point require a user to refresh. 

Happened during downtime, would pile on re requests and flood backend.

**Comment by infinite-persistence** [comment]
Just some notes:
It's down at the moment, but `${SDK_API_PATH}/status` doesn't reflecting that, so I guess can't use that as an indicator.

**Comment by infinite-persistence** [comment]
`--- Re-open ---`
1321 is only a band-aid from the top-most layer.

- A potentially-more robust solution can be done at `doClaimSearch` (and also `doResolve`) in a similar way with how auto-pagination is being done.
  - [ ] block calls with the same options if repeated within short duration
    - the `id` is usually `Date.time()`, so we already the time-tracking info.
  - [ ] but retry N times first, as noted in 1321.
