### ISSUE TITLE
Show feed view progress bar as farthest watched.

### ISSUE THREAD

**Issue by myfirstnameispaul** [OdyseeTeam/odysee-frontend#1323]
**Is your feature request related to a problem? Please describe.**
When I forget what I've watched, which is normal, I can now look at the magenta progress bar in the feed view, which is great. However, if I go back in a video to re-listen to an earlier portion, the feed view will show the last viewed timestamp as the progress watched on the video.

**Describe the solution you'd like**
Show the farthest watched timestamp of a given video in the feed view, even if I have gone back to relisten to an earlier section of the video.

**Comment by tzarebczan** [comment]
I don't think we'll be storing 2 pieces of data for this. I believe YouTube does the same as we do, but if not, feel free to reopen. 

Eventually we can have some other indicator for when it was fully watched, but don't expect that anytime soon.
