### ISSUE TITLE
move floating ad to no-overlap

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#1335]
_<sub>Branch: [adnim](https://github.com/OdyseeTeam/odysee-frontend/tree/adnim)</sub>_

## Details
as part of these changes, start showing no-overlap ad to all non-prem+ users

- [x] remove floating bottom ad (outbrain)
- [x] replace vidcrcuch with admination video ad. 
  - [x] I asked them what to do about scrolling - if they don't want to handle the pop out ad, maybe we'll re-place another tile once you scroll down. This may be better for cross browser support also. 
    - <sub>_Requires #1341_</sub>
- [x] insert ar6 between every other category

:heavy_multiplication_x: <strike>KP: Mobile:  maybe the ad should always use the List (Recommended) layout to reduce the ad height among the video tiles.  Otherwise, on a small screen, the ad is all we see on the first screen, with the next video tile being off screen.</strike> 
_Skip, looks bad_
- [x] Tom: Mobile: it can probably be on each category since it requires scrolling, but fine for every other if that's easier. 
- [ ] :grey_question: What about mobile initial homepage load - we want to be sure to show the ad somewhere. So maybe we show floating until they scroll, and then no-overlap? 

## Vendor to-do
- [ ] Get adnimation to disable floating ads
- [ ] Handle dark theme
- [ ] Append id or class to `<style>` so we can clean up
- [ ] Clean up console errors if possible (see email)

## Follow-up
- [ ] Clean up `<styles>`  to prevent accumulation in DOM.

**Comment by infinite-persistence** [comment]
Updated current state.  See initial description.

**Comment by infinite-persistence** [comment]
Category pages: re-fill ads after scrolling every 2 pages

**Comment by infinite-persistence** [comment]
`--- close ---`
This is shipped, and the `style` tag problem has been filed separately.  CSS issues have been accounted for by our own customizations.
