### ISSUE TITLE
Discrepancy in button and text for weekly watch reward

### ISSUE THREAD

**Issue by flauc** [OdyseeTeam/odysee-frontend#1336]
**Bug**
There is a discrepancy between the text for the "Weekly Watch Reward" and its button on the rewards page. The text says you can earn a minimum of "0.1" and the button shows "0.25 - 25".

**To Reproduce**

1. Go to https://odysee.com/$/rewards

**Expected behavior**
It should either say a minimum of "0.25" in the wording or "0.1 - 25" in the button.

**Screenshots**
![image](https://user-images.githubusercontent.com/4489834/163318542-5cb8d81e-dc57-433c-b92a-79e80a30d67c.png)

**System Configuration**
OS: Windows 11
Browser: Brave

**Comment by tzarebczan** [comment]
Thanks for the report, it will be fixed shortly!
