### ISSUE TITLE
Add button to force kill livestream for stream owner

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#136]
Add a button on their livestream file page, and on channel page where we show the livestream is live. We can also consider adding to the dashboard. Only show when we know the channel is actually live. 

It's going to be a post call to: https://stream.odysee.com:3000/stream/kill/{{CHANNEL CLAIM ID}} with these params:

d: hex data from signing a channel name (See how we create a livestream / commenting stuff)
s: call channel sign with hex data, use signature from channel sign return
t: use ts from channel sign return

**Comment by mayeaux** [comment]
PR is up here: https://github.com/OdyseeTeam/odysee-frontend/pull/209

**Comment by tzarebczan** [comment]
Done, will have some clean up coming up + add to content page.
