### ISSUE TITLE
Add tag filter / search + sorting options to wild west

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#1371]
We used to have a tag filter on the old discover page. Would be great to bring that back, and maybe add an option to fill in own tag term to filter on.

Also add the new/top/trending sort, default trending as usual.

**Comment by infinite-persistence** [comment]
Re: tags

How did that look like -- just a text field?  (well, I guess I can try loading old code ^^)

**Comment by tzarebczan** [comment]
Think it had a drop down with the popular tags. And would be cool to add custom option to enter own.
