### ISSUE TITLE
Tag search has some probably unexpected params

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/odysee-frontend#1378]
There are some probably unwanted params in tag search https://odysee.com/$/discover?t=test
* [x] `release_time: >x` probably not wanted in "Trending" and "New"  for tag search
  * _<sub>Closed by #1380</sub>_
* [x] in "Top" the time options don't do anything. (Seems to also affect categories)
  * _<sub>Closed by #1380</sub>_
* [ ] "Content Type: Any" uses `claim_type: [streams, reposts, channels]`,  with `stream_types: ["video", "audio"]`, so channels aren't returned, and not any types of streams either.  Probably shouldn't have `stream_type` filter there.  
(This also happens in categories, but maybe wanted in there?)

**Comment by tzarebczan** [comment]
@infinite-persistence probably related to the recent changes.
