### ISSUE TITLE
Clicking on "Repost" on a search with no claim yet will crash the site if search contains space / add url params for repost

### ISSUE THREAD

**Issue by Abwasserrohr** [OdyseeTeam/odysee-frontend#1385]
**Bug**
The site crashes by clicking on "Repost" if there is no claim yet.

**To Reproduce**

1. Go to search with a search term with a space that doesn't exist yet: https://odysee.com/$/search?q=heiliger%20ofenk%C3%A4se
2. Click on "Repost"
3. Site crashes

**Expected behavior**
Should open either the repost modal or the repost site.

**System Configuration**
Chrome, 100.0.4896.127

**Comment by tzarebczan** [comment]
nice catch 

also, there should be a way to share a URL directly to a repost, with prefilled params. Think this was the case when it was a page vs modal, at least partial support.
