### ISSUE TITLE
Add apple-app-site-association file for iOS universal links

### ISSUE THREAD

**Issue by ktprograms** [OdyseeTeam/odysee-frontend#1386]
**Is your feature request related to a problem? Please describe.**
In order for iOS to open `https://` links in-app, the website needs a `apple-app-site-association` file in the `.well-known` directory.

**Describe the solution you'd like**
Add a file with the following content to be served at `.well-known/apple-app-site-association`:

```json
{
	"applinks": {
		"details": [
			{
				"appIDs": [
					"7G9P9AM955.com.odysee.Odysee"
				],
				"components": [
					{
						"/": "/*",
						"comment": "Matches all URLs that are not just / (All files/channels)"
					}
				]
			}
		]
	}
}
```

(I think the App ID is correct, I got it from the development team setting in Xcode)

**Describe alternatives you've considered**
N/A

**Additional context**
Issue: https://github.com/OdyseeTeam/odysee-ios/issues/277
Documentation: https://developer.apple.com/documentation/Xcode/supporting-associated-domains

@akinwale Pinging you since this is related to the iOS side as well, hope that's okay with you.

**Comment by tzarebczan** [comment]
it should be up at https://odysee.com/.well-known/apple-app-site-association after the site rebuilds (For some reason, pointing to the android file that's there under https://odysee.com/.well-known/assetlinks.json

**Comment by tzarebczan** [comment]
(there's some strange bug where it's always resolving the first file it sees, @infinite-persistence going to take a first shot at it).

**Comment by tzarebczan** [comment]
This is working now, thank you KP!
