### ISSUE TITLE
Design Feeback

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#1389]

**Comment by infinite-persistence** [comment]
- [ ] Tag appearance is inconsistent

Sometimes red, sometimes gray, sometimes black.
The black version is also hard to see for the Livestream case below.

<img width="517" alt="image" src="https://user-images.githubusercontent.com/64950861/165018376-8ca14819-053b-465f-9bd4-d7d86fe1fbe0.png">

<img width="535" alt="image" src="https://user-images.githubusercontent.com/64950861/165018402-1622a72b-95e5-473d-bd80-28e8899bcd07.png">

<img width="539" alt="image" src="https://user-images.githubusercontent.com/64950861/165018455-0706740c-9b43-4951-b860-790b088e940f.png">

<img width="402" alt="image" src="https://user-images.githubusercontent.com/64950861/165018507-43f7124d-3e63-4d3a-848b-9e41c7aa58c7.png">

The original theme's tag appearance was consistent everywhere, and I also like that it uses a the smaller font.

**Comment by infinite-persistence** [comment]
- [ ] Contrast is bad in dark-over-dark elements

I have a hard time differentiating these elements.  I thought it was my screen, but it's the same thing on other devices, so it must be an accessibility (color-blindness, etc.) thing?  I don't have color-blindness, but everything just looks "disabled" to me.

<img width="338" alt="image" src="https://user-images.githubusercontent.com/64950861/165018780-8620a198-b2b5-47ba-b720-ba3ad0393170.png">

**Comment by infinite-persistence** [comment]
- [ ] Better use of opacity to differentiate elements in a block, so we can decipher the structure in a glance.
e.g. label vs values, title vs. subtitle, main buttons vs aux.

One random example:
<img width="530" alt="image" src="https://user-images.githubusercontent.com/64950861/165019145-990f7717-0e10-441a-bad7-c48c24de69a7.png">

The "reply | fire | slime" line used to be gray, emphasizing that: (1) it's a different element than the comment text (2) lower emphasis than the comment text.  So, when I'm skimming, the reply line doesn't distract or require my subconscious attention to read it,

The "1 day ago" is a good example -- differentiates the element better, and also tells you the emphasis.

**Comment by infinite-persistence** [comment]
- [ ] Styles that break away from the rest

Example:
These look odd:
<img width="527" alt="image" src="https://user-images.githubusercontent.com/64950861/165019519-51e3db54-78a8-44bf-bcf3-3b52b1f6a076.png">

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/64950861/165019824-7cde061c-4ff8-49b1-864f-1e84c2fade7e.png">

The other similar pages uses `Card`s, so they are centered, easier to read, and subtitles are displayed in a consistent style.

**Comment by toshokanneko** [comment]
Mostly patched. I'll keep this thread open for more issues until the end of the month.

**Comment by infinite-persistence** [comment]
- [ ] Paid embed instructions confusing due to overlap

Authenticated + < 1 LBC in wallet + https://odysee.com/@test1:d/Content-FREEdom:0

Can't recall how it used to look like.

<img width="586" alt="image" src="https://user-images.githubusercontent.com/64950861/165891035-6958bf89-b262-479f-ac63-73c3422b2a1d.png">

**Comment by infinite-persistence** [comment]
- [ ] https://github.com/OdyseeTeam/odysee-frontend/issues/1389#issuecomment-1108050827 was closed, but I didn't notice any changes?

**Comment by toshokanneko** [comment]
The changes are subtile. I've increased the opacity of the font color to the maximum (white/black) to make it more obvious that the element is not disabled. I've also adjusted the hover opacity.

**Comment by toshokanneko** [comment]
Not really ideal, but no longer overlapping.
![image](https://user-images.githubusercontent.com/94839278/166191956-1250ef7b-695b-4a70-9edd-7ea22c0f0cd1.png)
