### ISSUE TITLE
Add ability to stop "Default Quality Setting" hint?

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#1408]
"You can also change the default..."
appears on every quality change.  Feels weird have a reminder executed every time a setting changes, but I understand the need to unbury the setting.

Maybe add a "don't remind me again" link below the "Settings" link.

**Comment by tzarebczan** [comment]
It should only happen once per session if you don't have a default

**Comment by infinite-persistence** [comment]
`-- close --`
Hm ... not sure what happened this morning -- it was constantly appearing.  Now, it does not.  Maybe it was loading old code.
