### ISSUE TITLE
How to help translate?

### ISSUE THREAD

**Issue by atjn** [OdyseeTeam/odysee-frontend#1413]
First of all thanks for making this very cool project!

The contributing guidelines don't say anything about how to help translate the project. Could you add that somewhere?

I am interested in this because my app recently (automatically) switched to the danish translation, and that translation is really bad.
I am not trying to be disrespectful to the translator by saying that, the fact is just that the translation is not valid danish. Some of the most prominent words like "Followers" and "Comments" are not spelled correctly, and there is a list of longer phrases that, while grammatically correct, do not resemble anything a Dane would ever say.

**Comment by tzarebczan** [comment]
Thanks for the offer! Check out https://www.transifex.com/lbry/lbry-desktop/ and request access there.
