### ISSUE TITLE
POSTs to clickstream excessive for some users

### ISSUE THREAD

**Issue by jbn** [OdyseeTeam/odysee-frontend#1418]
If I `GROUP BY` the `uuid` sent to `clickstream`, the median count of requests per `uuid` is 1. This is expected -- most video views result in one request. However, some users send _a lot_ of requests. These are the top request counts by `uuid` for `2022-04-20`,

![image](https://user-images.githubusercontent.com/78835/165548244-41f061c5-1215-4c43-80a7-4d210f0f2beb.png)

From my side, I don't believe this is a bug. I can coalesce each request because it has a `uuid` But it could definitely degrade the experience for some users. Wanted to flag this for whoever will be working on,

- https://github.com/OdyseeTeam/odysee-frontend/issues/1317
- https://github.com/OdyseeTeam/odysee-frontend/issues/1318

**Comment by tzarebczan** [comment]
We didn't wanna change too many things at that time and Johnny said he was handling the data just fine. When I talked to Johnny, these were just from a few days, so could have been some other hiccups too.

**Comment by tzarebczan** [comment]
Please reopen if you see these again
