### ISSUE TITLE
YtSync: extend description limit

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#1432]
Was trying to implement automatic-chapter-markers, but noticed that descriptions are being truncated.  It's also bad from a consumer standpoint as when the description is cut-off, they need to visit the original site.  

Most likely due to SDK or transaction limitation?  (But I tried creating a claim with original text length -- seems ok)

Odysee:  https://odysee.com/@hashoshi4:6/bitcoin-metrics-are-up%2C-btc-price-is:5?r=2ituZftpdG18f1TBADDbCaaEZ9ecYYYm
<img width="309" alt="image" src="https://user-images.githubusercontent.com/64950861/166194174-dd005467-3e80-4a3d-b3fe-bbfce74c4b80.png">

Original:
<img width="492" alt="image" src="https://user-images.githubusercontent.com/64950861/166194210-4aad0c53-9331-40e6-81f8-0bde88929c14.png">

**Comment by tzarebczan** [comment]
This was extended for new syncs.
