### ISSUE TITLE
Reading progress status automatically saved (in a local cookies or on you remote server)

### ISSUE THREAD

**Issue by tsaphnat** [OdyseeTeam/odysee-frontend#1449]
Recommended internet browser by Odysee in order to save automatically the progress status of reading, please?
Thank you and best regards.

**Comment by tzarebczan** [comment]
What do you mean by reading progress? Watched video progress? This is already being done, locally for now. Happens every 5 seconds or so.

**Comment by tzarebczan** [comment]
Let us know what scenario it doesn't work in. If it's the same browser and still logged in, you should see the progress saved. A watch history page is coming soon also.
