### ISSUE TITLE
Embed Logo Link opens in iframe

### ISSUE THREAD

**Issue by Abwasserrohr** [OdyseeTeam/odysee-frontend#1455]
**Bug**
Not sure if it's part of #936, so opened a new one.
If one clicks on the logo to give Odysee a visit, it will open Odysee in the iframe instead of a new tab.

**To Reproduce**

1. Go to https://wissenschaftstehtauf.de/#video
2. Click on the embed to load it
3. Click on the odysee logo
4. Link is opened in embed and not a new tab

**Expected behavior**
`target="_blank"` is missing

**Screenshots**

https://user-images.githubusercontent.com/44294954/166802327-0a77543c-1053-4971-be97-7ec40b3648ab.mp4

**Comment by tzarebczan** [comment]
Thx for spotting, not sure when this broke...
