### ISSUE TITLE
Volume control

### ISSUE THREAD

**Issue by LANEW1995** [OdyseeTeam/odysee-frontend#1469]
Typically most browser based web video players, you can scroll wheel over the volume control slider to control it. Its a nice feature I've become very accustomed to using youtube, and it would making the switch much easier.

Simple scroll wheel with the mouse over volume bar support would be the obvious solution if it's do-able.

A second useful way would be simple shortcut, like hold ctrl+shift then use the mouse wheel.

**Comment by infinite-persistence** [comment]
> _Typically most browser based web video players, you can scroll wheel over the volume control slider to control it. Its a nice feature I've become very accustomed to using youtube, and it would making the switch much easier._

Hm ... it doesn't seem like YT or any major video websites do this, even over the the volume slider control area. 

As a temporary workaround, the `up` and `down` arrow keys can be used to adjust the volume when the video is in focus, although I understand it's not exactly the same as using the mouse-wheel.

**Comment by mayeaux** [comment]
Shipped with https://github.com/OdyseeTeam/odysee-frontend/pull/1638

@LANEW1995 , the alternate shortcut is to Shift + Scroll on the video element

**Comment by Myzel394** [comment]
@mayeaux I think we should add this when the video is in full screen. You can't scroll anywhere, so it makes sense to be able to change the volume by scrolling without having to press the Shift-key.

**Comment by mayeaux** [comment]
@Myzel394 I think that would be a good feature, I know VLC has that feature and I use it often

**Comment by tzarebczan** [comment]
This is now possible!

**Comment by Myzel394** [comment]
@tzarebczan  I think that should also be possible when **not** holding down the SHIFT key, given that the video is in fullscreen mode.
