### ISSUE TITLE
Add a watch queue like on Youtube

### ISSUE THREAD

**Issue by Grooty12** [OdyseeTeam/odysee-frontend#1477]
**Is your feature request related to a problem? Please describe.**
When wanting to watch multiple videos after each other, one need to either add them to the "watch later" playlist or in another browser tab (on desktop).

**Describe the solution you'd like**
Instead, a watch queue like on YouTube could be added. It could look the same as when playing a playlist, but more integrated into normal viewing. Basically just copy what YouTube does, or something similar.

**Additional context**
![Youtube-queue-odysee-request](https://user-images.githubusercontent.com/85930101/167476112-016b9aff-da4f-4462-b41f-03e8a9053c26.png)
Just like this

**Comment by tzarebczan** [comment]
Thanks for the suggestion! I know we had something similar filed as a feature request, will try to dig it up, and if not, we'll keep this one.
