### ISSUE TITLE
Opening Odysee using middle-click crashes the site 

### ISSUE THREAD

**Issue by Abwasserrohr** [OdyseeTeam/odysee-frontend#1483]
**Bug**
If I middle click on the odysee logo, it crashes the new opened odysee tab, this used to work.

**To Reproduce**

1. Go to https://odysee.com (you can just middle click on this link, normal clicking works)
2. Middle click on Odysee logo
3. New tab with Odysee opens
4. Odysee crashed in new tab

**Expected behavior**
Odysee shouldn't crash, this doesn't happen if I right click and click on "open in a new tab".

**Videos**

https://user-images.githubusercontent.com/44294954/167682447-79dd2fab-8cac-46c7-8f0a-3ff7c3c2df6b.mp4

**System Configuration**
Tested on
Chrome Version 101.0.4951.54
Firefox Version 100.0

**Comment by tzarebczan** [comment]
Just pushed up a fix for it, can you confirm in ~20 min. Also, let's make sure the meme works in that scenario. Have you guys already tested localized meme?

**Comment by Abwasserrohr** [comment]
It's fixed 👍
Didn't test the localized meme yet, but will do soon.

**Comment by Abwasserrohr** [comment]
localized meme works 👍
