### ISSUE TITLE
ReachUI Tab errors

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#150]
- Occurs when entering a Channel Page
- Been there for a long time.  Interferes with development when you're trying to debug your own errors.

![image](https://user-images.githubusercontent.com/64950861/139192599-9e31d654-b3b3-4179-add4-01c9ba048474.png)

**Comment by david0178418** [comment]
Looks like this one was an issue with the dependency itself.  And it looks like they resolved it as of v0.16.0. See the above PR
