### ISSUE TITLE
Clicking Odysee logo while on a channel page causes crash

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/odysee-frontend#1505]
1. Go to some channel page
2. Click Odysee logo
3. Page crashes

![crash](https://user-images.githubusercontent.com/34790748/168580980-d3a158c7-15b8-413b-9bea-a316624810c2.png)
From chrome
![crash](https://user-images.githubusercontent.com/34790748/168582288-c26c1dfb-420a-4503-9d91-41bab4654fa6.png)

**Comment by tzarebczan** [comment]
@saltrafael think this is from the urls pr, that's the same crash i saw. Something with selecting a Livestream
