### ISSUE TITLE
Mobile: Embedded touch controls are misaligned on Android

### ISSUE THREAD

**Issue by ivandenis** [OdyseeTeam/odysee-frontend#1519]
When using the embed link, the video player controls are misaligned with the video (offset upwards). There is also a large play/pause button that interferes with the navigation bar.

**Steps to reproduce the behavior:**
1. Go to https://wissenschaftstehtauf.de/ using an Android device (or Chrome devtools in mobile mode with an Android device)
2. Click on one of the Odysee videos
3. Tap the video
4. Error appears

Note: This can also be reproduced by pasting the `src` url from any Odysee embedded iframe into Chrome browser on an Android device.

**Expected behavior**
The controls (i.e. navigation bar) should be aligned at the bottom of the video, not floating 1/3 of the way up. The play button should not be over top of the navigation bar.

**Screenshots**
![image](https://user-images.githubusercontent.com/100809122/168973890-34f10f38-e944-473f-952f-1a3035529a52.png)
![image](https://user-images.githubusercontent.com/100809122/168973961-ef8018d3-4d69-480d-be2d-3013ce0675b5.png)

**System Configuration**
Odysee May 17, 2022
Chrome 101.0.4951.61
Android 11; Samsung Galaxy S10 (SM-G73F Build/RP1A.200720.012)

**Comment by tzarebczan** [comment]
Noticed this on twitter embeds recently too, let's get it fixed soon
