### ISSUE TITLE
strange thumbnail size requested on mobile layout (pc only?)

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#1526]
https://thumbnails.odycdn.com/optimize/s:900:506/quality:85/plain/https%3A%2F%2Fplayer.odycdn.com%2Fspeech%2Fa592d282b754a2e2%3A7.png

900:506 ? 

On the screen, they look even smaller than regular layout. Not sure if this is just a chrome issue in mobile mode,

**Comment by infinite-persistence** [comment]
This is from the video poster, not the claim tiles.  Fix coming up to improve this.

**Comment by tzarebczan** [comment]
Pretty sure this was from related content, sorry I wasnt specific enough. I don't think we pass any size info for poster...

But will double check in a bit and with the PR.

**Comment by tzarebczan** [comment]
Did confirm, but you're PR is still valid still..didn't realize we were using sizing there, thought it was always 0:0 for the original.

**Comment by infinite-persistence** [comment]
> _Did confirm_

Oh, it really came from Recommended?  Will take a closer look.  When I looked yesterday, it seems to use FileThumbnail, which has a hardcoded value for w and h, but it's a long file, so maybe missed something.
