### ISSUE TITLE
New grid fall out bugs

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/odysee-frontend#1534]
* [x] Loading channel page on medium layout and zooming out makes all claims disappear after some zoom level (Doesn't  seem to happen always, but saw at least on this channel https://odysee.com/@trickovec15 also on Odysee channel)
1. Load channel page on medium layout
2. Scroll down so second page loads
3. Zoom out
4. Claims disappear
---------------------------------------------------------
* [x] The last claim on channel is missing on medium/small layout. 
Last claim can be seen on first image, but zooming in makes it disappear.
https://odysee.com/@trickovec15

Large
![large](https://user-images.githubusercontent.com/34790748/169367510-605ee7b3-7c07-4838-bee1-310a276cc3c7.png)

Medium
![medium](https://user-images.githubusercontent.com/34790748/169367548-f00e272c-632d-4562-9dec-0f75c489e684.png)

Mobile(scrolled down)
![small](https://user-images.githubusercontent.com/34790748/169367589-9a514560-47aa-40c1-8426-7487fd4f2d2f.png)

**Comment by keikari** [comment]
* [ ] Last item on this channel is missing on all layouts https://odysee.com/@Normalostehtauf
https://odysee.com/@Normalostehtauf:9/S_Kapitel1_2_SD:e <--- missing video
![last-item-missing](https://user-images.githubusercontent.com/34790748/169748174-01d782f4-d19c-4783-a94b-41f6c14264c5.png)

**Comment by infinite-persistence** [comment]
- [ ] On Brave (ad-blocked), an FYP list with 2 channels blocked still results in an empty slot:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/64950861/169751683-4d51fdac-58c2-48d5-b790-61a06874259a.png">

**Comment by toshokanneko** [comment]
@infinite-persistence Did this happen before or after your onHidden changes?

**Comment by infinite-persistence** [comment]
@toshokanneko, before.  I had the same question too :D

**Comment by toshokanneko** [comment]
Hmmm.....for some reason this seems to work for me. I've blocked 3 channels and all the tiles got replaced. The tiles are empty right after blocking/muting a channel, but when I refresh the page they all get replaced. Is it possible that something else is hiding the tile like the mature tag?

**Comment by keikari** [comment]
Some odd stuff can still be seen on this channel https://odysee.com/@Normalostehtauf (Unless I'm still running old code, but shouldn't be)

* [ ] The last claim is missing. (It does appear if page is loaded on large layout, scrolled down, and then zoomed to medium layout)

* [ ] Loading channel page on medium layout, scrolling to second page, and zooming out makes most/all claims disappear after some zoom level  
(This is currently fine on channel in earlier, but for some reason it seems to now load all claims on one page for that channel. )
