### ISSUE TITLE
Floating-player high CPU usage on Chrome

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#158]
@infinite-persistence commented on [Fri Sep 03 2021](https://github.com/lbryio/lbry-desktop/issues/7016)

- On Chrome (Windows and Linux), regular player uses about 10% CPU, while Floating jumps between 50-90% (see image).

![image](https://user-images.githubusercontent.com/64950861/132039157-0e9e88f7-5080-45d5-b77b-edd0006832a7.png)

**Comment by infinite-persistence** [comment]
https://odysee-workspace.slack.com/archives/C02G20Z2AEL/p1635808922111700

**Comment by infinite-persistence** [comment]
Bump.  Gets me every the mini-player lags and "teleports" when dragged.

I know Anthony managed to reproduce it back then.

**Comment by infinite-persistence** [comment]
`Close`
Fixed by Assad ... due to `useRect` over-observing ... nothing to do with videojs itself.
