### ISSUE TITLE
Add view stream view count on tiles

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#16]
backend API has the value, but it's not being populated. WIll be soon.

**Comment by infinite-persistence** [comment]
Still no `viewCount`, I think

<img src="https://images.zenhubusercontent.com/6040e15e79c4cfbee0755ca9/47b9c48d-ae0a-4dc0-95b5-e3477eb68355" width="300">

**Comment by tzarebczan** [comment]
Correct, we tried and broke some stuff. Will be done after we migrate away into our new backend.
