### ISSUE TITLE
design issues June 2022

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#1608]
- [x]  can't see password autofill thingy on ios ![](https://i.imgur.com/aGgo0fW.png)

**Comment by infinite-persistence** [comment]
- [ ] Button borders missing.  Or new style?

<img width="253" alt="image" src="https://user-images.githubusercontent.com/64950861/171370045-2766fe79-89c5-43a9-b193-1e47a8f5bac6.png">

**Comment by Abwasserrohr** [comment]
- [ ] Text on sync page while claiming a YT channel is not toggled to light mode:
![image](https://user-images.githubusercontent.com/44294954/171573498-65afac48-49b6-42b2-9011-c7c48603d8a2.png)

**Comment by infinite-persistence** [comment]
- [ ] Uneven box when navigating via keyboard

<img width="287" alt="image" src="https://user-images.githubusercontent.com/64950861/171802496-cf326228-2688-43b2-a152-07bef62f395b.png">

**Comment by infinite-persistence** [comment]
- [ ] Can't navigate to video controls via `tab` unless I click it to focus.

Other video sites do enter into the video controls.

**Comment by infinite-persistence** [comment]
- [ ] Video in an embed iframe:  the loading spinner is square instead of round.

**Comment by tzarebczan** [comment]
- [ ] grid + wild west = uneven tiles (at least on 6 wide)

**Comment by infinite-persistence** [comment]
- [ ] [Enhancement] Differentiate between mouse-overed and current selection

![image](https://user-images.githubusercontent.com/64950861/172532380-249d273d-da52-4401-a72b-a97bef665b93.png)

**Comment by infinite-persistence** [comment]
- [ ] Can't change homepage or language when signed out.

The button is no longer available, so have to rely on the nag, but the won't re-appear after dismissed, unless one clears Secure Storage.

**Comment by infinite-persistence** [comment]
- [ ] Artifact in livestream page when logged out

<img width="310" alt="image" src="https://user-images.githubusercontent.com/64950861/173048391-607ec7fa-0986-4c37-af69-641837b4e5ef.png">

**Comment by infinite-persistence** [comment]
- [ ] Chromecast screen misaligned in small layout

Medium vs. small
<img width="300" alt="image" src="https://user-images.githubusercontent.com/64950861/173289562-37fcf7fa-9bdb-4ea8-9208-5b8d9f0811eb.png">         <img width="311" alt="image" src="https://user-images.githubusercontent.com/64950861/173289607-d7f64d66-455a-4aaf-a745-070f28e2777b.png">

**Comment by infinite-persistence** [comment]
- [ ] Medium or small layout

<img width="671" alt="image" src="https://user-images.githubusercontent.com/64950861/173291331-c32cfbba-9844-4102-ab4f-92a4acccc9ba.png">

**Comment by tzarebczan** [comment]
![image](https://user-images.githubusercontent.com/8120721/173609360-7e7ef8e8-55b4-44ac-90fc-a47f6876e2be.png)
cut off

**Comment by tzarebczan** [comment]
transparency issue with less notificaitons? 
![image](https://user-images.githubusercontent.com/8120721/173680236-646cd21e-7147-46da-a981-155f5f097599.png)

**Comment by infinite-persistence** [comment]
- [ ] `sclassname` typo is back.  Maybe merge issue.
<img width="401" alt="image" src="https://user-images.githubusercontent.com/64950861/173846327-572e8934-5d55-4bb8-a760-60bf0eb209be.png">

**Comment by infinite-persistence** [comment]
- [ ] Sticky is broken in Dark Theme (transparent background)
I don't think we changed anything, so they must have updated their script again?

<img width="300" alt="image" src="https://user-images.githubusercontent.com/64950861/174260707-313cc863-929d-45c9-8e3b-761baf644210.png">

**Comment by tzarebczan** [comment]
too wide? 
![image](https://user-images.githubusercontent.com/8120721/174445372-9c3073cf-a4f3-4719-9c79-11c29112b8bd.png)

**Comment by Abwasserrohr** [comment]
- [ ] Nag is under the ad instead of overlapping it or pushing it up and is not switching to light mode
![image](https://user-images.githubusercontent.com/44294954/174588174-4eee082e-3a65-4503-bb0d-7744fba9addf.png)

**Comment by infinite-persistence** [comment]
- [ ] Wunderbar suggestion overflow

<img width="297" alt="image" src="https://user-images.githubusercontent.com/64950861/174930926-7e242e09-a24b-46d0-b852-2a4408b36ca2.png">

Aside:  don't know why, but I always find the popup blends in too much with the rest of the page (maybe just needs a border).  The odd thing is that the claim context menu doesn't have a border either but it doesn't bug me there.  Maybe it's due to the busy-ness of the wunderbar popup (too many things).

**Comment by infinite-persistence** [comment]
- [ ] Similar to the Settings Page, we can't access `/$/help` in Incognito unless you manually type it.

**Comment by infinite-persistence** [comment]
- [ ] Google's complaining about this again (DMCA notice exceed mobile width)

<img width="543" alt="image" src="https://user-images.githubusercontent.com/64950861/177161407-02d4e23d-ecfc-44dd-9702-0add0f4729bf.png">

**Comment by infinite-persistence** [comment]
- [ ] Titles without space is not wrapping, so overflowed in mobile

https://odysee.com/CBS_News_-_I_M_NOT_FIGHTING_-_Tom_Aviles_an_award-winning_photographer_with_CBS_Minnesota_was_arrested_and_struck_by_a_rubber_bullet_while_covering_protests_in_Minneapolis.-1267099935234818049/adf66a92d394823b2a259343690e8e9b3b5fea49

<img width="295" alt="image" src="https://user-images.githubusercontent.com/64950861/177161682-270fa967-e647-452e-b4fc-067080b84b55.png">

**Comment by infinite-persistence** [comment]
- [ ] I think came from #1597
<img width="588" alt="image" src="https://user-images.githubusercontent.com/64950861/177235274-74cd3129-ea00-4c26-a930-551ff0a7c799.png">

**Comment by infinite-persistence** [comment]
- [ ] :arrow_down_small: The tooltip reflowed.  Can happen with chat width adjusted, and probably also from long translations.

Feel free to re-design entirely. 

<img width="339" alt="image" src="https://user-images.githubusercontent.com/64950861/177473862-9b9295f7-95dd-449a-95c9-5a58dd3f1235.png">

**Comment by infinite-persistence** [comment]
- [ ] The card nag got shifted

<img width="347" alt="image" src="https://user-images.githubusercontent.com/64950861/177914974-8811b72c-df99-4bd6-bf98-87950ed27bf6.png">

**Comment by Abwasserrohr** [comment]
- [ ] Not sure if it has been reported somewhere, but seeing a floating "x" to remove the ads from time to time on latest Chrome/Windows 10 without any ad, also seen it pop up while cookie consent message is open. It's not clickable, so clicking on it does nothing if there is no ad.
![image](https://user-images.githubusercontent.com/44294954/177928397-2e5e23fb-814f-43dd-be33-f5c7b7d5331b.png)
![image](https://user-images.githubusercontent.com/44294954/177928533-724334d4-62c0-4584-a96b-e6db513fef11.png)

**Comment by infinite-persistence** [comment]
Nag, sticky-ad and toast z-order problem

<img width="535" alt="image" src="https://user-images.githubusercontent.com/64950861/178672602-6060bd67-6d7f-4db6-a852-df3e1a65c229.png">

**Comment by infinite-persistence** [comment]
- [ ] Restore narrower modal?  Close if disagree.
    - I believe in #1271, the modal width was increased so that the tab in the support modal isn't touching the sides in German (?). 
    - It was easier to read paragraphs when it was narrower.  Also, things like the Publish Preview ended up having too much empty space anyway.

**Comment by infinite-persistence** [comment]
- [ ] This came back in the playlist merge

<img width="190" alt="image" src="https://user-images.githubusercontent.com/64950861/179142417-ccf0e2b9-fc1e-495c-a96d-f60b3c354c12.png">

**Comment by infinite-persistence** [comment]
Added DMCA link above.

**Comment by infinite-persistence** [comment]
- [ ] On Desktop small layout, the autoplay-next countdown screen overflows the mini player.

<img width="218" alt="image" src="https://user-images.githubusercontent.com/64950861/179448503-a919be9a-1a7f-4a24-8428-81638453e4ce.png">

**Comment by infinite-persistence** [comment]
- [ ] In`/$/playlists` light mode, the context menu does not appear on hover, unless hovered exactly on the 3-dot button.

**Comment by infinite-persistence** [comment]
- [ ] Sign in nag misalignment

<img width="284" alt="image" src="https://user-images.githubusercontent.com/64950861/182993916-2ff156e4-9a1a-43fe-8bbb-c309244e00bd.png">

**Comment by infinite-persistence** [comment]
- [ ] https://odysee.com/$/careers needs style pass?
  - Similar to the stripe pages, it doesn't really follow the site's theme.  Could probably just use `<Card>`'s title and subtitle fields to stay in theme, rather than crafting own `body`?  Or anything that's consistent with the overall style.
  - The "IT Project Manager" doesn't feel like a link, but felt like an IT manager signing off a message at a bottom.  Not sure what's the solution, but perhaps just use a bullet, even though there's just 1 entry for now.

**Comment by tzarebczan** [comment]
pink clashes with pinned + hyperlink? Iffy on light mode too. 
![image](https://user-images.githubusercontent.com/8120721/184397497-b109252a-5b00-47b1-9ba1-e8113366ef42.png)

**Comment by infinite-persistence** [comment]
I think this was right-justified
<img width="245" alt="image" src="https://user-images.githubusercontent.com/64950861/184597609-89e28a29-db8c-4098-813c-8b2c9cf973e1.png">
