### ISSUE TITLE
Suggestions for live chat layout

### ISSUE THREAD

**Issue by Abwasserrohr** [OdyseeTeam/odysee-frontend#1627]
**Is your feature request related to a problem? Please describe.**
I feel like the livestream chat on Odysee is empty and while there are not always a tons of chatters, I also get that feel on active Odysee chats. There is way too much dead space in the chat and I want to suggest a few changes to make it feel less empty and some other suggestions with images how it could look.

I also looked at the chat of other platforms like Twitch, YT, Dlive, Trovo and all of them implement the chat in way like I want to suggest for the Odysee live chat. While I see that we don't want to be a copycat doing everything exactly the same, all video streaming platforms I watched besides Odysee have implemented their chat in a similar way.

**Describe the solution you'd like**
1. **More compact chat**
    1. **No extra line just for username**, rather start the message after the name
    2. **Remove** the **@ character** like on channel names in video cards
    3. **Move and change timestamp in front of name**
    4. Have **badges in front of the name**, it looks more organized, since it’s always at the same place and not changing due to length of name. It is harder to find the badge of the user if it is behind the name and devaluing it that way.
    ![image](https://user-images.githubusercontent.com/44294954/171589292-a0320602-6cc4-4a5c-ad2f-08b42d47c01a.png)
    ![image](https://user-images.githubusercontent.com/44294954/171589497-e13610e1-67e9-45ff-a671-a08deb5ce616.png)

2. In chat, most people are not writing tons of text, the **input field could be just 1 line** and expand if people write more into it.
    ![image](https://user-images.githubusercontent.com/44294954/171591108-e35cd9fc-a08f-43ef-a445-448d3e28b512.png)

3. **Move cogwheel** down to the other settings, since it’s just easier to have all the switches and settings at one place instead having some on top and some on the bottom.
    ![image](https://user-images.githubusercontent.com/44294954/171591409-924edf67-d213-4049-8474-c379c714a176.png)

4. The **“Comment” button** did confuse me first time I looked at it in the chat box, it **could be “Chat”** instead, so everyone knows that clicking that button will create a chat message.

**Comment by tzarebczan** [comment]
Thanks for taking the time to research and spell out! 

I agree we don't wanna look exactly like the competition, but there's definitely things to improve.

**Comment by mayeaux** [comment]
I really like these ideas:
- Putting the chat on the same line as the chatter username makes a lot of sense (as well as removing the @ symbol). I agree when you compare them, it is a lot better to put it on the same line, it's much easier visually to map the chat to the user (also agree with moving the badge in front)
- Changing the name from 'Comment' to something better makes a lot of sense to me. YouTube just uses a symbol, Twitch uses 'Chat', I don't mind 'Send' but I agree 'Comment' is confusing
- Timestamp in front I'm a little less sold on, do you have an example of someone who does it that way where it looks good?
- Cog on the bottom I would say I disagree with, the three other buttons are all related to the specific chat that's being sent so I like the cog at the top since it applies to the whole setup of the chat

But great suggestions, I think these would be easy to implement and would have a really positive impact, thanks for the heads up

**Comment by Abwasserrohr** [comment]
I agree, the cog wheel is great where it is right now and that there should be a difference between both of the settings.

The timestamp after the name makes sense in the way the messages are displayed right now, but if messages start in the same line as the user names, the timestamp is blocking the way people read, maybe it's just me being biased, since I watched a lot of twitch streamers months/years ago. 

|After the name|In front of name|
|:-|:-|
| ![grafik](https://user-images.githubusercontent.com/44294954/172417084-03f34f06-34b8-438d-a97d-dd49ad91e102.png) | ![grafik](https://user-images.githubusercontent.com/44294954/172417172-50314a4d-f521-41ac-a19f-4d7b47ccc305.png) |
|Here, if I want to know who did write the message, I need to look at the name and instead of naturally reading the message, I need to fly over the timestamp, if it's enabled.|This way, people don't have the timestamp between the username and the message. Most platforms have no relative time, because it's just too long I guess.|

How competitors do it:

|Platform|Image|
|:-|:-|
|**Twitch**| ![grafik](https://user-images.githubusercontent.com/44294954/172417853-2b210491-48e1-44b2-8505-2d2a9d91b2fa.png) |
|**YouTube** |![grafik](https://user-images.githubusercontent.com/44294954/172418088-eda5ede9-3a67-467f-a187-a9a28239a7c2.png)
|**Dlive**|![grafik](https://user-images.githubusercontent.com/44294954/172418374-fd9955c1-0806-4ee1-898f-daf6a9febebe.png)|
| **Trovo** <br>(seems like they don't have any timestamps setting)|![grafik](https://user-images.githubusercontent.com/44294954/172420228-11551b0a-465e-4570-8fe2-838cd776c8fc.png)|
