### ISSUE TITLE
Oldest video won't be shown due to advertisement tile

### ISSUE THREAD

**Issue by belikor** [OdyseeTeam/odysee-frontend#1633]
**Bug**
In a channel page, the advertisement takes one tile in the grid of videos, so the oldest video will not be shown when the grid is full.

Related https://github.com/OdyseeTeam/odysee-frontend/issues/1583

**To Reproduce**

1. Go to a channel page that has an even number of videos.
2. Use "tile layout". The number of videos should be so that the grid is full.
3. Example 1, if a channel has 8 videos, in a small monitor they will be displayed in two rows of 4 videos each (full grid).
4. Example 2, if a channel has 12 videos, in a large monitor they will be displayed in two rows of 6 videos each (full grid).
5. Without a premium account, an advertisement tile will be inserted in the first row of videos. This will push all videos one position to the right.
6. The last video in the grid, which is the oldest if sorting by "New", will not be shown.
7. Switching to "list layout", all videos will be shown.

Presumably the code checks the number of videos in the channel, and if a full grid is assumed, it doesn't create another row of videos. So when the advertisement tile is added, it thinks the grid is full before displaying the last video.

Example with this channel, @ShadowRavenStudios:4

It has 48 videos, so they fit in a 12 x 4 grid (small monitor), or 8 x 6 grid (large monitor).

The oldest video is called "Hammerfell Armory SSE", the second oldest is "Abyssal Sword Standalone".

When in "list layout" both videos will be at the bottom. When in "grid layout", and sorting by "New", the last video in the grid, bottom right, will be "Abyssal Sword Standalone", and "Hammerfell" won't be shown.

**Expected behavior**
The page should create an additional row of videos in order to show the video that was displaced by the advertisement tile.

**Additional information**
The bug was reported in Discord by the channel owner.

https://discord.com/channels/721806979928162404/914213136414953492/982490457781194773

**Comment by tzarebczan** [comment]
Thank you for filing. Definitely an edge case we should handle - we can just throw the ad onto the next line or skip all together, whatever is easier

**Comment by toshokanneko** [comment]
Aight, it's patched. I'll keep this thread open for a few more day. Keep an eye out on similar issues...
