### ISSUE TITLE
Last claims on channel missing on grid-view

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/odysee-frontend#1634]
There been few people asking about this. Seems to affect most channels. Can be seen easily with grid vs list mode.

One(or sometimes few) last(oldest) claims missing from channel page on grid mode.
https://odysee.com/@langeveda:6
https://odysee.com/@Odysee:8

**Comment by belikor** [comment]
Same issue was just reported https://github.com/OdyseeTeam/odysee-frontend/issues/1633

**Comment by keikari** [comment]
Oh, missed that one
