### ISSUE TITLE
Syncing a channel that wasn't eligible for syncing

### ISSUE THREAD

**Issue by FinixFighter** [OdyseeTeam/odysee-frontend#1661]
**Bug**
I have a channel that I tried to sync with Odysee but it didn't meet the requirements for syncing. So when you click "Sync YouTube Channel" you'll see this:"@YouChannelName is not eligible to be synced", and that's ok. Problem is that when your channel will be eligible for syncing, you won't be able to sync it because it is marked as not eligible.

**To Reproduce**
1. Go to your "channels" page on Odysee
2. Click on "Sync YouTube channel" 
3. On the bottom of the page, click "Add Another Channel"
4. Type in your desired Odysee channel name, select language and check the box. Then click "Claim now"
5. Log in to your Google account and select the channel you want to sync (use a channel which wasn't eligible before, but it is now), then authorize
7. You are prompted to the initial Odysee screen (the one of point 3.)

**Expected behavior**
Odysee should check if eligibility critiera are met every time we try to add that channel (or at least doing the check once per day). Not only the first time we try to add that channel, otherwise it will be impossible to add it.

**Comment by tzarebczan** [comment]
These need to be processed manually via a request to help@odysee.com.
