### ISSUE TITLE
URI replacement issues

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#1667]
bf158ad6

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/64950861/173035637-2aa6cb05-726d-4109-8e11-5d6cc77bf5f7.png">

Normally, `uri` is sliced off correctly:
  <img width="189" alt="image" src="https://user-images.githubusercontent.com/64950861/173036265-b485d12e-e780-4839-a2da-101e31083626.png">

However, for the oauth case, there will be a temporary redirect while it re-checks the token, and there is an additional hash. 
- [x] The code seems to be slicing off from the first `:`, causing it to always return to the channel page.

  <img width="476" alt="image" src="https://user-images.githubusercontent.com/64950861/173036571-7aa9b211-8374-435e-9815-d478748ba59c.png">

----

- [x] There is also the `replace('#', ':')` issue that only replaces the first match, which we talked about in Slack.

**Comment by tzarebczan** [comment]
I'm guessing the single replacement is what breaks https://github.com/OdyseeTeam/odysee-frontend/issues/1359 too
