### ISSUE TITLE
Show last watched position of an upload, and go to that last watched position when navigated to

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#168]
@mayeaux commented on [Fri Aug 06 2021](https://github.com/lbryio/lbry-desktop/issues/6796)

A very important feature to have is to save where a user last was on a video and then show that progress when they are overviewing a channel page. When the user sees the progress bar they can know where they were in that video (a completed video should be a full red progress bar) and when they click that video they should be taken to where they last were while watching that video.

Example from NodeTube, YouTube has the same implementation:
![Screen Shot 2021-08-06 at 13 52 38](https://user-images.githubusercontent.com/7200471/128506553-4dfa82b7-cd41-471c-a42a-d5da3dfeb4c0.jpg)

It should be simple enough to make a call to the database on a recurring basis that will mark the current progress of the upload view. On the frontend most of this functionality exists because we are saving user's current state on the client side, so provided the backend can provide the last watched time along with the rest of the information about the claim all that is needed is a progress bar which is easy enough to implement.

---

@tzarebczan commented on [Fri Aug 06 2021](https://github.com/lbryio/lbry-desktop/issues/6796#issuecomment-894310551)

Thanks for filing, will close my old issue for this (https://github.com/lbryio/lbry-desktop/issues/3614). This should also include some indicator that something was viewed fully (red bar all the way to the end, maybe different tile shading, etc). 

We still need account API support for this to make it cross device / persistent: https://github.com/lbryio/internal-apis/issues/1790 

---

@mayeaux commented on [Mon Aug 09 2021](https://github.com/lbryio/lbry-desktop/issues/6796#issuecomment-895288449)

Re: indicating fully watched videos, YouTube does a solid red bar, which feels natural and I support as the spec. 

![Screen Shot 2021-08-09 at 16 49 25](https://user-images.githubusercontent.com/7200471/128726302-2aeda0d9-fc35-469c-a082-d82930e3e955.jpg)

**Comment by OliverBrotchie** [comment]
Search history would also be a very useful feature.
