### ISSUE TITLE
strange image preview on blog post

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#1680]
https://odysee.com/@lbrytech:19/hubba-hubba:6 

Click the image and you get: 
![image](https://user-images.githubusercontent.com/8120721/173395894-4bdc4562-439a-4e13-9357-1376510bed0d.png)

**Comment by infinite-persistence** [comment]
@toshokanneko, `ZoomableImage` uses the modal, and I guess this version needs to be full screen.  Take a first stab?
