### ISSUE TITLE
Closing image viewer scrolls page back up on mobile view, but not on desktop

### ISSUE THREAD

**Issue by Abwasserrohr** [OdyseeTeam/odysee-frontend#1704]
**Bug**
Not sure if it has been already reported already, but if I scroll down and click on a picture to zoom in and then want to close the image viewing menu, it will scroll up on mobile.

**To Reproduce**

1. Go to https://odysee.com/@odyseebr:1/mod:c on mobile 
3. Scroll down to the last image
3. Click on the last image
4. Close image menu
5. It scrolled up

**Expected behavior**
It should keep the current scroll state, I think.

**Screenshots**

https://user-images.githubusercontent.com/44294954/174233549-456d25f5-bc90-4015-b5f8-89fe3d05150c.mp4

Were able to reproduce on Android Chrome and Desktop Chrome

**Comment by infinite-persistence** [comment]
Should be the same root-cause as https://github.com/OdyseeTeam/odysee-frontend/issues/1085, which is a bug in react's modal.

**Comment by infinite-persistence** [comment]
But I vague recall adding a y-position restoration for the other modals ... will see why it didn't apply for all modals

**Comment by gadabra** [comment]
It happens exactly on 900px. When I change $breakpoint-small: 800px it happens there.

https://github.com/OdyseeTeam/odysee-frontend/blob/de068d36f1d719468e020db35fe8283ea9dc979f/ui/scss/component/_modal.scss#L5

This line is this problem. If you delete it works fine. But I cant figure out what it does.

**Comment by saltrafael** [comment]
Thank you for helping @gadabra, looks like some old code that has no use anymore
