### ISSUE TITLE
Player: livestream m3u8 continuously fetched despite auto-play is off

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#1708]
I have `autoplay` set to `off` in Setting and generally just want to check out comments.
But the stream seems to be running behind the scenes regardless.

![image](https://user-images.githubusercontent.com/64950861/174299443-e169f646-223e-45d7-ab1f-229f4bfa9528.png)

**Comment by tzarebczan** [comment]
I've seen that before, even before the recent refactor. It's only grabbing the metadata, but yeah still seems strange. It's probably so that it can play it right away from live edge, vs having to initialize again.

**Comment by tzarebczan** [comment]
Can you see if this was fixed by the PR?

**Comment by infinite-persistence** [comment]
Yup yup, tested with Anthony prior to his PR.
