### ISSUE TITLE
[FEATURE REQUEST] Supabase migration from firebase when it's on production soon?

### ISSUE THREAD

**Issue by iamflorencejay** [OdyseeTeam/odysee-frontend#1712]
**Describe the solution you'd like**
Supabase is now on public beta and will be on production very, very soon. If someone dosen't know this project, Supabase is basically an open source firebase alternative that is also available for both selfhost and directly on their premises to create a project, just like firebase.

[Github repo here](https://github.com/supabase/supabase) 

I would like to ask if when it's now in production, will you have support for these services (cloud or selfhost) on Odysee?

**Comment by tzarebczan** [comment]
Don't plan to change this anytime soon unless there's widespread support across browsers and apps for it.

**Comment by iamflorencejay** [comment]
I think they have a support for both desktop and mobile. There literally the same, but open sourced.
