### ISSUE TITLE
Content page for fiat tip leads to incorrect path

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#1744]
we link to channelname:contentclaim_id: https://github.com/OdyseeTeam/odysee-frontend/blob/553a801bc3a6088439c55a44c5ba20576474aa83/ui/component/walletFiatPaymentHistory/view.jsx#L81

 We don't have the content claim name, but we can eventually add in the backend. 

If possible, on click it would claim search the source claim id and then navigate. If we have to do it for every entry before navigating, probably hold off. 

Can't think of any other way without the claim name...

**Comment by mayeaux** [comment]
Seems to work properly now
