### ISSUE TITLE
Missing UUID

### ISSUE THREAD

**Issue by jbn** [OdyseeTeam/odysee-frontend#1745]
There are a high number of `lvv` calls being written with a blank `uuid` (several per second). 

- I can't find the bug on the `clickstream` side. 
- The user agents seem to suggest it spans different browsers (e.g. there were edge, chrome, linux, etc).
- Most of the calls remain good
- I haven't been able to replicate this in my browser

**Comment by tzarebczan** [comment]
Resumed sends do seem to work, not sure what I was seeing before. 

Did notice 2 issues there:
1) we don't have playing time for those
2) if you close under 10 seconds, then you end up with blank recsysid and no uuid either.  My guess is that we store the entry before that data is loaded, and then append later on future redux saves as the video is playing. 

Johnny is getting UUIDs in the case I'm not (play > back > close pop out player). Seems to be browser/version specific. Strange that it would have the recsysid and not uuid as they come from the same place.

**Comment by infinite-persistence** [comment]
- Pushed the fix.  Re-open if there are still issues.
- Re-filing the `totalPlayTime` issue (probably need something elaborate to store value before the tab is destroyed, or update the rescys entry every time we update the play position -- but this will still miss the 1 update).

**Comment by tzarebczan** [comment]
@jbn are you okay with embeds not sending UUID or how do you want to handle that?

**Comment by jbn** [comment]
`uuid`s are used for two things. for embeds, the only one that is relevant is deduplification. **if i understand the front-end code in the embed case, they can't really fire twice, correct?** if that's definitely true, i can just look at the embed flag in the `lvv` post and create a new uuid if its true and the uuid is missing.
