### ISSUE TITLE
Support setting and showing featured channels 

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#1749]
On YouTube, there's a Channels tab which can be customized to show featured / main / other channels, and even subscriptions (optional). 

We'd want to do something similar on Odysee - provide an interface for setting this up, and then showing it nicely on the channels page. The first thing to focus on would be "featured" channels, but keep in mind that we may add other "sections"  later. 

If we want to keep this on chain, which we probably do,  it could be done via a specific playlist name. This would allow us to support other sections later also. Channel metadata doesn't have such fields, and would need to be flexible to support to support other sections.

Curious to hear other ideas or thoughts...

**Comment by tzarebczan** [comment]
api on commentron is ready. Field is called featured_channels and can take any json data we want. Maybe we can add a version number so we can adjust later as needed - dunno what the best practice for that is. 


example: ```{"jsonrpc":"2.0","id":1,"method":"setting.Update","params":{"channel_name":"@gifprofile","channel_id":"745d1223c66aaaa810fd58241304ef54b28c95f2","signature":"xxxx","signing_ts":"1666797652","featured_channels":{
  "entries": [
    {
      "type": "featured",
      "claimId": "3c27005a1f7012c93600d9d3033e21d43387348c"
    },
    {
      "type": "featured2",
      "claimId": "3c27005a1f7012c93600d9d3033e21d43387348c"
    }
  ]
}}}```

**Comment by infinite-persistence** [comment]
Alright.

Only if it's easy and you agree it makes sense, should the field be renamed from `featured_channels` to something generic like `sections`?

```
{
    "jsonrpc": "2.0",
    "id": 1,
    "method": "setting.Update",
    "params": {
        "channel_name": "@gifprofile",
        "channel_id": "745d1223c66aaaa810fd58241304ef54b28c95f2",
        "signature": "xxxx",
        "signing_ts": "1666797652",
        "sections": {
            "version": "1.0",
            "entries": [
                {
                    "value_type": "featured",
                    "value": {
                        "title": "FC1",
                        "description": "Maybe?",
                        "claimsIds": [
                            "3c27005a1f7012c93600d9d3033e21d43387348c"
                        ]
                    }
                },
                {
                    "value_type": "shorts",
                    "value": {
                        "claimIds": [
                            "3c27005a1f7012c93600d9d3033e21d43387348c"
                        ]
                    }
                },
                {
                    "value_type": "liked_videos",
                    "value": {
                        "claimIds": [
                            "3c27005a1f7012c93600d9d3033e21d43387348c"
                        ]
                    }
                },
                {
                    "value_type": "featured_members",
                    "value": {
                        "claimIds": [
                            "3c27005a1f7012c93600d9d3033e21d43387348c"
                        ]
                    }
                }                
            ]
        }
    }
}
```

**Comment by tzarebczan** [comment]
Yeah, can rename it for sure! We also added channel settings for rave, but i guess this unique to have it's own field.

**Comment by infinite-persistence** [comment]
_(just thinking out loud in case someone has better ideas)_

* added `id` into the mix ...the ui needs a way to search for the entry for things like editing.

**Comment by infinite-persistence** [comment]
Regarding the free-form json `featured_channels` attribute (soon to be renamed `sections`):
1. Unless I missed something, the API relies heavily on the app (Odysee and beyond) to not mess up existing data.
2. The app needs to always fetch the latest `setting.List`, make modifications over the existing `featured_channels`, and send it back. Potential failures:
    - If there is a network hiccup during `setting.List` and the app lets the flow continue, `featured_channels` will be in a blank state + new stuff (i.e. essentially clearing what's in the server).
    - If the user is making modifications over 2 tabs or hits "Done" hours later, we are essentially making modifications over the cached `featured_channels` from Step 2, which could be obsolete by then.

I can continue to work around this by being as cautious a possible (graying out buttons, etc.), but seems like it will be more robust if there is a new API to `add/modify/remove` entries.  This probably means more logic in the backend to formalize the format, and less flexibility.

**Comment by infinite-persistence** [comment]
Update:  Hm ... I guess it's the same issue as the following/subs list in the wallet.  Maybe not a big deal.

**Comment by tzarebczan** [comment]
Yea, I thought it wouldn't be too bad since we already do something similar with preferences. We'd definitely want to handle any failure causes of not being able to list. 

I don't think we have the resources for backend to support something like that for now, and this was the most flexible.
