### ISSUE TITLE
Support .ogv  files for downloads

### ISSUE THREAD

**Issue by dfghjkjhgr** [OdyseeTeam/odysee-frontend#1757]
Currently, Odysee does not support .ogv files for downloads. This is a problem because it requires non-free software to view videos.

# Solution
Add an option to download a .ogv file. .ogg is also used as a file extension for Theora video, but .ogv is betteer because it prevents confusion with .ogg audio files.

# Alternatives
You could try supporting any other free/libre video format.

**Comment by tzarebczan** [comment]
You should see a download link on all content, check the 3 button menu. 

Can you share some links with ogv files?

**Comment by dfghjkjhgr** [comment]
Oh, I know there are already downloads. But they are in the .mp3 format.

**Comment by dfghjkjhgr** [comment]
Oh. Now I see. You don't have any .ogv support for uploads.

**Comment by tzarebczan** [comment]
That means people uploaded mp4s, and not ogvs. So not sure what you're asking for...

If they are super old uploads, they may just say mp4 but may be ogvs, we didn't have proper data back then.

**Comment by tzarebczan** [comment]
You can upload any file, just need to select the All Files option when the explorer comes up. We'll be changing this soon so it does it by default.

**Comment by dfghjkjhgr** [comment]
Oh. Thanks!
