### ISSUE TITLE
Add Keywords meta tag

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#177]
@jsigwart commented on [Mon Nov 25 2019](https://github.com/lbryio/lbry-desktop/issues/3288)

Pull the user tags (if available) and add those into a `<meta keywords="">` tag in the `<head>` section. This will improve SEO for the content.

---

@tzarebczan commented on [Fri Dec 06 2019](https://github.com/lbryio/lbry-desktop/issues/3288#issuecomment-562717853)

Believe this requires the latest chainquery update to be deployed so we have access to the tags. 

---

@tzarebczan commented on [Thu Oct 28 2021](https://github.com/lbryio/lbry-desktop/issues/3288#issuecomment-954169289)

Also consider views  / uploads. Need to make sure both are in CQ.

**Comment by infinite-persistence** [comment]
[This](https://www.semrush.com/blog/meta-keywords/?kw=&cmp=AA_SRCH_DSA_Blog_Core_BU_EN&label=dsa_pagefeed&Network=g&Device=c&utm_content=515771559997&kwid=dsa-1053501803507&cmpid=12565136841&agpid=119030067266&BU=Core&extid=23631749371&adpos=&gclid=Cj0KCQiAu62QBhC7ARIsALXijXSJ5ifRWhc1S4fogB8h5-w0IXICnfcMrkWvRAg5C0-zNb-B7a_GmRoaAhkGEALw_wcB) and [this](https://en.ryte.com/wiki/Meta_Keyword#:~:text=Meta%20keywords%20is%20a%20type,and%20separated%20with%20a%20comma.) says don't do it as it is useless.  
Not saying that we shouldn't do it -- just passing some info.
