### ISSUE TITLE
Allow setting custom duration option on duration picker

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#1801]
On channel pages, and other areas where we have the duration picker, give an option to set a custom duration (in minutes?), that can be used. Once added, it should persist until changed if possible/easy (doesn't have to be for this release).

**Comment by infinite-persistence** [comment]
How detailed did you have in mind?
- `==` only?
- Support all single ranges through a dropdown + number field? `<, <=, =, >=, >` `minutes`
- <strike>Support in-between ranges as well?  `>` `5 minutes`, `<` `10 minutes`</strike>  _never mind, don't think the SDK supports this_

**Comment by tzarebczan** [comment]
Boo about the range support https://github.com/lbryio/lbry-sdk/issues/2787

Probably just >= and <= to start?
