### ISSUE TITLE
Enabling "hide reposts" on a channel, makes settings permanently expanded(Can shrink in current page, but it's expanded again on next channel entry)

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/odysee-frontend#1802]
1. Go to some channel page
2. Enable "hide reposts"
3. Shrink settings
4. Go to some channel (same or different)
5. Settings are expanded again

**Comment by infinite-persistence** [comment]
"Enabling any filter + fresh click into the page (not using Back/Forward)" would automatically expand it.

I believe the intention was to let the user know there is an active filter running ... the red-highlight of the button might not be obvious.

Can remove if this behavior is no longer wanted.

**Comment by tzarebczan** [comment]
Yea, I recall that now. We do show the red button when there are filters - maybe that's enough? We could also add a warning (vs taking up a bunch of space).

**Comment by toshokanneko** [comment]
The filter section no longer expands by default. Probably not ideal either, but much less annoying in most scenarios for most users. The button is still purple when a filter is active. PR: #1994
