### ISSUE TITLE
Markdown video player floats

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#1818]
https://odysee.com/@dev-test:898c901e7f39b44c5b3f52b1d67a22b185fb3e15?view=about

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/64950861/178000115-da4082ac-45f2-4f7c-bbb5-daecbeb29985.png">

**Comment by tzarebczan** [comment]
Played off-screen and was inaccessible to me.

**Comment by infinite-persistence** [comment]
- [ ] In livestream chat, the embed currently plays in place of the livestream video
