### ISSUE TITLE
Toast: bring back stacked-look (or add hints of multiple items)

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#1819]
- [x] Not dismissing itself anymore
    - _KP:  not reproducible.  Maybe it's just because of the missing stacked look that was causing confusion. Note that hovering over the toast will pause the dismiss timer, allowing the user to read._
- [ ] The "stacked look" is not appearing for multi-toast case ... at least for toasts with the same strings.

**Comment by infinite-persistence** [comment]
`--- unassigned ---`
It was intentionally commented out, so I'll assume it's in the design-todo

<img width="387" alt="image" src="https://user-images.githubusercontent.com/64950861/178684704-e30fb773-0d4f-4dff-8db0-8acb4899df8d.png">

**Comment by toshokanneko** [comment]
I replaced the indicator with an actual counter.
![image](https://user-images.githubusercontent.com/94839278/185334599-78d4f8bd-214f-4790-b81d-c342162a9a80.png)
