### ISSUE TITLE
Support save and share should all be the same size in mobile view

### ISSUE THREAD

**Issue by IronMaltese** [OdyseeTeam/odysee-frontend#1838]
![image](https://user-images.githubusercontent.com/89056889/178779007-843e5ec0-83e3-416d-b260-417bacdd6769.png)

The buttons all being different sizes looks strange, and they should be uniform in their appearance

**Comment by tzarebczan** [comment]
Thank you for filing! Not sure about them being the same size, but should have same padding at least.

**Comment by IronMaltese** [comment]
Thanks for the quick response! It looks much better now 🤙
