### ISSUE TITLE
Don't play video after clicking a comment reply notification

### ISSUE THREAD

**Issue by terminal-root** [OdyseeTeam/odysee-frontend#1849]
# Issue
After I comment on a video I watch, I will sometimes receive a reply to my comment and get a notification. When I click the notification, I am taken to the video page, and the video begins to play from the beginning. This resets the "watched" bar for that video and plays the video when I really only wanted to see the comments.

# (Potential) Solution
One solution could be to not autoplay the video after clicking a notification (specifically comment notifications).
1. User clicks notification
2. Video page loads as it does now (with the page positioned at the related comment)
3. Video is paused at the last played-to position

# Alternative Solution
Another possibility is to implement the ability for users to reply to comments right from the notification list.

# Thank you, OdyseeTeam & Contributors
I'm so glad that there is a competitive platform to stand up to YouTube. Thank you to everyone who helps this project grow. Hopefully I am able to contribute more than just requests sometime in the future.

:)

**Comment by tzarebczan** [comment]
Thank you for filing the detailed issue! 

You should be able to reply if you go to the notification page (not dropdown) also.
