### ISSUE TITLE
adblock check being called multiple times, sets off tracking alerts

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#1868]
Think we use this to see if ads are blocked, but it is loaded multiple times. By trying to load it, we also set off sites that say we use google ads. Maybe there's a better way to do this, or we can work around the need for this check.
![image](https://user-images.githubusercontent.com/8120721/179875198-2d019b64-a685-4dd8-a415-426aa12bacc5.png)

**Comment by infinite-persistence** [comment]
It was meant to be called only once per session, but all the in-content are requesting at the same time.
I think something minor broke when the info was moved to redux. 

Will fix, unless this ticket meant "don't ping google at all"?

**Comment by tzarebczan** [comment]
At least improve to not all multiple times, but probably not a big deal unless it causing issues... Wouldn't spend too much time on it.
