### ISSUE TITLE
Leverage LBRY P2P network

### ISSUE THREAD

**Issue by robd003** [OdyseeTeam/odysee-frontend#1895]
I'd love it if there was an option to connect to the LBRY P2P network from within Odysee. At times the Odysee servers can be overwhelmed and it would be great if when videos are buffering or not loading at all if the data could just be loaded from all of the users running LBRY desktop.

I understand that you'd have to rearchitect LBRY desktop to add in the functionality to serve video streams instead of just the encrypted blobs, but this would be immensely helpful for the continued growth of Odysee.

**Comment by tzarebczan** [comment]
I don't think we'd plan to do this anytime in the near future, it comes with a whole slew of complications with very little added benefit. With the recent improvements to video playback, buffering should be a thing of the past.
