### ISSUE TITLE
Paid content next steps 

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#1906]
You can now pass type, claim_id_filter (claim id originally pre ordered), or reference claim id. This will search both the original claim and the purchase after preorder. 

Clicking the play button will result in the backend get call validating the purchase and retuning a signed url. Nothing special should need to be done there, but we should setup something to read error messages in the case that authorization failed or video is expired (rental). 

We will also support rentals sometime in August, these will be similar to purchase but the tag will be rental:xx.xx:<rental period in seconds>. 

- [x] use filter to look up preorders vs the open ended list query. If reference claim id is returned, that's when you know the purchase claim is available). You'd want to allow navigarion to that claim and show it's available. When calling the tip API, pass type as: preorder

- [x] a fiat purchase claim will have a tag called 'purchase:xx.xx'. if this tag is found, call the list API with claim id filter to see if it's purchased. If so, show a note (you purchased or you preordered if target claim id is different from the reference) and allow play button. If not purchased, show a purchase button either on the play button area, or below. If below video, disable play button. Pass type on the tip call: purchase

Don't worry about rentals for now, but they would work similar to above but we'd show rental details. List call returns expiration time, can show how much time is left if someone purchased it. The tip call would include type: rental and validity_seconds in seconds. A claim may have both purchase and rental tags, show both options. 

Others:
- [x] hide download button if tag has purchas: or rental: 
- [x] disable right click > save video.

Sample claims: https://odysee.com/@gifprofile:7 (use stashu or salt for test stripe).

**Comment by mayeaux** [comment]
Next items:
Embeds of paid content [_]
Show play button that triggers purchase flow [_]
Display that it's paid content in the claim preview tile [_]

**Comment by infinite-persistence** [comment]
- [ ] Mobile overflow
  - <img width="265" alt="image" src="https://user-images.githubusercontent.com/64950861/182517474-429d1608-27af-480a-b936-dbb00293061c.png">
- [ ] Using primary button as a no-action label.
