### ISSUE TITLE
Playlist: can't publish anonymously

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#1910]
- Wallet with 1 channel only
- In Channels Page, ensured the Default Channel is selecting that channel (no other choices).  Also confirmed that the header is pointing to that channel.
- Created a private playlist with 1 item.
- Try to publish the playlist.
- The channel selector is pointing to Anonymous, which is fine -- that was what I wanted.
- When published, the collection went to the default channel. The network dev-tools tab also showed `channel_id` was sent.

**Comment by infinite-persistence** [comment]
I think `https://github.com/OdyseeTeam/odysee-frontend/issues/1890` is also related.

**Comment by infinite-persistence** [comment]
Hm ... If I toggled between Default and back to Anonymous in the publishing page, then it works.
So it feels like the channel selector wasn't reflecting the correct state

**Comment by saltrafael** [comment]
should've been closed by https://github.com/OdyseeTeam/odysee-frontend/pull/2252
