### ISSUE TITLE
Get rid of "on odysee" for RSS

### ISSUE THREAD

**Issue by IronMaltese** [OdyseeTeam/odysee-frontend#1929]
**Is your feature request related to a problem? Please describe.**

When importing my Rss Odysee subscriptions they all have "on odysee” at the end and I have to manually get rid of it for each one

Example:

![image](https://user-images.githubusercontent.com/89056889/182299277-591796fc-73a3-485a-9583-3a90ca849cd9.png)

**Describe the solution you'd like**
Only the channel name should show up in the RSS feed

**Describe alternatives you've considered**
N/A

**Additional context**

Getting rid of this won't affect anything since the user can already see that the feed is from odysee.com

**Comment by tzarebczan** [comment]
This is the only way to signify that Odysee provides the RSS feed, which is why we don't plan to remove it.
