### ISSUE TITLE
Adding a column (:) at the end of a url returns a blank page

### ISSUE THREAD

**Issue by ebenezerdon** [OdyseeTeam/odysee-frontend#193]
**Bug**
Adding a column (:) at the end of a URL returns a blank page with an undefined error message

**To Reproduce**
1. Go to `https://odysee.com/@ebenezerdon:` from the URL bar
2. You should see a blank page with the error message "__ is not defined"

**Expected behavior**
The parent channel should be returned, or the user should see a 404 page.

**Screenshots**
<img width="730" alt="Screenshot 2021-11-01 at 00 25 19" src="https://user-images.githubusercontent.com/43746609/139604701-859a7173-9d06-4e73-ae14-be601cf0d01d.png">

**Comment by tzarebczan** [comment]
Thanks for the report @ebenezerdon ! We're still moving some issues over from an old repo, so I brought this one over as https://github.com/OdyseeTeam/odysee-frontend/issues/202 - it happens in a few other cases.
