### ISSUE TITLE
Uploading a Video or Thumbnail Results in Error

### ISSUE THREAD

**Issue by cahlenlee** [OdyseeTeam/odysee-frontend#194]
**Bug**
Selecting a file to upload on an Android device results in the "There is a bug... somewhere," screen a majority of the time. If the video succeeds then the bug will usually occur when doing the thumbnail forcing you to have to start over.

This has been going on for over a month, and forces me to spend sometimes 10 to 20 minutes repeatedly selecting my video and thumbnail until they both happen to work without an error.

When I write hello@LBRY.com they tell me it's due to a temporary server error, but that doesn't explain how I get the error almost everyday I try to publish a video for over a month.

**To Reproduce**
1. Go to Upload
2. Select a video to upload
3. If error doesn't occur yet, select a thumbnail to upload

**Expected behavior**
No errors occur when files are selected for uploading .

**Screenshots**

https://user-images.githubusercontent.com/30788194/139615969-ef3bb97f-e823-4a24-b8f1-97bafb095975.mp4

**System Configuration**
Android 11

**Comment by tzarebczan** [comment]
See my email reply. Can you please try another browser to see if it happens there? Or maybe a different file picker? It sounds like an incompatibility there and wherever the file is being selected from.

**Comment by cahlenlee** [comment]
It occurs in Chromium, Firefox, Bromite and Brave.

Need to research how to debug in a mobile browser and how to change file picker. Let me know if you have some tips for that .

**Comment by cahlenlee** [comment]
It looks like I need a PC to debug, and I only have an Android at the moment.

I don't see how to change my file picker, but here's its info case it's useful :

com.android.documentsui
version 11

**Comment by tzarebczan** [comment]
Roger that. Can you try again now? It should show the proper error...it was getting caught up in a race condition if the upload failed.

**Comment by cahlenlee** [comment]
The bug still occurs after selecting videos about half the time.  It did not happen with the thumbnail after about 20 attempts, so I think you've fixed that part.

I noticed that the file picker now allows me to choose multiple thumbnails, but not with the videos. Perhaps related to why thumbnails work and videos don't now.

**Comment by tzarebczan** [comment]
I think it's most likely related to the app your running as the picker. Can you try another app there? Which Files app is it? I can try it with remote debugging here.

**Comment by cahlenlee** [comment]
com.android.documentsui
version 11

It's the app that comes native to LineageOS.

I don't know how to change  to a different one.

**Comment by tzarebczan** [comment]
Closing for now, let us know if this happens again.
