### ISSUE TITLE
Fix invites page - button to sign up below content list

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#1954]
This should only be showing 1 row of content, so you don't have to scroll down a bunch to sign up.

Also check the logic on page load - think there's some action that tries to happen before the preferences are loading and it will say 'account not ready'. 

Ensure the invite page still calls the referrer API.odysee.com call successfully.
![unknown-6](https://user-images.githubusercontent.com/8120721/183500658-27fe42d9-61f4-45d2-ba68-2df73eff6ae9.png)

**Comment by tzarebczan** [comment]
This should be a quick one too - at least add the create account/skip to the top section for now.

**Comment by toshokanneko** [comment]
17699f2e073c004876becbeb6e83b750b1b339e4
