### ISSUE TITLE
"Customize Homepage" drag-n-drop has offset issue on Firefox

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/odysee-frontend#1957]
![firefox-drag](https://user-images.githubusercontent.com/34790748/183625258-8add33cd-1207-430d-a55f-3a7afcd8001f.png)

**Comment by toshokanneko** [comment]
Fixed via 9a44130dbdbd48f851df40081cb54ab7681b6bc0 & 54dbb0410927d254c87d40ba4e57a1c10648169c
