### ISSUE TITLE
improve confirmation button text on edits (both live and upload)

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#1966]
On uploads, it shows "upload" - but you may not be uploading anything. Show upload if a new file is selected, otherwise show confirm? 

On livestream edit, it shows "create". Probably show confirm.

**Comment by toshokanneko** [comment]
I'm not quite sure what you did, but both forms should show "Save" when you're in edit mode.

**Comment by toshokanneko** [comment]
In case you were talking about the button in the preview modal, that's now fixed (#1988).

**Comment by tzarebczan** [comment]
Yes, preview = confirmations

**Comment by tzarebczan** [comment]
Thank you!
