### ISSUE TITLE
Profile and investigate site performance

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#197]

**Comment by infinite-persistence** [comment]
It all revolves around the somewhat-expensive `parseURI` being mistakenly overused in wrappers and loops.
- [ ] `isUriValid` was already double parsing for a long while.  The redux consolidation added more of these calls, in busy selectors.
- [ ] `isURIEqual` slows thing down a lot when used in a loop, and it happens to be used in many large loops like subscriptions and blacklists.
    - Introduced back in July -- probably the same timeframe what Jeremy started saying performance has regressed, and Android is unusable?

**Comment by infinite-persistence** [comment]
Closing in favor of #28.

Sub-tasks can also be tracked in:  https://www.notion.so/Lighthouse-Scores-62b8da789d1a4e42ac366e5cba71b652
