### ISSUE TITLE
Empty post description

### ISSUE THREAD

**Issue by michaelmitnick** [OdyseeTeam/odysee-frontend#1970]
Post description content is not visible, only in edit mode.

![brave_k1rig900eA](https://user-images.githubusercontent.com/33647673/184383853-d4fed805-b7bc-4617-bdd6-ca61937e7244.gif)

**Comment by tzarebczan** [comment]
For now, can you try giving that a ### on top or maybe removing the fire? (try one and then other...)

**Comment by michaelmitnick** [comment]
Apparently the emoji is the one causing the problem. Now it works.

**Comment by toshokanneko** [comment]
Already looking into it. I have a very similar description in one of my test pages which works fine although with a frog instead of the fire. The only difference that I can see is the ### right bellow it. Will be fixed asap.
