### ISSUE TITLE
Broken links in post description

### ISSUE THREAD

**Issue by michaelmitnick** [OdyseeTeam/odysee-frontend#1971]
Links coming from YouTube's synced video description break in Odysee. Only links that are 100% visible work. https://odysee.com/@alylohace:6/STICKERSCONINFINITEPAINTER:a

![brave_uHBOroE6e8](https://user-images.githubusercontent.com/33647673/184429619-ce1d0b02-073e-4be6-8f28-e4186342596e.gif)

**Comment by infinite-persistence** [comment]
Checked with Tom, and this doesn't seem like a synced video.  The MD itself is showing the truncated URL, so maybe it was a copy/paste error.
