### ISSUE TITLE
Playlist: adding a thumbnail in private list edit makes playlist crash

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/odysee-frontend#1972]
1. Open local edit page for some playlist 
2. Update thumbnail there
3. Opening playlist crashes page
![playlist-image-crash](https://user-images.githubusercontent.com/34790748/184494707-8ecf8085-1764-4c9f-a813-f4f770a3bbd6.png)

**Comment by tzarebczan** [comment]
Might be related to the recent emoji changes, hmm. What do you mean by local? Localhost?
