### ISSUE TITLE
Design & UI Issues - August 2022

### ISSUE THREAD

**Issue by toshokanneko** [OdyseeTeam/odysee-frontend#1986]
Remaining legacy issues from the last thread:

- [ ] https://github.com/OdyseeTeam/odysee-frontend/issues/1608#issuecomment-1149065058 
grid + wild west = uneven tiles (at least on 6 wide)
- [x] https://github.com/OdyseeTeam/odysee-frontend/issues/1608#issuecomment-1183868021
Restore narrower modal, expand only for specific modals? Close if disagree.
- I believe in https://github.com/OdyseeTeam/odysee-frontend/pull/1271, the modal width was increased so that the tab in the support modal isn't touching the sides in some translations.
- It was easier to read paragraphs when it was narrower. Also, things like the Publish Preview ended up having too much empty space anyway.
- [x] https://github.com/OdyseeTeam/odysee-frontend/issues/1608#issuecomment-1185130037
This came back in the playlist merge (livestream replay page)
![image](https://user-images.githubusercontent.com/94839278/184820347-2c846699-e359-4f6a-a002-2edf91504f9e.png)

**Comment by Abwasserrohr** [comment]
- [ ] The text on the confirm page on paid doesn't look right: (paid pdf, but also looked similar on videos)
![image](https://user-images.githubusercontent.com/44294954/185454069-eef6fb71-a86a-45d9-aeb4-75f37763df5b.png)

**Comment by tzarebczan** [comment]
Also on mobile it's full screen.

![Screenshot_20220818-185507](https://user-images.githubusercontent.com/8120721/185509189-831283ce-bc19-4986-8fc4-c702625489b0.png)

**Comment by infinite-persistence** [comment]
- [ ] Padding, plus anything to make it coherent with the theme

<img width="300" alt="image" src="https://user-images.githubusercontent.com/64950861/185520122-e1a5f048-8db2-4dc0-a333-60f351dbba2e.png">

**Comment by infinite-persistence** [comment]
- [ ] Similar to the recent sidebar issue, but now `/$/Following/Manage`

<img width="538" alt="image" src="https://user-images.githubusercontent.com/64950861/185549505-c44aa15e-bae1-4b5d-931d-48c35efa03f8.png">

**Comment by infinite-persistence** [comment]
- [ ] Padding + weird-looking in general (the name being aligned the same as the icons)

![image](https://user-images.githubusercontent.com/64950861/185549999-94c87bb4-bdf4-4804-af85-af68ef140e0b.png)

**Comment by infinite-persistence** [comment]
- [ ] Just happen in certain widths, so it's minor

<img width="500" alt="image" src="https://user-images.githubusercontent.com/64950861/185552116-c1cd4f69-42c5-441a-94aa-7957e0755816.png">

**Comment by infinite-persistence** [comment]
- [ ] In a channel page + followed + hover of the follow button = clip for some languages

![image](https://user-images.githubusercontent.com/64950861/185552387-eb6c94e3-2fab-4595-a923-09bce0e8f315.png)

**Comment by infinite-persistence** [comment]
- [ ] Notification highlight in light theme

![image](https://user-images.githubusercontent.com/64950861/185821926-88182e94-d140-430b-9b8e-9db5141761ff.png)

**Comment by infinite-persistence** [comment]
- [ ] Can't dismiss sunset nag on Firefox Android if signed in.  Button visible if signed out.

<img width="243" alt="image" src="https://user-images.githubusercontent.com/64950861/185860947-94dbbbd6-1875-42c9-b3c9-f9a720c5f3e0.png">

**Comment by infinite-persistence** [comment]
It also affects other languages and potentially other homepage orders, so a per-language solution might not be good.

<img width="483" alt="image" src="https://user-images.githubusercontent.com/64950861/186076278-78bc508f-df5b-4742-a812-73b31482883a.png">

But, as noted, it's only on a very specific width, so feel free to close if it's not worth addressing :+1:

**Comment by infinite-persistence** [comment]
- [ ] In dark mode, the text becomes red when highlighted

![image](https://user-images.githubusercontent.com/64950861/186349870-478d6d45-4dcf-4809-82c5-780e05937252.png)

**Comment by Abwasserrohr** [comment]
- [ ] Verification text is white on light mode:
![image](https://user-images.githubusercontent.com/44294954/186928421-cd8f0950-4d0c-4613-a81d-a4c4a7a292ec.png)

**Comment by Abwasserrohr** [comment]
- [ ] Not sure if it's a design issue, but earlier there has been a YouTube Sync button which is no longer on that page if you have no channels, could we add that back in? https://odysee.com/$/channels
![image](https://user-images.githubusercontent.com/44294954/186935662-e7a8e5fa-da3d-4013-846f-f4c3afa7fc63.png)

**Comment by tzarebczan** [comment]
![Screenshot_20220827-101123](https://user-images.githubusercontent.com/8120721/187033925-4a0d5f85-748a-47f0-a77d-13b81adac7f5.png)
https://odysee.com/@logosliterature:1/the-house-of-starless-sky-chapter-1:3

Channel name overlap?

**Comment by Abwasserrohr** [comment]
- [ ] In [Settings](https://odysee.com/$/settings) on mobile, the credits button is not round:
![image](https://user-images.githubusercontent.com/44294954/187171965-fe88fdcc-3906-4928-94ad-fc2a6486ac61.png)

**Comment by Abwasserrohr** [comment]
- [ ] There are two tab dividers on mobile in the [wallet](https://odysee.com/$/wallet?tab=credits)
![image](https://user-images.githubusercontent.com/44294954/187205489-4c225a1c-6a09-4120-8dec-9f6f702a99e5.png)

**Comment by infinite-persistence** [comment]
- [ ] Chapters lost its padding

![image](https://user-images.githubusercontent.com/64950861/187795693-c94b1b5c-4ff7-4e93-be0c-3ad8b5639a13.png)

**Comment by infinite-persistence** [comment]
- [ ] Links in static page hard is to read
    - https://odysee.com/$/tos -- (dark blue over purple)
    - Career listings -- gray `mailto` link.  I think it could use the red one like in `/$/fyp`, unless it was a stylistic choice to make it less prominent.
