### ISSUE TITLE
Rentals / purchase follow-up

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#2000]
- [x] Handle "user as customer is not setup yet"
  - <img width="458" alt="image" src="https://user-images.githubusercontent.com/64950861/185218702-feff9e58-aa42-4f1f-a624-c2d409bd1891.png">
  - Steps:  open up Incognito and play a video.  Reverting the rentals commit prevents this.
  - No crash or anything, just that sentry was picking it up.  
  - Maybe due to the `await Lbryio.call` -- does that handle the failure case?  
  - Probably doesn't affect anything behavioral-wise, but an indication of bad code.

**Comment by infinite-persistence** [comment]
- [ ] Crash when trying to purchase https://odysee.com/@gifprofile:7/after-preorder:b

**Comment by tzarebczan** [comment]
- [ ] add rental to claim preview if has both rental and purchase tags
- [ ] add preorder to claim preview (only if active - i..e no full upload)
- [ ] pre-order content - shows "click here to view your purchased content" without a purchase/rental. Should have the other button which says go to content or whatever
- [ ] rental + purchase tag + rental expired:  says : thanks for purchasing. Should probably say something about the rental being expired, and give option to rent or purchase again.

**Comment by mayeaux** [comment]
Use `startsWith` for tags matching
