### ISSUE TITLE
Playlist: Random crash on playlist page during playlist confirmation (probably)

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/odysee-frontend#2007]
Got some crash on main playlists page. Kind of seemed like it had something to with a published new list waiting for a confirmation.
Crashes seemingly stopped when next block got created.

Haven't been able to repro so far. (Though I think I have seen same error in the past once)
![playlists-crash](https://user-images.githubusercontent.com/34790748/185419900-0b262740-d8d6-4f0d-9b7e-0f175c6f6f4a.png)

**Comment by tzarebczan** [comment]
Another user is seeing this persistently. @infinite-persistence can you look tonight?

**Comment by saltrafael** [comment]
should've been closed by #2021 (?)
