### ISSUE TITLE
Odysee does not load videos / thumbnails when on VPN

### ISSUE THREAD

**Issue by robd003** [OdyseeTeam/odysee-frontend#2016]
When connected to a VPN Odysee fails to load thumbnails / videos. As soon as I disconnect both thumbnails and videos load.

I can't even **connect** to the thumbnail / video hosts so it seems like an overprotective firewall banning half of the internet.

Could you please check to make sure that you aren't banning all routes from AS9009?

**Comment by IronMaltese** [comment]
> When connected to a VPN Odysee fails to load thumbnails / videos. As soon as I disconnect both thumbnails and videos load.
> 
> 
> 
> I can't even **connect** to the thumbnail / video hosts so it seems like an overprotective firewall banning half of the internet.
> 
> 
> 
> Could you please check to make sure that you aren't banning all routes from AS9009?

This also happens in #1052 but with Tor

**Comment by tzarebczan** [comment]
Which VPN are you using @robd003 ? Can you get the error from the network tab or console, or if you copy/paste the player.odycdn.com url directly into browser?

**Comment by robd003** [comment]
AS9009 is for Mullvad

The problem is that Stackpath appears to be flat out denying connections to port 443 from all of 89.45.224.0/24

The connection attempt simply times out.

**Comment by tzarebczan** [comment]
We'll reach out to them about this, thank you!

**Comment by tzarebczan** [comment]
@robd003 can you grab a HAR from chrome and upload here when this happens? Or maybe screenshots of the headers  + console?

**Comment by tzarebczan** [comment]
@robd003 is it still happening? Is so, can you provide the above?
