### ISSUE TITLE
Referenced Javascript returns HTML instead of JS

### ISSUE THREAD

**Issue by robd003** [OdyseeTeam/odysee-frontend#2025]
I noticed a weird issue when loading pages on Odysee.

This file is referenced via <script src=""> tags but is HTML and not javascript: https://odysee.com/public/ui-4bec2bee-5e6d-4326-80ae-f6e7de0f387d.js

**Comment by tzarebczan** [comment]
Going to see if https://github.com/OdyseeTeam/odysee-frontend/pull/2013 fixes it, technically should...

**Comment by tzarebczan** [comment]
Give it a refresh  - should no longer reference it anywhere now?
