### ISSUE TITLE
Investigate `redux-state-sync` to address tab sync problems

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#2037]
Preference-syncing is an open issue that we all know. 
Having multiple tabs open is one of the problematic scenarios, where the tab-focus method might not be fast enough since it ends up doing an API call round-trip.

https://github.com/AOHUA/redux-state-sync might be a solution to eliminate the API calls for the tab-to-tab (same PC) case.

**Comment by tzarebczan** [comment]
I was looking into this a couple weeks ago and was going to suggest we look, but wasn't sure how prevalent of a problem this is. But i guess some of the missing data scenarios might be related if we don't have other ideas.

**Comment by infinite-persistence** [comment]
Yeah, when trying to create playlists from multiple tabs today, my effort was lost because things are out of sync :(
