### ISSUE TITLE
`replaceAll` error in `videojs-vtt-thumbnails`

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#2039]
We substituted all `replaceAll` usages to the regex version in our app.  Need to do the same in the vtt repo

<img width="527" alt="image" src="https://user-images.githubusercontent.com/64950861/186441397-6b727e8a-4a2a-4c30-b461-0284edc4195a.png">

**Comment by tzarebczan** [comment]
I guess even something like a polyfill wouldn't work for this?

**Comment by infinite-persistence** [comment]
We are using Anthony's fork https://github.com/OdyseeTeam/videojs-vtt-thumbnails
Haven't figure out how it works -- need to bump version, or does it take latest `master`?
