### ISSUE TITLE
i18n file not updated

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#2046]
New strings are being pushed to and translated in Transifex, but the output has been stuck for a week.

`https://lbry.com/i18n/get/lbry-desktop/app-strings/*.json`

lbry cut us off?

**Comment by tzarebczan** [comment]
Which part would be cut off? Hm

**Comment by infinite-persistence** [comment]
Uploading to `lbry.com/i18n`?
Not sure how things work at the Transifex side.

**Comment by tzarebczan** [comment]
There's also this endpoint, wonder if that had something to do with it? https://lbry.com/clear-cache

**Comment by infinite-persistence** [comment]
Seems to be working now after clicking it

**Comment by tzarebczan** [comment]
woohoo! Thought it was cleared automatically at some point. 

This is on the list of things to move over...
