### ISSUE TITLE
Push notifications in Brave not working

### ISSUE THREAD

**Issue by michaelmitnick** [OdyseeTeam/odysee-frontend#205]
I have been going through and editing different site settings in the settings in Brave and the error message is still popping up. I'm not sure whether to clear browser or site cache, but naturally it should work for the average user.

Also, I don't see any Push settings in Brave, only site notifications and permission settings. Maybe just for Chrome.

![image](https://user-images.githubusercontent.com/33647673/139741284-b633c71b-4786-4872-b331-f2102d119eb2.png)

**Comment by tzarebczan** [comment]
This is the one for brave - it needs to be restarted after (a relaunch button appears): 
![image](https://user-images.githubusercontent.com/8120721/139741665-6af29529-457a-4c51-8c18-a599204e6838.png)

**Comment by michaelmitnick** [comment]
I already found the problem. Brave in its Spanish version has changed the name to the Push notification for something totally different and unrecognizable. I will inform the community. Thanks

![image](https://user-images.githubusercontent.com/33647673/139741982-8426be9a-4fde-4daa-a9e6-e01f8ba13a12.png)

**Comment by tzarebczan** [comment]
Once we have the translations up, that should be used directly!
