### ISSUE TITLE
Enable BitChute sync with Odysee

### ISSUE THREAD

**Issue by robster7674** [OdyseeTeam/odysee-frontend#2064]
**Is your feature request related to a problem? Please describe.**
No problem.

**Describe the solution you'd like**
It would be great if people could sync their Bitchute channels with Odysee, similar to how it can be done for YouTube. 

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by tzarebczan** [comment]
Don't think Bitchute has APIs for authentication or listing all content on a channel, so this probably won't happen anytime soon.

**Comment by robster7674** [comment]
@tzarebczan : looks like they are a bit behind on schedule. ;)

https://support.bitchute.com/features/api-target-april-2020
