### ISSUE TITLE
Save button scaling broke on mobile

### ISSUE THREAD

**Issue by IronMaltese** [OdyseeTeam/odysee-frontend#2068]
**Bug**
![image](https://user-images.githubusercontent.com/89056889/186956135-8fb039db-00e0-44c5-98aa-29ae48dea86c.png)
**To Reproduce**

**Expected behavior**

**Screenshots**

**System Configuration**

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Additional context**

**Comment by IronMaltese** [comment]
Fixed now :)

**Comment by tzarebczan** [comment]
Ty for the report!
