### ISSUE TITLE
odd length string playlist error

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#2073]
@saltrafael has the details, a few people have run into this.

**Comment by SkySpiral7** [comment]
Seems to happen when trying to publish any update to any playlist. Example from console:
`{"code":-32500,"message":"Odd-length string","data":{"args":[],"command":"collection_update","kwargs":{"bid":"0.00100000","blocking":true,"channel_id":"3c608bf7b6dbd74f3caf4322c0fbc3d689e9bb8e","claim_id":"b3f9c94c42d5bed45997981ee78d1453e8a2b660","claims":["549202938d986cc072bc897b69edca2a8d48e597","fca64a2cb4e69919e4aaa0d1cfcbc369b1fe6224","b3be458de75be81bff1ee921f63c818f82da79a3","1bcdbc9d65787920dde8511a0f5d0e11aa9e3d82","d11a2cd6649c6977b126978490db1005510085fc","f6ab1b7a2604ec05160d1feb79847805590e166b","d7be8cd33859b6ab435c2eb5ccd8ea24547626c7","8d9b3d862ccb5845b7fc817a80e1f69356be710e","b81c5041e77893033e683b7d4c0a252b8e8d75a4","b444249c3b18174cc5ca0e398ea940b3857a3c70","e8c078ec108ddb3e71f752d72aede282770a7ada","a67e893344ced91547d1b076a52b83811616ccb3","1d76189ab78830f442e8e25617d732cb54928ce4","6add610ac3b0ffa3b814d359c584cea36806e14e","a1b5d693f32a6fa1fff12ea04c62a23314db9a77","db52ae275d9e5c7ea9270f0e942e99f0718a0f62","475cd779c239026db58820682b97491c5df3156b","6e003802c79839679e255eea81b2ebb7b1a6a6eb","4d71befc488ce34ac51b7317b215776c27faf35a","2222a5e2c04c018ec2d6418dd464772fc9ce10dc","423e4201c05dc555d8d93cc6309d244508dcb85c","4262b2b690cf7e544bb52fbf2db7392a1fd29dac","213fb3f7406a9028a17e66468724f8b7ee1a4e62","3","3","3"],"clear_claims":true,"description":"Everything from my Hollow Knight gameplay that isn't included in https://odysee.com/$/playlist/efb4986d8392522ea7bce22c4c04cf26113c03e7","languages":[],"locations":[],"replace":true,"tags":["letsplay","hollowknight","video games"],"title":"Hollow-Knight-extras","wallet_id":"lbrytv-id.517159908.wallet"},"name":"Error","traceback":["Traceback (most recent call last):","  File \\"lbry/extras/daemon/daemon.py\\", line 723, in _process_rpc_call","  File \\"lbry/extras/daemon/daemon.py\\", line 4151, in jsonrpc_collection_update","  File \\"lbry/schema/claim.py\\", line 146, in update","  File \\"lbry/schema/base.py\\", line 105, in extend","  File \\"lbry/schema/attrs.py\\", line 383, in append","  File \\"lbry/schema/attrs.py\\", line 362, in claim_id","binascii.Error: Odd-length string",""]}}`

**Comment by SkySpiral7** [comment]
Actually there may be multiple instances of that error message since this issue was created Aug 29 but I was able to post last week but not today. https://www.reddit.com/r/odysee/comments/yf9242/oddlength_string_error_on_odysee_when_attempting/ was posted 2 days ago and sounds to me like it's blocking everyone now.

**Comment by tzarebczan** [comment]
There's a fix in the works and it should be out next week. Try it on salt.odysee.com

**Comment by SkySpiral7** [comment]
@tzarebczan yep I was able to get it to work on salt. I already posted a comment on the PR https://github.com/OdyseeTeam/odysee-frontend/pull/2309#issuecomment-1296068178
