### ISSUE TITLE
Embed: `?feature=latest` causing infinite set-states

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#2092]
- From [sen_22570](https://sentry.lbry.tech/organizations/odysee/issues/22570)
    - The `setIsFetching` stack trace might be a red-herring.
    - **In the breadcrumbs, a lot of `user/referral` is being sent.  Maybe this is a better clue.**
- One example of the embed is here (bottom of page): https://www.oval.media/aaf105c4-de54-4643-9a0b-1efdf8aafaad/
    - or this `<iframe id="odysee-iframe" width="560" height="315" src="https://odysee.com/$/embed/@ovalmedia?feature=latest" allowfullscreen></iframe>`
- Locally, the max I've seen is 4 API calls, so still missing the recipe to make it infinite.  The log says it's mostly on mobile .. haven't tried that.

**Comment by tzarebczan** [comment]
Noticed this today too while testing some stuff with future embeds. After a few refreshes, i got it to start continuously spamming.

We're going to have someone using this embed more actively on their site, so it would be nice if it worked properly.
