### ISSUE TITLE
setting "Default Video Quality" requires a refresh of video to take effect

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#2134]
<img width="652" alt="image" src="https://user-images.githubusercontent.com/64950861/188895099-d6c724c9-732a-41dc-96db-ccc448161c42.png">

I have it set at 144p, which https://odysee.com/@AlphaNerd:8/the-tik-tok-data-breach-is-fake!-for:e supports.  But it either sets to `auto` or a previous non-auto value that is not 144p.

I do see the button on the video player flash between few settings at times, though.

**Comment by tzarebczan** [comment]
Seemed to work here. Did you save the settings? Refresh help? Check network tab too to see which version it's playing ... v3 is 144p

**Comment by infinite-persistence** [comment]
Oh, requires a Save + Refresh.

Repro:
- Select one video with all the transcoding options.
- My default was "Auto", and it played with "Auto" -- great.
- Settings > Default = 360p > Save
- Load same video -- it's stuck at Auto
- Load a different video -- stuck at auto
- Refresh and load the same video -- working now
