### ISSUE TITLE
autoplay doesn't work with embed

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#2138]
User was trying to setup auto play here: 

Iframe looks like, which has the right param in iframe (and extra on url, not sure if needed) 

```
<iframe width="560" height="315" src="https://odysee.com/$/embed/let%27s-cook-wagyu-enhanced-brisket/498bec51b0ddc7f0411d7c1f923fba3650967f4c?r=5bSHWQjmQaAAz3TLKy6sTN1c46xUTmVT&amp;autoplay=true" title="Odysee video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen=""></iframe>
```

**Comment by edde746** [comment]
Not familiar with the codebase, but [here](https://github.com/OdyseeTeam/odysee-frontend/blob/master/ui/component/fileRenderInitiator/view.jsx#L119) shouldAutoplay is set to false if embedded is true.

**Comment by tzarebczan** [comment]
You're right, will adjust that today.
