### ISSUE TITLE
thumbnail not re-populated when editing playlist

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#2142]
Getting some reports of this, but haven't reproduced. @keikari can you try?

**Comment by keikari** [comment]
Hmm... seems to re-populate fine here, with public and private lists. In edit and publish form.

Closest I got was something like this, but probably different:
1. Publish/update list (change channel if updating, I think)
2. Wait on the list page for publish to confirm
3. Once confirmed, click "Publish"
4. All fields except list items are empty
5. Refresh fixes
