### ISSUE TITLE
scroll resets on homepage when expanding sidebar

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#2148]

**Comment by tzarebczan** [comment]
This seems to be the worst when you scroll down very far on the homepage, and then expand. Less noticeable in other scenarios. This will need a deeper look in a couple weeks.

**Comment by toshokanneko** [comment]
This is fixed in my `channelpage-revamp` branch. I removed the transform effect to make the scroll effect on the new channel pages work. This fixes both issues at once.
