### ISSUE TITLE
Cache stuff 

### ISSUE THREAD

**Issue by jxxp9** [OdyseeTeam/odysee-frontend#2154]
**Is your feature request related to a problem? Please describe.**
The site is pretty slow and takes a lot to load

**Describe the solution you'd like**
Cache all the cacheable

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by tzarebczan** [comment]
Where are you located and how's your bandwidth? Which part exactly is slow? There's various layers of caching in place already. Email us at hello@odysee.com with more details.
