### ISSUE TITLE
Memberships v1 remaining items

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#2159]
<details>

- [x] chat support and required changes, Anthony has on slack. Also make same changes for super chat list. Web socket still needs work, we'll probably at least do something that's not the content claim id for v1 (we'll see how far we can get).
- [x] add membership icon to notifications related to memberships. Right now there's only one when a creator gets a new member, category Memberships, type is new_member.
- [x] disable download button and right click on members only content
- [x] hide member only content on categories, and homepage categories. Leave on following / wild west. Do this by appending the c: members only tag to not tags claim searches.
- [x] Option to hide member only content on channel pages (similar to reposts) (via not tags)
- [x] Option to hide member only content site wide in Settings ( via not tags).
- [x] if livestream is members only, take the Livestream url and pass to the backend get call, with URI (like a normal get call) and base_streaming_url (Livestream url). This will return streaming_url like it does for static content, but with signing information. 
- [x] make sure tags bug on publish flow is fixed (you'd select a tag, but it wouldn't add it). Think this was when I was trying to manually add a c:members-only tag, but not sure. 
- [x] make sure editing works nicely with member only livestreams, where you'd upload replays. Also make sure editing works for member only content (shows which tier your publishing for). 
- [x] when clicking a membership from a channel, you get a confirmation which lists all the tiers again and shows the one you selected. It's not super clear on the top list that this is what's happening, not clear that the item you clicked is selected.

</details>

Feel free to add items from your list too.

Maybe @infinite-persistence can help with the claim search changes.

**Comment by infinite-persistence** [comment]
- [ ] Missing members-only green padlock fetch in Category Pages.  It will only appear if you enter the claim and go back.

**Comment by tzarebczan** [comment]
More:
- [ ] livestream member only page - add overlay similar to static content, with ability to join. Make sure it autoplays after. 

Nice to have:
- [ ] smooth out direct page load scenario. It briefly shows membership required even though I have access.  https://anthony.odysee.tv/@gifprofile:7/members-only:7
- [ ] ability to join a membership from the channel page when clicking a tile, and then load the content page right after.

**Comment by mayeaux** [comment]
- [ ] Exclude Odysee from having a join button 
![Screen Shot 2022-09-26 at 2 29 44 PM](https://user-images.githubusercontent.com/7200471/192276507-9f9e0ec0-71da-4e5e-81d6-1514e7cb9639.JPG)

- [ ] Bug when filtering memberships when multiple memberships have tiers but selected doesn't
![Screen Shot 2022-09-26 at 2 25 41 PM](https://user-images.githubusercontent.com/7200471/192276607-f11cb372-c350-40c0-a40c-fb8af60ac2fb.JPG)

- [ ] Use the data from `doGetMembershipSupportersList` to populate the overview page with real data (though I don't think we will show Total Received anymore)
![Screen Shot 2022-09-26 at 3 01 34 PM](https://user-images.githubusercontent.com/7200471/192283298-02c22d5e-4957-40e8-92ef-ddfc9ddfdeb7.JPG)

**Comment by tzarebczan** [comment]
- [ ] Still showing premium badges right ? 

https://github.com/OdyseeTeam/odysee-frontend/pull/2147#discussion_r970971491

**Comment by toshokanneko** [comment]
- [ ] Protected content only seems to work for videos/streams. Image pages, post pages etc. just return an error. Context menu on these pages (3 dot) is broken.

- [ ] Can't comment on my own protected content => error message

- [ ] Billing history tab

- [ ] Creators to support tab

- [ ] Supporters call returns channel name instead of unique id

**Comment by tzarebczan** [comment]
- [ ] prompt users to add credit card if they don't have one when purchasing.

**Comment by infinite-persistence** [comment]
Sanitize please:
- [ ] Ensure all images have been removed.
- [ ] Remove defunct http://localhost:9090/$/membership_history

**Comment by tzarebczan** [comment]
For later:
- [ ] add restriction selection to confirmation page 
![image](https://user-images.githubusercontent.com/8120721/194098024-83aa78ff-3b62-4ad1-a9e4-0ad127a4d273.png)
