### ISSUE TITLE
hide tags filter on channel pages in filter menu

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#2171]
There's some feedback that having a search + tag search on channel pages is confusing. One idea would be to hide the tag search under the filters option similar to what we had originally done. Leave everywhere else as is.

**Comment by infinite-persistence** [comment]
I gave this a shot today, and can have a PR up after some cleaning up.

However, it doesn't seem to be solving the issue at hand, which is "multiple search bars".  Also, it introduces inconsistencies in the placement of the widget.

Another idea:  
If we are willing to remove the other right-hand-side items like "Results boosted by LBC", maybe we can place the search bar there. In the case of Channel Page, the search bars will be combined, where the icon will be a dropdown that toggles between Tag and Magnifying glass.  This will require a little bit more effort of pulling things out, but do-able.
Cons: also somewhat doesn't address the main problem.
```
| New | Trending | Top |                           |Icon v| --- enter query ---  |
```

If the one in the original description is still preferred, just let me know -- can do that too :+1:

**Comment by tzarebczan** [comment]
Drew said that sounds just about as confusing, so lets try the first idea still, for channel pages. Maybe Rave can do a styling pass later. 

Also, while you're there, can we do this:

if searching tags anywhere, remove the limit per channel and release time params from the claim search.
