### ISSUE TITLE
App Forgets Open Video While in Background

### ISSUE THREAD

**Issue by Chiramisu** [OdyseeTeam/odysee-frontend#2179]
**Bug**
App loses / "forgets" open video and resets view after an hour or so of running in the background, requiring us to navigate back to the video (if we can remember it) and start it again.

**To Reproduce**

1. Open any video, preferably a long one (e.g. 10+ mins), and start playing it.
2. Wait a couple minutes into the video.
3. Pause the video and switch to another app, so Odysee is running in the background (DO NOT close it or swipe it away).
4. Wait for an hour, or two if that's not long enough, then switch back to Odysee.
5. Odysee resets back to the Home screen as if it were launched from scratch and you have to find your video again.

**Expected behavior**
The app should remember the video I'm currently watching indefinitely and restore the exact view as-is when the app lost context and went into the background, even with battery optimization on. On Android, you can see a thumbnail in your task switcher of the last thing that the app showed when it lost context, which is exactly what I expect to see restored when I change back to the app.

**Screenshots**

**System Configuration**

Not Found

- LBRY Daemon version: ?
- Odysee App version: 0.0.61 (Google Play)
- LBRY Installation ID: ?
- Operating system: Android 13

**Additional context**
Fortunately, Odysee at least remembers the playback timestamp where we left off, unlike Rumble 🤮 (deal breaker).

**Comment by tzarebczan** [comment]
Until we have the native app out which is being worked on, I don't think we'll have any fixes here. Many things can kill background apps on a variety of phones. Hopefully you should be able to go to watch history to see the video there still.
