### ISSUE TITLE
possible to delay / lazy load emojis

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#2180]
If you access a content page, you get tons of emojis loaded. If it's used on the page, can it load the ones it needs, and then load rest if someone goes into emoji picker? 
![image](https://user-images.githubusercontent.com/8120721/191600127-1668dd5c-3165-4d44-8511-892f896a0fa3.png)

**Comment by infinite-persistence** [comment]
Ah, saw that too and have been trying to pinpoint the component.  

It's lazy-loaded in mind, but must have slipped somewhere.

https://user-images.githubusercontent.com/64950861/191921301-931ea556-4164-49c3-95d6-e9db930f544c.mp4

**Comment by infinite-persistence** [comment]
- Chrome:
    - Fixed a few items missing the lazy attribute. It should be lazy-loading now unless I missed any.
    - Note that the algo is browser-based, so we don't have control over the exact amount of off-screen images to load (but amount looks reasonable from here).
- Firefox 105:
    - Seems broken.  Support for `loading="lazy"` was added since Firefox 96.  Need to investigate what's wrong.
    - Opinion:  should not bring back our old `IntersectionObserver` implementation since browsers will be supporting it moving forward.  If want to bring back, [do it efficiently this time](https://www.bennadel.com/blog/3954-intersectionobserver-api-performance-many-vs-shared-in-angular-11-0-5.htm) or use a library.

**Comment by infinite-persistence** [comment]
Scratch that ... not related to Firefox.  Even on Chrome, I sometimes get the initial screen from the description, sometimes get the correct loading behavior as depicted in the video.  Maybe related to the MUI wrapper

**Comment by infinite-persistence** [comment]
Something with the Reach Tab is causing the `loading="lazy"` to be non-functional at times?

- Can't do the usual "don't mount tab panel until visible" trick as a quick fix, since the reveal-animation depends on the emojis (at least the first page) to be mounted first, otherwise it looks laggy.
- Also can't use `<WaitUntilOnScreen>` to lazy load the emoji pages either, since the scroll-to-category behavior relies on a mounted object.
