### ISSUE TITLE
Update browser window title when notifications are received

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#22]
@kauffj commented on [Mon Mar 22 2021](https://github.com/lbryio/lbry-desktop/issues/5727)

When you have an active notification (number over the bell icon), the page title should be updated with something like
`{title} ({unread_notification_count})`

You can test this by creating a separate channel, then commenting on an upload from your first channel.

---

@pranav1601 commented on [Mon May 10 2021](https://github.com/lbryio/lbry-desktop/issues/5727#issuecomment-836784156)

Hey, could i take up this issue?

---

@kauffj commented on [Mon May 24 2021](https://github.com/lbryio/lbry-desktop/issues/5727#issuecomment-847116366)

@mayeaux is going to begin work on this

**Comment by mayeaux** [comment]
Maybe it's logical for @dan-peterson to look at this? @tzarebczan
