### ISSUE TITLE
`/$/latest` "reading 'stream'" crash

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#2206]
- https://sentry.lbry.tech/organizations/odysee/issues/30050
- https://odysee.com/$/latest/@Bicituristas:5

<img width="459" alt="image" src="https://user-images.githubusercontent.com/64950861/192471630-bd76e262-f663-452d-aaf1-be7ef5d11439.png">

**Comment by tzarebczan** [comment]
Probably the no content case.
