### ISSUE TITLE
Publish v3 fall out

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#2209]
- [x] "The file is still being processed. Check back later after a few minutes."
   - Shouldn't be displayed as an error because it is not.
   - Maybe loop forever (instead of 2 minutes) if the status remains the expected `202`, and only stop on error?
   - Show "last checked" timestamp so users are assured it is still alive and don't need to worry.
   - Improve logging -- we still want some insight, but probably not for every call.
- [x] Some errors not logged to Sentry. Can get more insight from the breadcrumbs there.
- [ ] "The upload does not exist.".  Not expecting this.
    - <strike>Confirm that item exists in server even long after claim is confirmed (it was during initial testing).</strike> ==> still does, so that's not it
    - Should be due to unhandled v2 to v3 transition.

**Comment by infinite-persistence** [comment]
- [ ] "The upload does not exist.".  Not expecting this.
    - Confirm that item exists in server even long after claim is confirmed (it was during initial testing).

**Comment by cemerson** [comment]
Guessing you guys don't need end-user input but I'm seeing this error/msg today. 
![error](https://i.imgur.com/uofaBto.png)
Related upload: lbry://safe-and-effective-a-second-opinion-2022-oracle-films-2022-09-28

**Comment by infinite-persistence** [comment]
`--- close ---`
I think this is closed.
