### ISSUE TITLE
Paid content upload support + UX / UI improvements

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#2210]
Overview: currently we're using tags to setup / detect purchase/rental and preorders. For now, let's skip preorders. The tag process is manual at this time, the goal here is to add something to the publish flow on all modes that allows a user to setup a purchase and/or rental. We would check for their bank account connection, and show this option, otherwise hint to setup one up to enable. We should be able to support both LBC and USD at the same time, but for now, you can grey out LBC price settings if USD is selected. 

On top of the purchase:xx.xx / rental:xx.xxx:sssssss tags, we should convert these to use the c:, and also add a separate tag for c:purchase, and c:rental. This will make it easier to filter via claim searches, since we can't do fuzzy tag searches. Both cases should hide the tags like we do with other control tags. 

The price must be in xxx.xx format, and must have a period and 2 digits. For rental, the ssss is added as seconds, but allow users to choose hours/days/months. 

Only USD and EUR is supported, and USD is treated at 1:1 currently (maybe make not if someone has non USD denom bank, not sure?). 

Others:
- [ ] add rental to claim preview if has both rental and purchase tags. Don't overwhelm the thumb, find some nicer way to show? 
- [ ] Show play button that triggers purchase flow
- [ ] mobile overflow + primary action as message: https://github.com/OdyseeTeam/odysee-frontend/issues/1906#issuecomment-1203447231
- [ ] Use startsWith for tags matching (https://github.com/OdyseeTeam/odysee-frontend/issues/2000#issuecomment-1222381268)

nice to have: 
- [ ] support embeds where you can purchase right from it / play it if you already have access

**Comment by infinite-persistence** [comment]
- [ ] "Price" seems to be missing in Replays in production.
