### ISSUE TITLE
API for fetching channel/video information

### ISSUE THREAD

**Issue by highlanderdev** [OdyseeTeam/odysee-frontend#2211]
**Is your feature request related to a problem? Please describe.**
I am trying to dynamically embed our videos on our company website so that new uploads will automatically be featured . It seems currently the only way to do this is using the RSS feature which is not ideal. It causes slow page loading, because the whole feed needs to be fetched. It also is not very fun working with XML. Aside from that, the RSS feature also appears to  have a strict CORS setting, making the only solution I've found is to use a proxy.

**Describe the solution you'd like**
Ideally, an API that can deliver a  smaller batch of channel/video information in JSON.

**Describe alternatives you've considered**
A faster solution would be to give the ability to whitelist a domain on our channel, so we can use the RSS feature. This, however, still won't fix the slow page loading issue.

**Additional context**
If there's any existing feature that can solve my problem that I don't know of, please let me know. Thank you!

**Comment by tzarebczan** [comment]
Are you trying to embed multiple videos at a time, or only the latest one?

**Comment by highlanderdev** [comment]
Multiple videos. For example, the 5 most recent videos will be shown, and the user can hit next to show the next 5.

**Comment by tzarebczan** [comment]
Email us at hello@odysee.com and reference this chat + provide your channel, we'll get a query over that will give you the embeds via json. At this time we probably wouldn't support accessing outside embeds, and I know showing multiple embeds is a bit ugly right now. Eventually can maybe support a special embed type of multiple videos.
