### ISSUE TITLE
Design & UI Issues - October 2022

### ISSUE THREAD

**Issue by toshokanneko** [OdyseeTeam/odysee-frontend#2226]
Remaining legacy issues from the last thread:

- [x] https://github.com/OdyseeTeam/odysee-frontend/issues/1608#issuecomment-1149065058 
grid + wild west = uneven tiles (at least on 6 wide)

**Comment by infinite-persistence** [comment]
- [ ] Button overflow

A combination of button being too verbose + general i18n problem :(


<img width="273" alt="image" src="https://user-images.githubusercontent.com/64950861/194203664-b0dbd5b3-821c-4a4f-9dab-2e30c128da4f.png">

**Comment by infinite-persistence** [comment]
- [ ] Mobile header title

<img width="283" alt="image" src="https://user-images.githubusercontent.com/64950861/194206139-fe8c2462-f6e7-4721-929e-c9ca0ceca6dd.png">

**Comment by tzarebczan** [comment]
- [ ] chat goes to 2 lines when moment rolls over
![image](https://user-images.githubusercontent.com/8120721/194585541-88a54952-fbda-43e2-a0d6-27f222abbef3.png)

**Comment by infinite-persistence** [comment]
- [ ] Share Modal > Embed > Light Theme -- copy button text color incorrect

<img width="250" alt="image" src="https://user-images.githubusercontent.com/64950861/195076095-604132a3-a0ba-47df-a73d-c96606941e70.png">

**Comment by infinite-persistence** [comment]
- [ ] Need padding on the comment filters in various layouts

<img width="708" alt="image" src="https://user-images.githubusercontent.com/64950861/195227178-fa946873-e565-450f-b712-5d998ae3400b.png">

<img width="317" alt="image" src="https://user-images.githubusercontent.com/64950861/195227240-992f5572-bd5f-4cda-bdfa-08c4871a02f9.png">

p/s: Is the filter in mobile slightly too high (w.r.t. it's font size)?

**Comment by infinite-persistence** [comment]
Livestream incognito ... need padding

<img width="527" alt="image" src="https://user-images.githubusercontent.com/64950861/195338982-27f36974-7248-42d4-b1f4-cf8e58cf3751.png">

**Comment by infinite-persistence** [comment]
Google mobile report

https://odysee.com/$/search?q=VINCENT%20REYNOUARD

<img width="483" alt="image" src="https://user-images.githubusercontent.com/64950861/195476197-029713c2-4624-41d0-a371-02abf8a48311.png">

**Comment by toshokanneko** [comment]
- [ ] Truncate channel name in selector
![image](https://user-images.githubusercontent.com/94839278/195863480-365ab69a-f178-460f-b2a1-fa625b3ca40b.png)

**Comment by Abwasserrohr** [comment]
- [ ] On `Auto`, the p of the 1024p is moved the the next line on [this](https://odysee.com/@lincoln-project-djsbsw:d/JETZT-REICHT-ES-MIR:b) claim
![grafik](https://user-images.githubusercontent.com/44294954/196435756-ec885118-227d-49d0-b98b-884ce12aaef0.png)

**Comment by infinite-persistence** [comment]
https://odysee.com/$/top?name=blah

<img width="486" alt="image" src="https://user-images.githubusercontent.com/64950861/196951475-58c063fa-2c51-488c-bf61-a74944083374.png">

**Comment by infinite-persistence** [comment]
Unbalanced border radius between left and right  side?

Close if intentional -- probably to account for the rounded pin.

<img width="195" alt="image" src="https://user-images.githubusercontent.com/64950861/196953225-33686f4a-2389-4de3-8966-8d43624f7272.png">

**Comment by infinite-persistence** [comment]
Ad placeholder exposed when localized text wraps

<img width="376" alt="image" src="https://user-images.githubusercontent.com/64950861/196954333-eeda7004-7d9d-4276-8d4b-27433e3be596.png">

**Comment by tzarebczan** [comment]
![Screenshot_20221020-234507](https://user-images.githubusercontent.com/8120721/197106934-18af2146-c75b-4892-adfb-3e0e716e2b76.png)
Weird LBC icon placement on mobile / my res.

**Comment by infinite-persistence** [comment]
<img width="295" alt="image" src="https://user-images.githubusercontent.com/64950861/197151960-2d619e68-5f80-42b6-8e44-dad49a35365f.png">

**Comment by Abwasserrohr** [comment]
[ ] Last line of longer text gets cut on the [membership cards](https://odysee.com/@NightNationReview:5?view=membership), tested on both Firefox and Chrome.
![grafik](https://user-images.githubusercontent.com/44294954/197183373-91cffeb9-9f21-4de5-9c69-18152cc013b7.png)

**Comment by infinite-persistence** [comment]
Tier selection margins in mobile

<img width="242" alt="image" src="https://user-images.githubusercontent.com/64950861/197752390-8e0e49e9-5262-4795-9969-a062ac25237a.png">

**Comment by tzarebczan** [comment]
![image](https://user-images.githubusercontent.com/8120721/197871550-f4cb770c-62e6-4322-85ab-58a08045d4eb.png)
join button alignment

**Comment by tzarebczan** [comment]
in full screen mode, chat disabled 
![image](https://user-images.githubusercontent.com/8120721/198390363-f5990d72-f5ec-4ae5-86ae-48ef267e108c.png)

**Comment by Abwasserrohr** [comment]
- [ ] The three dots on syncs (claim page card) are a little bit too left, padding is missing?
Happens on both Chrome and Firefox
![grafik](https://user-images.githubusercontent.com/44294954/201714882-b739f225-bf4c-41c4-a543-27b637171b9a.png)
![firefox_5UP55FwCZ8](https://user-images.githubusercontent.com/44294954/201715083-5a7ff717-63a0-40ee-b704-68ed1b8468e2.gif)

**Comment by Abwasserrohr** [comment]
- [ ] The stickers and emojis are shifted in the community tab on both Firefox and Chrome
![image](https://user-images.githubusercontent.com/44294954/204791263-45654081-e517-4965-87f0-86d3403983c1.png)

**Comment by Abwasserrohr** [comment]
- [ ] There is a space missing in the "another livestream is running" notification
![image](https://user-images.githubusercontent.com/44294954/204852708-7e4dae5d-7787-4c7a-be8b-62a8ccd29e5b.png)

**Comment by Abwasserrohr** [comment]
- [ ] Tags are hard to read while creating a new channel:
![grafik](https://user-images.githubusercontent.com/44294954/206029555-363f3a6e-9678-4509-a9fc-a173c71e143c.png)
