### ISSUE TITLE
Transaction link for fiat tip is incomplete

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#2229]
Received a fiat hyperchat from a Post's comment section, but the transaction lists used an incorrect address and routed me to someone else's channel.

![image](https://user-images.githubusercontent.com/64950861/194251234-d9834e78-d5d4-433b-bb12-4eb3e8a24c07.png)

**Comment by tzarebczan** [comment]
hmm that used to be broken in a differnet way. yea, that data for claim name isn't in the backend. it should just link to $/search/<target_claim_id>
