### ISSUE TITLE
memberships fall out

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#2239]
- [x] when clicking a new member notification, make sure to refresh supporters list (even if you are on the page / in another creator area).
- [x] show indication to everyone that a chat is in members only mode (i.e. if you're a member or creator, you can't tell). 
- [x] premium badges don't load here 
![image](https://user-images.githubusercontent.com/8120721/194672851-695fbe31-6ada-4c81-9a24-3aed17121e95.png)

- [x] premium badge not showing on top result or search... 
![image](https://user-images.githubusercontent.com/8120721/194881634-86ed7fea-566d-4626-aba3-0794d74860dc.png)
- [x] from notifications, clicking a URL which goes to a channel page ends up with "undefined" [https://odysee.com/@AussieFighter:828f9bdb59ce634f5f381301b531baa1e30ac077?lc=3bf7[…]a182187b82412aee986a9891e49fecf4c354fa4f2d95cda5&view=undefined](https://odysee.com/@AussieFighter:828f9bdb59ce634f5f381301b531baa1e30ac077?lc=3bf75409c481fcb8a182187b82412aee986a9891e49fecf4c354fa4f2d95cda5&view=undefined)
- [x] on memberships page, when you have an active memberships, show the $ tier and total amount somewhere. Also, would there be an easy to way show "all tiers" here? 
![image](https://user-images.githubusercontent.com/8120721/194908790-6fe2d740-8441-45c0-aaf0-8fa60f192dca.png)
- [x] mention USD bank support on premium only message
- [x] upload description box not expanding, no scroll bar: 
![image](https://user-images.githubusercontent.com/8120721/194674755-c8fb8d62-37b5-45a5-8dc3-94014af5a85f.png)

**Comment by keikari** [comment]
* [ ] https://odysee.com/membershipbeta:cc70596a8fa6ae21add0c9fff3048887bb5ae85d?lc=105126bbb0e3b5c754aa946dc2ecd2f2c2d9763a9d66ca71bdeeda7e359bd2cc
![membership-bug](https://user-images.githubusercontent.com/34790748/194935739-8ebff79f-2a07-413e-80ac-8dc8a5309d28.png)
