### ISSUE TITLE
can't reply via 3 button > reply if channel is pending confirmation? 

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#2240]
![image](https://user-images.githubusercontent.com/8120721/194612294-f7307c04-0d5e-4e5a-bbf5-428b692f24ff.png)
doesn't do anything

**Comment by tzarebczan** [comment]
(nevermind, it only seems to be SOME users?) maybe when channel is pending confirmation?

**Comment by toshokanneko** [comment]
Fixed. eab9385d6bb94476c2cc07fafcb65d721ede7b8b
