### ISSUE TITLE
Add members-only restriction to upload confirmation page

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#2257]
For later:
- [ ] add restriction selection to confirmation page 
![image](https://user-images.githubusercontent.com/8120721/194098024-83aa78ff-3b62-4ad1-a9e4-0ad127a4d273.png)

_Originally posted by @tzarebczan in https://github.com/OdyseeTeam/odysee-frontend/issues/2159#issuecomment-1268589175_

**Comment by infinite-persistence** [comment]
I think I'll take this one to avoid merge conflicts with paid-content :D

**Comment by infinite-persistence** [comment]
Implemented in Paid Content PR.  

<img width="308" alt="image" src="https://user-images.githubusercontent.com/64950861/196613618-6d407b7b-b815-4a9a-a6e8-abb8ea5cad79.png">
