### ISSUE TITLE
Change what is displayed at the end of a video with autoplay next off 

### ISSUE THREAD

**Issue by mayeaux** [OdyseeTeam/odysee-frontend#2271]
Comparing against this video: https://odysee.com/@Odysee:8/bankaccount:6

Currently we just freeze at the last frame when a video ends
![Screen Shot 2022-10-13 at 1 40 46 PM](https://user-images.githubusercontent.com/7200471/195589596-9eb9c351-aeda-45b6-9abe-ceb29659766e.jpg)

Better implementation would be to show the original thumbnail with a play overlay per YT 
![Screen Shot 2022-10-13 at 1 42 06 PM](https://user-images.githubusercontent.com/7200471/195589693-98cc222e-b8eb-4bbe-b586-b516e0f01546.jpg)

Or to show an overlay with 6 next recommended videos
![Screen Shot 2022-10-13 at 1 48 29 PM](https://user-images.githubusercontent.com/7200471/195589743-33458229-4315-4ad2-b77c-a23127488440.jpg)

**Comment by toshokanneko** [comment]
#2523
