### ISSUE TITLE
Tier selection for livestream replay incorrect?

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#2293]
Current tier-selection logic in publish forms:
- **Livestream Form:**  list tiers with `Exclusive livestreams` perk
- **Upload & Post Form:**  list tiers with `Members-only chat` perk

But "Livestream Form" covers `livestream` and `replay`.  
Since `replay` is just a video, shouldn't the selection be `Members-only chat` instead?  Can see it argued both ways, though.

**Comment by tzarebczan** [comment]
Did you mean members only content, and not chat? 

Replay would show the same as upload form with video - members only content.

**Comment by infinite-persistence** [comment]
I mean this selection:

<img width="549" alt="image" src="https://user-images.githubusercontent.com/64950861/196691954-5fc2edb1-f45d-4ab1-8e3e-f21219e078ab.png">

The choices for Replay is currently filtered the same way as Livestream, instead of being the same as Uploads.

**Comment by tzarebczan** [comment]
Roger that, thx for spotting and you're right, should be like uploads!
