### ISSUE TITLE
Is there a plan to paywall 4K content?

### ISSUE THREAD

**Issue by IronMaltese** [OdyseeTeam/odysee-frontend#2300]
With YouTube's recent change to restrict 4K content to premium, I was wondering if odysee would do the same since having 4K as a listed option for odysee premium would incentivize more users to pay for it and it would reduce cost of running the website, I'm curious to see the answer, thanks!

**Comment by tzarebczan** [comment]
That's something we may consider doing down the road with our premium plan, but don't have immediate plans to do so.
