### ISSUE TITLE
View-rewards eligibility evaluated for every single video, not whole channel

### ISSUE THREAD

**Issue by FinixFighter** [OdyseeTeam/odysee-frontend#2320]
**Is your feature request related to a problem? Please describe.**
Actually, your channel can be either monetized (eligible for view-rewards) or not. It is rather unusual, since a user expect that if some of his videos are not eligible this would not affect the entire channel.

**Describe the solution you'd like**
View-rewards should be enabled on a video basis, not on a channel basis. Is a video eligible for view-rewards? Great, it will produce rewards. Is a video not ok? Still good, but won't produce rewards, nor this will affect the entire channel.

**Describe alternatives you've considered**
A mark could be used next to every video, signalling if issues are present. For instance: red = issues are present; green = all ok, this video generates view rewards.

**Additional context**
Users with lots of videos can't know which videos are not eligible, since there's no indication about it at the moment. Even if they wanted to "clean up" their channel, that's not always so immediate and straightforward to understand which videos modify/delete.

**Comment by tzarebczan** [comment]
We don't plan to track this on a per upload basis, sorry.
