### ISSUE TITLE
Google drive upload option

### ISSUE THREAD

**Issue by securegh** [OdyseeTeam/odysee-frontend#2324]
**Is your feature request related to a problem? Please describe.**

My upload speed sucks, it takes forever to upload videos.

**Describe the solution you'd like**

It would be awesome, If I can upload videos to odysee from my Google Drive.

Thank you for your consideration.

**Comment by tzarebczan** [comment]
We're aware and working on it, sorry!

**Comment by tzarebczan** [comment]
And we don't plan to support a Google drive option

**Comment by securegh** [comment]
It coud be any cloud storage provider, the main benefit is that the video upload can take as long as takes, I can close my browser or restart my computer.
