### ISSUE TITLE
Web: Search not returning results

### ISSUE THREAD

**Issue by robster7674** [OdyseeTeam/odysee-frontend#2330]
**Bug**
Pretty much any Search leads to an empty results list. This changed roughly a week ago.

**To Reproduce**
- Just Search on the website. This typically gave me previews of a few hits, and a longer list of results when clicking View All Results.

**Expected behavior**
A list of search results.

**Screenshots**
![image](https://user-images.githubusercontent.com/70331923/198644800-2a352e1c-b205-4ae3-ad6a-9325b4082e3b.png)

![image](https://user-images.githubusercontent.com/70331923/198645205-1be9b0db-7170-404b-9b5f-a38797dfe40a.png)

**Comment by tzarebczan** [comment]
Don't see any widespread issues here..anything change on your end? Maybe some extension blocking it? 

What do you see when you go to: https://lighthouse.odysee.tv/search?s=%22monero%22&size=20&from=0&claimType=channel&sort_by=release_time&nsfw=false

**Comment by robster7674** [comment]
Then I do see to get some results:
![image](https://user-images.githubusercontent.com/70331923/198819171-02c8bab0-dd36-4665-9799-0d6cae6bbeaf.png)

**Comment by tzarebczan** [comment]
Not sure. Maybe post some of the browser console logs when the issue happens. And it's all the time, right? Related content missing too?

**Comment by robster7674** [comment]
Ok, I tested in a different browser and then it works fine. I will figure out what is going, thanks for the support so far!
