### ISSUE TITLE
Playlists fallout: Deleted item in list make publish/edit load infinitely

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/odysee-frontend#2351]
1. Add item to list  
2. Delete the added item from Odysee  
3. Go to the list and try to edit/publish
4. See thing in screenshot  
![edit](https://user-images.githubusercontent.com/34790748/199847450-88f8c52e-48e2-4cd0-94c5-3d56a2bf10ad.png)
-----------------------  

5. When you click "cancel" , this happens on list's page:  
![edit-back](https://user-images.githubusercontent.com/34790748/199847656-7be36e9a-e4ba-47eb-ae66-4bebb382a7c3.png)

**Comment by tzarebczan** [comment]
@keikari can you see if this still happens?

**Comment by keikari** [comment]
Doesn't happen anymore
