### ISSUE TITLE
Posts don't load properly if channel part of the URL is missing

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/odysee-frontend#2358]
Three links to a same post.

These don't load post here:  
https://odysee.com/channelpages:e  
https://odysee.com/channelpages:e4945ba648c27dc5fc047f7fcd48162e6322258f  

This loads it:  
https://odysee.com/@Odysee:8/channelpages:e

**Comment by Abwasserrohr** [comment]
The links that don't load are also used in the notifications, Odysee announcement posts are affected too if people have notifications enabled for it.
