### ISSUE TITLE
Website Optimization

### ISSUE THREAD

**Issue by iamflorencejay** [OdyseeTeam/odysee-frontend#2363]
When I check the GTMetrix website for the optimization, it has a F rating, because of a lot of reasons (check attachment):
[GTmetrix-report-odysee.com-20221105T192836-esiPPGK1.pdf](https://github.com/OdyseeTeam/odysee-frontend/files/9943672/GTmetrix-report-odysee.com-20221105T192836-esiPPGK1.pdf)
[GTmetrix-report-odysee.com-20221105T193444-ErbDjqvy.pdf](https://github.com/OdyseeTeam/odysee-frontend/files/9943676/GTmetrix-report-odysee.com-20221105T193444-ErbDjqvy.pdf)

Also, pagespeed insights shares the same thing:
https://pagespeed.web.dev/report?url=https%3A%2F%2Fodysee.com

So... What is your plans on dealing with this kind of DOM overload stuff on react?

**Comment by tzarebczan** [comment]
Most of these are filed in other issues already, thank you.
