### ISSUE TITLE
Playlists fallout: Invalid value for claim_id in older published list will wipe old items on update

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/odysee-frontend#2366]
1. Create list with following data as claims
```
"claims": [
            "9759d0f4e91bd27589989206a4f1a9d5c818d163",
            "5c71904d85adade2c3dec85ef5af383839bac1ee",
            "16a4879c5522dfcdcda0c242b7255e327b8717b4",
            "f2f9dd00e504f568eb552cca5fe1b73835340227",
            "36b95db0312f2e309ae4fdc66e57a325ff75a6cd",
            "e4"
          ],
```
2. Public version of the list loads claims infinitely, and if adding more items and publishing updates, old items get wiped.

**Comment by tzarebczan** [comment]
@saltrafael I think this is the worst one and reproducible. Probably happens with deleted ones too.

**Comment by tzarebczan** [comment]
@keikari have you heard of these issues recently? Maybe we can close this one.

**Comment by keikari** [comment]
Don't recall any more reports of this during this year.  

Gave it a try, and invalid claim_id doesn't seem to cause any issues. 
And editing the list, will clear the invalid item.

Same if the claim in public list is deleted, but seems that the deleted item would anyway get cleared when publishing edited list.
