### ISSUE TITLE
Refactor ClaimList / ClaimListDiscover and ClaimPreview / ClaimPreviewTile

### ISSUE THREAD

**Issue by mayeaux** [OdyseeTeam/odysee-frontend#2381]
These components have become incredibly messy with a lot of repeated code and without much logical organization. Refactoring this will clear up a lot of technical debt and make these particularly messy components much more maintainable and accessible.

**Comment by tzarebczan** [comment]
It's been filed under https://github.com/OdyseeTeam/odysee-frontend/issues/1163
