### ISSUE TITLE
support language specific /$/content/get call

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#2388]
The data is getting larger, and we only really need a single language at a time.

**Comment by infinite-persistence** [comment]
Doing `?lang=xx`, similar to `?format=roku`, seems to work.

But data like `meme`, `features` and `portal` falls back to English if they don't exist.  Ideas to avoid double call at boot to get `en` data for non-English users:

1. Perform the English fallback directly at the server side.
    - con:  But apps that really don't like English won't be able to differentiate whether it was fallen-back data or not.
2. Make `?lang=xx` always return `en + xx` -- apps can then decide what to do with empty data.
    - con:  Slightly larger size, but still smaller than current version.

I'm thinking "2".  Thoughts, @tzarebczan?
