### ISSUE TITLE
Playlists fallout: Total staked amount shows 0, if entering a list from playlists tab

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/odysee-frontend#2405]
1. Go to https://odysee.com/$/playlists
2. View some public list
3. Total staked amount shows 0 and "supports and tips"  is blank
4. With direct link and after a refresh it shows expected numbers

![list-staked-amount](https://user-images.githubusercontent.com/34790748/202770459-b7a9370d-1b41-4c2b-9e68-1cc7c07cc1f9.png)

**Comment by tzarebczan** [comment]
This still shows 0? https://odysee.com/$/playlist/570bfd64988509829fda1f659558674c6d686fcd
