### ISSUE TITLE
Playlists: Keep track which tab was active in playlists page(all/private/public/...)?

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/odysee-frontend#2410]
**Is your feature request related to a problem? Please describe.**
Currently opening some list on playlists page when in some other tab than "All" tab and then going back, will get you to the main playlists page where scroll height + page number are same where you left off, but tab is always "All". 

**Describe the solution you'd like**
Keep also track of the active tab. 

**Describe alternatives you've considered**
Don't keep track of scroll height and page number. (Always returning to page 1 + scroll height at top is maybe better than current behavior)

**Additional context**
In video clicking back gets to seemingly random place in https://odysee.com/$/playlists 

[list-back.webm](https://user-images.githubusercontent.com/34790748/203150538-9414136e-5ab7-4794-b66e-1de995d34417.webm)

**Comment by hdragos** [comment]
Hello! Is this feature being implemented? If not, I would like to implement it myself.

**Comment by tzarebczan** [comment]
@hdragos hey, thanks for chiming in! You're free to take a shot, it's not currently being worked on.

**Comment by hdragos** [comment]
I think I found the issue:

Upon going back to the playlists page (aka loading the playlists page), the default collection list that is displayed will be All, as seen [here](https://github.com/OdyseeTeam/odysee-frontend/blob/master/ui/page/playlists/internal/collectionsListMine/view.jsx#L57). Apart from that, the page number gets supplied from the URL query params, as seen [here](https://github.com/OdyseeTeam/odysee-frontend/blob/master/ui/page/playlists/internal/collectionsListMine/view.jsx#L94).

So the playlist and position displayed are not random. Whenever you go back to your playlists page, the `All` playlist collection will always be displayed, on the page provided in the URL (if available, if not, it will default to the 1st page).

How should I implement the solution? From what I can see, we have 2 options: persist the last active tab data in the sessionStorage or in the query params.

**Comment by keikari** [comment]
@hdragos  Wasn't sure if you were still planning to implement this, so gave this a try.

**Comment by hdragos** [comment]
Apologies, I began to work on this before the winter vacation and I totally forgot about it. I tried to make a general hook that could sync the state between react state and an URL param (very similar to how [`use-persisted-state.jsx`](https://github.com/OdyseeTeam/odysee-frontend/blob/master/ui/effects/use-persisted-state.js) works), but for some reason, I could not get it to work.
