### ISSUE TITLE
Create new wallet tab for purchases/rentals

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#2415]
We recently renamed the fiat one > Tips, but it has all the stripe transactions. 

We can pass the type as tips/rental/purchase, gotta see if we can pass multiple here on the backend to suppor this.

At the same time, these would be nice, both on sender/receiver: https://github.com/OdyseeTeam/odysee-frontend/issues/2390 / 
https://github.com/OdyseeTeam/odysee-frontend/issues/1744

**Comment by mayeaux** [comment]
Closed by #2437
