### ISSUE TITLE
Sidebar can only be shrinked by using sidebar toggle when on home/channel pages

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/odysee-frontend#2417]
From user:
 "For the past couple weeks or so, when I'm on the following or home page and expand the sidebar I have to click the button again to narrow it. I used to be able to click anywhere on the page to narrow the sidebar. It will narrow by clicking elsewhere when I'm on a video or post page. This happens on multiple OSes and browsers. Just a minor annoyance, but if you can make it so that it narrows by clicking other places, besides the button, that would be much appreciated. "

**Comment by toshokanneko** [comment]
Fixed. 5eb88960785f148dc6da010ce4ad8ed224334cb7
