### ISSUE TITLE
banners/portals fall out

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#2424]
- [x] make sure to pass all banners/images through thumbnails cdn
- [ ] enable view counts on portal pages for internal-feature + global mod users
- [x] fix recommended section logic - it made sense to leave it in the customize list since both features were premium, but now, customize is for everyone. So it needs to be conditionally shown based on odysee premium.  If anyone clicked X or customized, they will now have a blank recommended section since it was in the list. If we can auto hide that if you don't have premium, that would be great too.

**Comment by toshokanneko** [comment]
- [ ] Use English homepage as fallback for banners and portals.
