### ISSUE TITLE
Home page fallout: "View More" gives error on playlists

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/odysee-frontend#2429]
Happens only with "Playlists". Seems to work fine with single playlist and other items.
![view-more-playlists](https://user-images.githubusercontent.com/34790748/205350387-2b8bb93e-217d-45b3-87c1-735f65d7ac8c.png)

**Comment by toshokanneko** [comment]
Fixed. 415b3dabe143e467332e0c3fb70f0455340c5cd8
