### ISSUE TITLE
Mobile: Related videos missing 3-dot buttons 

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/odysee-frontend#2431]
Happens also on actual device.

Related (no 3-dots) | More from channel (has 3-dots)
![mobile-related](https://user-images.githubusercontent.com/34790748/205661727-6f7b8aeb-e975-4384-8127-3f3fe2da2b72.png)

**Comment by toshokanneko** [comment]
Fixed in the upcoming `design-patch`. However, the menu was disabled via js by purposely passing the `hideMenu` parameter to the component on mobile and I don't know why. There might be a good reason for that.
