### ISSUE TITLE
Design & UI Issues - December 2022

### ISSUE THREAD

**Issue by toshokanneko** [OdyseeTeam/odysee-frontend#2458]
**Remaining legacy issues from the last Thread**

- [x] https://github.com/OdyseeTeam/odysee-frontend/issues/2226#issuecomment-1276056059
Livestream incognito Spacing

- [x] https://github.com/OdyseeTeam/odysee-frontend/issues/2226#issuecomment-1286645525
Credit Card Alignment

**Separate Threads**

- [ ] https://github.com/OdyseeTeam/odysee-frontend/issues/2378

- [ ] https://github.com/OdyseeTeam/odysee-frontend/issues/2094

**Comment by keikari** [comment]
* [ ] Cash tip button bit higher than others
![cash-tip-offset](https://user-images.githubusercontent.com/34790748/210652753-744b2ab0-0e58-493c-908d-956386d82a99.png)

**Comment by keikari** [comment]
* [ ]  Stuff overlapping on homepage editing
![homepage-edit-overlap](https://user-images.githubusercontent.com/34790748/211221994-0903eda1-6532-4a91-b0c7-583299ca611a.png)

**Comment by infinite-persistence** [comment]
- [ ] Padding for annoymous posts

In "Your Uploads" page;

<img width="311" alt="image" src="https://user-images.githubusercontent.com/64950861/224005554-1cbb3305-46f9-4c5d-ba3d-35df54f69923.png">

**Comment by keikari** [comment]
* [ ] Hide reposts check box 
![hide-reposts-checkbox](https://user-images.githubusercontent.com/34790748/224093057-0770e1f1-c808-44bd-bec1-80e763974425.png)

**Comment by infinite-persistence** [comment]
- Layout shift  http://localhost:9090/@toshokanneko:d

"New videos" section come in slow for me, so things are jumping around.

**Comment by toshokanneko** [comment]
#2591
