### ISSUE TITLE
Downloads aren’t working through browser. 

### ISSUE THREAD

**Issue by DurbansPoison** [OdyseeTeam/odysee-frontend#2468]
# issue 
When clicking the download button on a 3d file it shows this page(on desktop macos, and mobile iOS)
![5095C10C-B28D-43C5-997C-284031EF3A1D](https://user-images.githubusercontent.com/97037988/210705800-e5b5fe3a-2efd-43a8-82f4-23bf976666bd.png)

# current work around:
The solution I’ve found to be true, regardless of what browser is this : 
https://user-images.githubusercontent.com/97037988/210705895-40b64168-d991-4342-96d2-b9a12ec64c9d.MOV

## side note 
Is this on purpose? Certainly seems to be intentional but I thought I’d try to see from you guys yourselves. 
love the platform and the freedom on it, this will definitely mean a platform switch for quite a lot of people if it’s intentional.

**Comment by tzarebczan** [comment]
Check back in a few days
