### ISSUE TITLE
My article is comletely broken.

### ISSUE THREAD

**Issue by JYamihud** [OdyseeTeam/odysee-frontend#2470]
![Instead of the article, it shows that it can't load the article](https://notabug.org/jyamihud/update_manager/raw/master/generalpurposeimages/1.png)

I uploaded the article to LBRY using the SDK ( using FastLBRY ). And then I tried to upload it multiple times over and over. And every-time it tells me that it can't load the damn thing.

Here is the link:

https://odysee.com/@blenderdumbass:f/The_Boss_Battle_of_Freedom:c

 ( I'm aware of the loss to the us government and potential problems that it can do to the LBRY network. But are doomed? Should I look for an alternative? )

**Comment by tzarebczan** [comment]
We're having backend issues, check back later.
