### ISSUE TITLE
Some characters not shown corretly in video title

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/odysee-frontend#2482]
Video's title on page shows as `Batman: Arkham City | Part 1 | He&#039;s Backd`
Should be: `Batman: Arkham City | Part 1 | He's Back` (is like that in the claim data)

https://odysee.com/@evillaughgaming:0/batman-arkham-city-part-1-he%27s-back:d

Seems to appear like expected outside of the content page.

**Comment by tzarebczan** [comment]
Probably the emoji change?

**Comment by tzarebczan** [comment]
another: https://odysee.com/@FrontlineCovid19CriticalCareAlliance:c/MyStory_RaymondHarrison:3?lid=d735338512a54b8a11fe0fc08c9f8edba2c229c5

**Comment by toshokanneko** [comment]
Temporarily fixed. ec4f5cd4e386f1e0eeb8f78412c4548ad6483d61
