### ISSUE TITLE
Error message: Not enough funds to cover this transaction.

### ISSUE THREAD

**Issue by christiancontent** [OdyseeTeam/odysee-frontend#2483]
I can't upload videos to Odysee through the browser at the moment, I get this error:

"Error message: Not enough funds to cover this transaction."

I have the same amount of funds as before and I have been able to upload tens of videos without those funds diminishing much, so maybe this is a bug?

**Comment by tzarebczan** [comment]
Each upload requires additional funds and a deposit. Are you able to earn more in rewards? How much is the available balance?
Email us at hello@odysee.com if you continue to have issues

**Comment by christiancontent** [comment]
Woops sorry this was my bad, I just realized that amount of funds displayed at the top right corner is not actually the amount of available funds but instead the amount of total funds and most of those were locked with content.
