### ISSUE TITLE
Strange behaviour when opening livestream from notification

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/odysee-frontend#2491]
1. Open livestream from notification
2. Page freezes, or opens floating player that can't be closed.   (Depends of the floating player setting)  

Next scheduled streams:
[https://chainquery.lbry.com/api/sql?query=SELECT%20c.name,%20c.claim_id,%20c.publisher[…]20GROUP%20BY%20c.claim_id%20order%20by%20release_time%20asc](https://chainquery.lbry.com/api/sql?query=SELECT%20c.name,%20c.claim_id,%20c.publisher_id%20FROM%20chainquery.claim%20c%20INNER%20JOIN%20claim_tag%20ct%20ON%20ct.claim_id%20=%20c.claim_id%20INNER%20JOIN%20tag%20t%20ON%20ct.tag_id%20=%20t.id%20WHERE%20(t.tag=%22c:scheduled-livestream%22)%20and%20c.release_time%20%3E%20UNIX_TIMESTAMP()%20GROUP%20BY%20c.claim_id%20order%20by%20release_time%20asc)

**Comment by toshokanneko** [comment]
Might already be fixed. I've made a few changes to the player earlier today. Thanks for the list, I'll test it as soon as I get a notification.

**Comment by tzarebczan** [comment]
still happening, at least on desktop

**Comment by toshokanneko** [comment]
Fixed. #2515
