### ISSUE TITLE
Add support for LibreJS

### ISSUE THREAD

**Issue by Darin755** [OdyseeTeam/odysee-frontend#2493]
**Is your feature request related to a problem? Please describe.**
I think it would really good for Odysee to get LibreJS support. LibreJS is a browser extention that only allows Free JavaScript to run. It blocks any JavaScript that is under Propeitary or unknown license.

**Describe the solution you'd like**
I think it would be fairly trivial to add the license information into Odysee. The Odysee frontend is already FOSS and it is just a matter of adding the proper tags for LibreJS to recognize.

**Why bother?**
I know that LibreJS isn't exactly popular but I think it will be a great tool to build trust. By listing all of the JavaScript licensing you can prove that Odysee is for the community. LibreJS will also protect Odysee from turning into a propeitary data monster like youtube

**Comment by tzarebczan** [comment]
We don't plan to do this anytime soon, closing for now. Thanks for the detailed issue and your time..

**Comment by Darin755** [comment]
No problem. I just want to see Odysee grow
