### ISSUE TITLE
Confirm purchase modal title says "Confirm Pre-order" for LBC purchases

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/odysee-frontend#2495]
![pre-order](https://user-images.githubusercontent.com/34790748/213248127-e35be1ae-17d3-4196-85f5-3bf498a0bfa7.png)

**Comment by infinite-persistence** [comment]
- [ ] Unintended automatic purchase https://odysee-workspace.slack.com/archives/C02G20Z2AEL/p1685545728900519
