### ISSUE TITLE
Livestream page blank except for thumbnail and chat

### ISSUE THREAD

**Issue by LiGoldragon** [OdyseeTeam/odysee-frontend#2496]
https://odysee.com/@WhitePhoenix:9/TheKingAndQueenOfOlympus-NewMoonLivestream-SadAlSuud-2Aquarius5916AnnoMundi:f

The page show up fine on the mobile app (which cannot open odysee URLs by the way).

Rant: I just want to add that I'm really annoyed with this, but we're all in the same boat. I republished several times, even deleted the claim and then used a different URL, as it wouldnt let me reuse the one I just deleted. Now I have to edit all my advertising, and re-inform all my people of the new link. Rumble is another black box "trust us we won't censor (they already do)", and odysee *sucks*. But at least it exists. So now I really want to make a platform to make them all obsolete. Help me implement the Kriom prototype! https://kriom.me

**Comment by tzarebczan** [comment]
Sorry about about that, we'll get it looked into!

**Comment by tzarebczan** [comment]
This is fixed now, thanks for the report!
