### ISSUE TITLE
Content gets purchased automatically

### ISSUE THREAD

**Issue by Myzel394** [OdyseeTeam/odysee-frontend#2502]
**Bug**
When I went to a video that needs to be purchased, it has automatically been purchased. First, the video only showed "Purchase ... for ...", but after a few seconds it was purchased automatically without me clicking anything.

**To Reproduce**
1. Go to a video that needs to be purchased
2. (not sure if this is required) Scroll down a bit
3. Content gets purchased automatically

**Expected behavior**
No automatic purchase or at least a confirmation dialog

**Screenshots**

**System Configuration**
I was using the website on Firefox. I have a lot of extension installed, but I wouldn't expect from any of them to automatically press buttons (except IDontCareAboutCookies, but that shouldn't be the case here)

**Additional context**
This bug only happened once (just a few minutes ago) and I didn't want to try this bug again, as I don't want to loose all my money :D

**Comment by tzarebczan** [comment]
USD or LBC video? Can you share a link?

**Comment by Myzel394** [comment]
Hey, that was fast :O

It's this video: https://odysee.com/@Florian.Dalwigk:f/die-jagd-beginnt!-osint-challenge-auf:1

**Comment by tzarebczan** [comment]
Yep, happened here too. Ty for the report! 

Email your LBC address to hello@odysee.com and reference this thread for a refund.

**Comment by Myzel394** [comment]
Okay thanks for your help. I'm a bit confused though, how can you refund transactions from the blockchain?

**Comment by toshokanneko** [comment]
Fixed @ 180e7936a4cd8e92e0818519fef2df0f35582108

**Comment by tzarebczan** [comment]
> Okay thanks for your help. I'm a bit confused though, how can you refund transactions from the blockchain?

We'd just send you some credits 🤙

**Comment by Myzel394** [comment]
@tzarebczan Ahh I see, thanks. I sent an email. Btw, that was a quick fix @toshokanneko :D
