### ISSUE TITLE
Play all functionality

### ISSUE THREAD

**Issue by robbah** [OdyseeTeam/odysee-frontend#2504]
Hello,

I am requesting a feature to fix a 'issue' what i am running into.

It would be nice to have a button which is placing all content of the channel into a 'view all' playlist which is on-demand and thus not in my account playlist. This way, i can watch all the channel's content in chronological order which is not possible right now.

Regards,

**Comment by tzarebczan** [comment]
Thanks for the suggestion, we've got it filed under: https://github.com/OdyseeTeam/odysee-frontend/issues/1761

**Comment by robbah** [comment]
Lol, i didn't see that one. Thank you for mentioning!
