### ISSUE TITLE
New Ads on website are very intrusive

### ISSUE THREAD

**Issue by IronMaltese** [OdyseeTeam/odysee-frontend#2508]
**Is your feature request related to a problem? Please describe.**

The Ads that follow the user’s scrolling across the website remind me of the illegal websites used to watch copyrighted movies and make me not want to recommend odysee anymore

**Describe the solution you'd like**

Make ads less intrusive and not follow you when scrolling on the page

**Describe alternatives you've considered**

**Additional context**

I love odysee, I just don’t want to have to use an adblocker everytime I want to watch a video

**Comment by tzarebczan** [comment]
Send us an email at hello@odysee.com with which ad you are referring to exactly.

Odysee needs to make money to operate, so ads are a must
