### ISSUE TITLE
I can't remove my channel from my odysee account

### ISSUE THREAD

**Issue by smashfilm** [OdyseeTeam/odysee-frontend#2516]
**Bug**
I can't delete my channel from odysee.

**To Reproduce**
1. Go to 'Channel page'
2. Click on 'Edit'
3. Scroll down to 'Other'
4. Click on 'Channel delete'
5. Confirm it
6. Error pops out

**Expected behavior**
I expected to be deleted from my odysee account.

**Screenshots**
![smashfilm - Google Chrome 28 01 2023 17_32_57](https://user-images.githubusercontent.com/123830236/215282208-f8af8ae8-d151-40af-b47b-c054dfa8d36e.png)

**Additional context**
It says at the end (From 6.): 'Error removing your claim or endorsement'.

I also contact odysee per email since now, and I showed them the issue, and still didn't get the reply, I'm not sure, if they got my email message, I checked their email adress to make sure I didn't sent to someone else.

**Comment by tzarebczan** [comment]
We'll take care of this via the help desk, please wait for a reply there.

**Comment by smashfilm** [comment]
I will, thank you for the support.
