### ISSUE TITLE
Make URL editable even for video Youtube imported videos

### ISSUE THREAD

**Issue by FinixFighter** [OdyseeTeam/odysee-frontend#2545]
**Is your feature request related to a problem? Please describe.**
When a user has his Odysee channel connected with YouTube, he cannot edit the URL of the newly uploaded videos. This means that user can't compete with other users on Odysee in order to make his content more discoverable (by staking LBRY).

**Describe the solution you'd like**
All videos should have editable URL.

**Describe alternatives you've considered**
If needed, a small LBRY fee could be requested for changing the URL.

**Additional context**
A browser add-on called "Watch-on-Odysee" exist. What's the point of this tool if users prefer a double upload (on YouTube AND on Odysee) instead of having their channel linked?

**Comment by tzarebczan** [comment]
Once a URL is created, it can't be changed. It would need to be deleted and duplicated. We don't plan to support this anytime soon.
