### ISSUE TITLE
How to deploy odysee in the private network?

### ISSUE THREAD

**Issue by r6fans** [OdyseeTeam/odysee-frontend#2561]
I want to build the whole odysee emvironment(include odysee-frontend and backend service).

I deploy odysee-api and player-server use docker-compose.
Then I change odysee-frontend .env(`LBRY_API_URL` and `PLAYER_SERVER` address) file and deploy it from source(follow the [README.md](https://github.com/OdyseeTeam/odysee-frontend#readme)).

I noticed that there are many backend address in the `.env` file. Which is required? Or I need change them all?

**Comment by tzarebczan** [comment]
If you want to run both the backend and frontend, yes, all those paths would need to be adjusted. I'm not sure how much of the backend is designed to work outside of our environment but feel free to poke around and try.

**Comment by r6fans** [comment]
@tzarebczan 

Could you tell me Which project is called by the Odysee-frontend Signup button ? I use the Odysee-API but it return 404 not found.

And then I use `/signup` as keyword to filter the project under the `OdyseeTeam`, but found nothing.
