### ISSUE TITLE
"You will need Toes to Count soon", is that a threat? LOL

### ISSUE THREAD

**Issue by juanpc2018** [OdyseeTeam/odysee-frontend#2569]
i write a comment, 
the channel owner does Not like the comment,
bans me,
then i get a message:
"You will need Toes to Count soon" LOL

i cannot stop laughing.
https://youtu.be/y9pQfRlg9Xk

**Comment by tzarebczan** [comment]
If the abuse continues, please feel free to email us at help@odysee.com

**Comment by juanpc2018** [comment]
The message appears when a user subscribes your channel, 
and you have a small number of followers / or the account is new.
Is Not The other User, is the System.
<img width="572" alt="Screen Shot 2023-03-02 at 10 12 15 AM" src="https://user-images.githubusercontent.com/33388902/222468921-70b90992-504c-4778-93da-ee426d1b1213.png">
