### ISSUE TITLE
Excessive CPU usage on playback in Safari (Mac)

### ISSUE THREAD

**Issue by tomeksowi** [OdyseeTeam/odysee-frontend#2579]
**Bug**
When playing video through Safari on a Mac, Odysee burns 2.3 out of my 8 cores making the laptop uncomfortably hot. Also, after a while the audio and video goes out of sync, the video stutters until page is reloaded.

**To Reproduce**
Play any video in Safari on a Mac. Resolution doesn't matter, Odysee burns CPU even with 144p.

**Expected behavior**
Reasonable CPU usage, Odysee on Firefox as well as YouTube on Safari takes about 50% of one core to play the same video on the same system.

**Screenshots**
All activity monitor screenshots while playing the same video in the same resolution (144p).
Safari:
![image](https://user-images.githubusercontent.com/583410/223523759-1ca2c09e-6bb4-4619-b4d2-1ba94b055ebd.png)
Safari (YouTube):
![image](https://user-images.githubusercontent.com/583410/223519243-f53ec234-e517-4012-a7af-32c8f92d9d05.png)
Firefox:
![image](https://user-images.githubusercontent.com/583410/223514377-c2050bf5-fda3-4ed2-80af-aa78bb521c2f.png)

**System Configuration**
* MacBook Air M2, 2022
* macOS Ventura 13.2.1
* Safari 16.3 (18614.4.6.1.6)
* Firefox 110.0.1
* odysee.com accessed on March 7, 2023

Also witnessed on:
 * MacBook Pro x86, 2019

**Comment by iamflorencejay** [comment]
Probably the video doesn't have transcoding enabled yet

**Comment by infinite-persistence** [comment]
- `https://github.com/videojs/video.js/issues/7520`
    - It should be the `WindowServer` issue with Safari 16 -- the CPU usage is less crazy in prior versions.
        - Firefox did something to not clog up `WindowServer` a while back.
- The seek-bar is the major contributor for the events, as not installing it prevents the CPU problem entirely (almost <5%). 
    - Asking videojs if there is a workaround to reduce the updates ...

**Comment by tzarebczan** [comment]
Thanks for the report @tomeksowi . Do you know if there's a different if you play non-transcoded content vs ones where quality options are available, like : https://odysee.com/@CryptoLawTV:9/sec-v.-crypto-this-will-be-a-long-fight:7  ?

**Comment by tomeksowi** [comment]
Interesting lead, @tzarebczan, there is indeed a difference. Your video and all I tried have resolution options and burn CPU. However, on non-transcoded videos without quality options like [this](https://odysee.com/@DeepMS:3/noes-like-a-boss-(magic-release)-2:9) or [this one](https://odysee.com/@DeepMS:3/blackpink-shut-down-(-trap-mix):e) the CPU usage is reasonable.

**Comment by tzarebczan** [comment]
Wow, i thought it would be the opposite, that's really strange, but definitely a good lead. We'll keep poking.

**Comment by tzarebczan** [comment]
@tomeksowi this should be fixed now, can you confirm?

**Comment by infinite-persistence** [comment]
hm ... if not mistaken, this should still be open.
My earlier suggestion about changing `overrideNative` turns out wasn't the root-cause, so I didn't change it.
Poked Gary about it -- haven't responded yet.

Or did Safari 16.4 fixed it?
