### ISSUE TITLE
Automatically toggle video suggestions to videos from creator if no videos are matching

### ISSUE THREAD

**Issue by Abwasserrohr** [OdyseeTeam/odysee-frontend#258]
**Is your feature request related to a problem? Please describe.**
Sometimes, no video suggestions are found, instead of showing that there are no suggestions, it could switch to the videos of the creator by default.

![34k2hnlkjösa](https://user-images.githubusercontent.com/44294954/140994677-e2ca6a2e-6dbe-4167-93ef-e36874e7a0e7.png)

**Comment by tzarebczan** [comment]
We're revamping this area soon and that should happen. It doesn't work on refresh either right?

**Comment by Abwasserrohr** [comment]
Refreshing didn't help, I tried that, but now it works for some reason. 😅

**Comment by tzarebczan** [comment]
Let me know if it happens again... we're aware of some issues with 1 of the servers, so you probably hit the bad one.
