### ISSUE TITLE
Livestream player: please remove blocking console

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#259]
Every time a livestream video loads, the console is blocked by `player-settings`. All other debug logs will not appear unless you clear the console first, which causes one to miss important errors.  Getting tired of having to manually clear it.

![image](https://user-images.githubusercontent.com/64950861/141028158-0142c1ad-20b4-41bf-a8d4-f9cd74eb92fc.png)

**Comment by tzarebczan** [comment]
Let's get rid of that player once and for all! Hopefully Anthony's progress will make that easier.
