### ISSUE TITLE
Design & UI Issues - March 2023

### ISSUE THREAD

**Issue by toshokanneko** [OdyseeTeam/odysee-frontend#2592]
**Remaining legacy issues from the last Thread**

- [ ] https://github.com/OdyseeTeam/odysee-frontend/issues/2458#issuecomment-1463387280

**Separate Threads**

- [ ] https://github.com/OdyseeTeam/odysee-frontend/issues/2378

- [ ] https://github.com/OdyseeTeam/odysee-frontend/issues/2094

**Comment by keikari** [comment]
* [ ] Notifications don't fit inside the page when using French as a language
![notifications-cut-out](https://user-images.githubusercontent.com/34790748/227942503-9fb743a7-a82e-46a6-87e4-a3c5b309b1e7.png)

**Comment by infinite-persistence** [comment]
- [ ] Column header for the "amount" should be right-justified too? Don't recall it ever looked like this, but I could be wrong.

<img width="497" alt="image" src="https://user-images.githubusercontent.com/64950861/228091673-fd1b3072-0bc9-463f-aaad-d51877c9cb95.png">

**Comment by infinite-persistence** [comment]
- [ ] Jumpy footer.

When loading claim pages directly, it's very annoying to see the footer jump up and down.  I assume this would also affect the CLS score.

1. It would be nice if it can be locked at the bottom.
2. Better still, perhaps we use the same strategy as Posts, where we hide the Comments sections for a few seconds before an auto-reveal.  Footers aren't important, so the timing doesn't have to be exact.

**Comment by infinite-persistence** [comment]
- [ ] Overlap title, small layout

<img src="https://user-images.githubusercontent.com/64950861/232657148-8859b38c-d833-4b6d-bd49-935e984eaec9.png" width="300">

**Comment by infinite-persistence** [comment]
The channel avatar  and "live in 2 days" feels misaligned too

**Comment by keikari** [comment]
* [ ] "Confirming..." uploads look bit strange with their different height (?)
![confirming](https://user-images.githubusercontent.com/34790748/233013254-a75e6387-8aed-447e-ab12-d33e35ab03e8.png)

**Comment by keikari** [comment]
* [ ] Scheduled livestreams showing on home page edit (also happens with scheduled uploads) 
![scheduled](https://user-images.githubusercontent.com/34790748/233014127-b0dcf56f-6246-46c1-90b8-0079f68b409c.png)

**Comment by keikari** [comment]
* [ ] Description in playlists looses formatting 

![list-description](https://user-images.githubusercontent.com/34790748/233356031-c4aa6d3e-4c94-4abd-a706-f452bd69af59.png)

Actual description that was set
```
This is description

This is second line of description
This is line
```

**Comment by keikari** [comment]
* [ ] Wrong font in channel name and follow/join buttons on posts
![post-font](https://user-images.githubusercontent.com/34790748/233616739-4852af3e-4bb0-415d-9f64-eb5b2fc243ac.png)

**Comment by infinite-persistence** [comment]
- [ ] Opinion:  the hover-highlight for Radio and Checkboxes doesn't feel right
    - Feels odd to highlight the entire thing as one blob without a different border color. 
        - ![image](https://user-images.githubusercontent.com/64950861/235055342-c6ddeb4b-e77c-48a6-ab38-17dfacd42086.png)
    - When hovering for a selected radio, the white dot in the middle doesn't feel nice, especially in Dark Theme.  
    It is also not centered.
        - ![image](https://user-images.githubusercontent.com/64950861/235055173-e58f1d93-47fe-43bf-9db4-b5bad983bf2a.png)

Suggestion:  perhaps just highlighting the border for hovered Radio and Checkboxes (like what GH is doing) is cleaner?

**Comment by keikari** [comment]
* [ ] Channel selector at the end of the upload page, doesn't make as much sense any more, since options in the form vary between different channels and anonymous. (Different state/options for membership content, and unlisted/scheduled uploads aren't available for anonymous.)  

Related comments in: https://github.com/OdyseeTeam/frontend-qa/issues/63

**Comment by infinite-persistence** [comment]
- [ ] Can/should the subtitle text be gray? Seems like too much emphasis.
- [ ] (legacy) Should these be indented slightly?
- [ ] Bottom margin seems too much (or maybe Title also introduces upper margin)

<img width="397" alt="image" src="https://user-images.githubusercontent.com/64950861/235578729-dab5f376-984e-4110-bcb7-3e23ee6495d0.png">

**Comment by keikari** [comment]
Scheduling livestream overlaps with the thumbnail selector
![livestream-scheduled](https://user-images.githubusercontent.com/34790748/236198398-d907f7bf-accf-4f4f-b820-119272d66a62.png)

**Comment by infinite-persistence** [comment]
If you refresh on a File Page, the logo blinks after something is fetched.

**Comment by keikari** [comment]
Missing some margin on playlist deletion
![list-deletion](https://user-images.githubusercontent.com/34790748/236458325-9498569d-c7cf-4171-98f8-d6bb7364bf7b.png)

**Comment by keikari** [comment]
Playlist arrange mode, video duration on top off the bottom bar
![timestamp](https://user-images.githubusercontent.com/34790748/236491202-43e977aa-4a47-4d09-a0bc-6faa9e016088.png)

**Comment by keikari** [comment]
Opinion: I still think the hover color in drop-down menus is too strong. Been quite a while, but I don't seem to get used to it.   Would maybe only highlighting the border look bad?
![drop-down-menu-color](https://user-images.githubusercontent.com/34790748/236623900-23a4d696-edbd-4073-9af3-4522fde3a5f3.png)

**Comment by infinite-persistence** [comment]
- [ ] Mobile footer block is left-aligned

F5 on a file page.

**Comment by infinite-persistence** [comment]
Follow button blends in with background: Incognito + mobile

Probably fine for this scenario, but feels unintentional, so reporting it.

<img width="254" alt="image" src="https://user-images.githubusercontent.com/64950861/236738709-21ba7cb6-1de7-4825-9777-cdfbd3ffd0f9.png">

**Comment by infinite-persistence** [comment]
Incognito
- [ ] need margin between buttons

[?] too much emphasis (too big) on the odysee tagline?
    - saw this from a news site that is using our embeds.  The taglines doesn't make sense from that context (was viewing a news video), and took me a while to recall that it is our hardcoded string and not related to that video.

<img width="625" alt="image" src="https://user-images.githubusercontent.com/64950861/236992619-201c9f52-ad3d-4878-8e15-1e080bf9f051.png">

**Comment by infinite-persistence** [comment]
Mac Safari 16 "confirming..." location is off

<img width="393" alt="image" src="https://user-images.githubusercontent.com/64950861/237000454-223fb6af-11aa-4a50-b200-ff3a0492bef1.png">

**Comment by Abwasserrohr** [comment]
- The field set on the credit details of the channel edit site has no padding:
![](https://github.com/OdyseeTeam/odysee-frontend/assets/44294954/5e1cd50b-208b-4f06-b404-5335b6cc051d)
