### ISSUE TITLE
Older iPad+Safari not loading optimizer's image.

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#2611]
Ipad + Safari with 2020 OS, none of the images that goes through the optimizer will work.
<img src="https://user-images.githubusercontent.com/64950861/228294928-6f692f37-1d30-4397-b37d-6c958ec50445.png" width="200">

Raw URL testing:
- :x: https://thumbnails.odycdn.com/optimize/plain/https://player.odycdn.com/speech/2e9a7dc6c99f0fb9.jpg
    - <img src="https://user-images.githubusercontent.com/64950861/228295948-34a669ca-81de-492f-9ce8-9253e9816d34.png" width="200">
- :heavy_check_mark: https://player.odycdn.com/speech/2e9a7dc6c99f0fb9.jpg
    - <img src="https://user-images.githubusercontent.com/64950861/228296014-0d3a8bbf-7703-471f-bb7f-e84610aea9a5.png" width="200">

With 2021 OS onwards, then it works.

**Comment by tzarebczan** [comment]
This is most likely due to lack of webp support. We rarely get any complaints, so I think most people are updated. It would be a hassle to serve / store non webp versions of all thumbs, so probably not something we'll consider anytime soon.
