### ISSUE TITLE
Going from livestream > regular video - video autoskips to next

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#2616]
It seems to skip to the end of the regular video, and then tries to autoplay next

repro:
play livestream, pop out enabled
play regular video

**Comment by tzarebczan** [comment]
Keep running into this one, pretty annoying.

**Comment by jessopb** [comment]
Can you confirm whether this still happens?

**Comment by tzarebczan** [comment]
Happens about 75% of the time. We also noticed sometimes the next clicked video autoplays automatically instead of requiring an additional play action.

**Comment by tzarebczan** [comment]
Jessop could not repro, but it happens pretty regularly here. Might be browser/OS specific.

**Comment by tzarebczan** [comment]
Thx for fixing @toshokanneko !
