### ISSUE TITLE
First video always fetches twice; first one is `undefined`

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#2624]
Repro:  after F5 on home, click a video.

Value coming from `selectStreamingUrlForUri`. 

<img width="423" alt="image" src="https://user-images.githubusercontent.com/64950861/229290492-eb5a341b-245a-452c-af32-3e978ef15de6.png">

**Comment by infinite-persistence** [comment]
`-- re-opened --`
Reverted the change as it affected other things.

**Comment by infinite-persistence** [comment]
@tzarebczan, this is still happening -- I reverted my fix since it was causing playlist issues. Passing on to Rave.

You need to enable "Autoplay media files", then load claim pages directly.

**Comment by tzarebczan** [comment]
Oh my bad, thought it was refixed in the last PR.

**Comment by infinite-persistence** [comment]
@jessop, I think the code-viewer issue wasn't a good one to highlight the problem I was facing.
Maybe tackle this after collections?  I'm always stuck when I need to tweak `withStreamClaimRender`.
