### ISSUE TITLE
"Wallet > Send :: Search" not working

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#2632]
Not seeing any network calls either

![image](https://user-images.githubusercontent.com/64950861/229997470-27b09004-c665-4e30-842e-6fb63e57f39a.png)

**Comment by tzarebczan** [comment]
Probably a similar issue with missing resolves

**Comment by jessopb** [comment]
Are there multiple issues re: missing resolves?

It looks like in December, useEffects that did resolving were taken out of claimPreview (for example, maybe others), and a withResolvedClaimRender HOC was made to sort of take its place at the page level. 

I'm currently thinking of a useResolve effect somewhere. 

Was there a strong opinion that a claim preview should definitely not be responsible for resolving its URI?
I could, for example, place this in effect in walletSend (after rewriting class component to functional).

**Comment by tzarebczan** [comment]
Not sure why it was done this way, Rafael seemed to think it was the right way. Let's just add whatever way is easier and makes the most sense.
