### ISSUE TITLE
Faulty display of multi-paragraph list items (ol>li>p)

### ISSUE THREAD

**Issue by RmbRT** [OdyseeTeam/odysee-frontend#2646]
**Bug**
In Markdown documents ([such as this one](https://odysee.com/@rmbrt:d/against-multi-core:e)), an ordered list with multiple paragraphs in one bullet point result in strange display, where the list number marker is in a separate line from the paragraph:
![Faulty rendering on Odysee.com](https://user-images.githubusercontent.com/12518378/230615601-b36d5f4d-2024-4704-bc11-3855334f1117.png)
Note that the same document displays correctly in the LBRY client:
![Correct rendering in LBRY client](https://user-images.githubusercontent.com/12518378/230615753-2367f7fb-4ac2-4544-aed9-40c9c19f323d.png)

**To Reproduce**&emsp;Investigate the document linked above.

**Expected behavior**&emsp;See the LBRY screenshot.

**Screenshots**&emsp;See above.

**System Configuration**&emsp;Odysee.com in the browser.

**Additional context**&emsp;
When investigating the DOM, I noticed that it is a simple `ol > li > p + pre + p` structure, so at least the DOM is correctly structured. I looked at the CSS, and it seems that you need to either: 1) change the `list-style-position` to `outside` and add a margin to the left of the list (which I recommend, since would make it easier to read multi-paragraph lists, as currently, it is not obvious where the list ends, and where the normal text resumes), or 2) add a CSS rule: `li>p::first-child {display: inline;}` and `li>p::first-child::after { content: " "; display: block; margin-bottom: /*normal P margin*/; }`.
This makes it look like this: ![hotfix screenshot](https://user-images.githubusercontent.com/12518378/230618897-5e6fa025-b4c7-4eff-a1f4-7ea85e4a33e3.png)

**Comment by RmbRT** [comment]
I also noticed that tab-indenting isn't that well supported as a means to indicate code blocks, but at least I can work around that with ```` ``` ```` blocks.

**Comment by toshokanneko** [comment]
419348853b2e4d951d224509e771167676f1de00

**Comment by RmbRT** [comment]
Thanks!
