### ISSUE TITLE
Blocking a specific word can be bypassed by changing up the capitalization

### ISSUE THREAD

**Issue by Abwasserrohr** [OdyseeTeam/odysee-frontend#266]
**Bug**
Spammers still can spam their link, even if I blacklisted it, they just change one letter to a uppercase and it goes through.

**Expected behavior**
It would be great if the check of the blocked words is not case sensitive.

**Screenshots**

![952äsddw](https://user-images.githubusercontent.com/44294954/141178162-1686c1a2-c74e-48e9-952a-e3fe5f21a181.png)

**Comment by tzarebczan** [comment]
Thanks for the report, this will be fixed on the backend. Should be in a few hours.

**Comment by tzarebczan** [comment]
(also, we're working on autoblocking these spammers...)
