### ISSUE TITLE
Claim Preview channel link click box too big

### ISSUE THREAD

**Issue by jessopb** [OdyseeTeam/odysee-frontend#2681]
![previewchannellink](https://user-images.githubusercontent.com/36554050/232949061-f2aa21ad-83a5-4aa9-add3-107f6d219a7f.png)
I often end up clicking the channel expecting to just go to the content.
Possibly css grid would do better for this general section.

**Comment by toshokanneko** [comment]
f1b29a5b26a38a1653eb0a7b7d26e8bcc2698d7b
