### ISSUE TITLE
"Duration" filter on channel pages is grayed out, if the content type filter is something else than "Any".

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/odysee-frontend#2691]
"Duration" filter on channel page is grayed out, if the content type filter is something else than "Any".

Seems to only happen in Odysee.com? 
Locally it works like expected. (Can set duration limit for "Any", "Audio" and "Video", and it's grayed out for others)

**Comment by infinite-persistence** [comment]
`--close--`
e014fe0b
