### ISSUE TITLE
Disabling autoplay next doesn't work in playlists

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/odysee-frontend#2701]
Playlist always auto plays next item in the list, no matter if auto play next enabled or not.

**Comment by tzarebczan** [comment]
That was a design decision. We didn't even used to show the auto play setting in the past, maybe it was readded with the settings cog.

**Comment by infinite-persistence** [comment]
It was there before the menu change.

I think for Playlist Mode, the setting meant "continue with Next Recommended when you've reach the end of the playlist, and if Loop is off"

**Comment by tzarebczan** [comment]
Ok, no worries then, let's leave it.
