### ISSUE TITLE
Don't allow clicking "Upload" if no file is selected

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/odysee-frontend#2722]
1. Select a file to upload
2. Reload page
3. File gets un-selected, but can still try to create an upload. (Results to an error, but still creates an entry in uploads)

**Comment by infinite-persistence** [comment]
Livestream Form also suffers from a similar problem, where users can submit without picking a replay or selecting a form.
Let's do this after the Unlisted PR to avoid conflicts.
