### ISSUE TITLE
Mature content filter is broken

### ISSUE THREAD

**Issue by RmbRT** [OdyseeTeam/odysee-frontend#2727]
**Bug**&emsp;[My post](https://odysee.com/@rmbrt:d/virtual-constructors:6) (a short markdown file) was marked as "mature" without my doing so. The tags are `programming` `language` `compiler` `virtual` `constructor`.

**To Reproduce** Visit https://odysee.com/@rmbrt:d/virtual-constructors:6
**Expected behavior** It should display normally.

**Screenshots**
![image](https://user-images.githubusercontent.com/12518378/235320362-1b52bd07-29e2-43ea-8d6e-8c5be2daa6f5.png)

**System Configuration** Odysee.com frontend.
**Additional context** I assume this happened due to a word filter or something, or an error in the upload form, because I did nothing different from my previous uploads, and even reused the exact same file as a thumbnail as I had used in a previous post that was not flagged as mature. I tried editing and re-uploading it via the LBRY client, and it is flagged as mature.

**Comment by tzarebczan** [comment]
Can you screenshot the edit page which shows the tags?

**Comment by RmbRT** [comment]
@tzarebczan 
![image](https://user-images.githubusercontent.com/12518378/235321362-7bf2bd67-9a2c-4282-9e7b-8612bb5a7bd8.png)

**Comment by RmbRT** [comment]
![image](https://user-images.githubusercontent.com/12518378/235327433-b20ddcee-d32a-49f6-b958-3804628e1428.png)
re-issuing the upload via odysee.com, hoping this will change anything.

**Comment by RmbRT** [comment]
Update: still flagged as 'mature'. I tried uploading a test document, and it was not flagged. I have no idea what's wrong here. Maybe some word in the content trips up the filter?

**Comment by tzarebczan** [comment]
We'll take a closer look on Monday. Definitely not normal, haven't seen it before either. 

Sorry!

**Comment by tzarebczan** [comment]
@RmbRT this should be fixed in about 20 minutes - https://github.com/OdyseeTeam/odysee-frontend/commit/20c1054a6e261655823892c736382660a21a46d4

Might need a blog post to explain what happened there :p

**Comment by RmbRT** [comment]
LMAO. The joys of javascript.

**Comment by RmbRT** [comment]
You guys should switch to WASM or something.
