### ISSUE TITLE
Channel icon sometimes not showing on video page with direct link/refresh

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/odysee-frontend#2739]
Some examples, may need to refresh page(?) for it to break:
https://odysee.com/@a:f1/AAy:c  
https://odysee.com/@RetroTechRalph:5/3-xbox's,-ebay-junk.-part-1.-the-xbox:b  

[channel-icon.webm](https://user-images.githubusercontent.com/34790748/235712227-ef4885a1-591f-4226-a06d-be17805072b9.webm)

**Comment by tzarebczan** [comment]
Shows when you mouse over it too
