### ISSUE TITLE
pt-BR

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#2743]
Might need some mapping

**Comment by infinite-persistence** [comment]
Ok, it was just `pt-BR` .. I mixed up PRs.

Instead of adding a map, just copy-pasted it.  

- [ ] Oddly, it didn't work immediately.  Need to propagate to CF or clear cache?

**Comment by tzarebczan** [comment]
What's not working exactly? I seem to be able to switch to pt/pt-br and it works.

**Comment by tzarebczan** [comment]
Ah, probably on salt / in your PR.

**Comment by infinite-persistence** [comment]
Had to copy `pt_BR.json` to `pt-BR.json` in the server last night.
It didn't work immediately -- I guess it just needed another build to get pushed.
