### ISSUE TITLE
titles cut off on related 

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#2757]
https://odysee.com/@adam.fury:d/ITWDIEUDONNE:4?lc=43286545262d436c58c1535df0f2f75cfc7817d4afdd1ff9ab7ecaa729518f25

**Comment by tzarebczan** [comment]
Happening on desktop also, same claim: https://odysee.com/@adam.fury:d/ITWDIEUDONNE:4?lc=43286545262d436c58c1535df0f2f75cfc7817d4afdd1ff9ab7ecaa729518f25

**Comment by toshokanneko** [comment]
da9f6b055cbbe9ef9960dba725fce0016de2deb2
