### ISSUE TITLE
improve upload error handling

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#276]
See slack for other suggestions and feedback. 

- [x] Users are still seeing some errors, but the files actually retry/finish correctly. Maybe suppress if we can tell? 
- [x] double notify calls causing issues on backend?

**Comment by tzarebczan** [comment]
- [ ] Improve what happens on new tab/refresh (old sessions double uploading?)

**Comment by infinite-persistence** [comment]
I think the first 2 was when we "used the correct endpoint"?

- [x] Improve what happens on new tab/refresh (old sessions double uploading?) 
    - <sub>KP: Closed by #339</sub>

**Comment by infinite-persistence** [comment]
Known suppressible errors:
- [ ] Sync upload completion between tabs, as removing an completed upload from another tab causes the "file not found" error.

**Comment by infinite-persistence** [comment]
`Close`
Seems like less errors now.  Other remaining known corner-cases have a separate ticket for it.
