### ISSUE TITLE
Design & UI Issues - Mai 2023

### ISSUE THREAD

**Issue by toshokanneko** [OdyseeTeam/odysee-frontend#2767]
**Remaining legacy issues from the last Thread**

- [x]  Jumpy footer.
https://github.com/OdyseeTeam/odysee-frontend/issues/2592#issuecomment-1501391804

- [ ]  Channel selector at the end of the upload page, doesn't make as much sense any more...
https://github.com/OdyseeTeam/odysee-frontend/issues/2592#issuecomment-1528716488

- [ ] If you refresh on a File Page, the logo blinks after something is fetched.
https://github.com/OdyseeTeam/odysee-frontend/issues/2592#issuecomment-1535950447

**Separate Threads**

- [ ] https://github.com/OdyseeTeam/odysee-frontend/issues/2378

- [ ] https://github.com/OdyseeTeam/odysee-frontend/issues/2094

**Comment by keikari** [comment]
Light theme, white text on dropdown hover
![light](https://github.com/OdyseeTeam/odysee-frontend/assets/34790748/e6fb319a-f6fc-4da6-a656-7583ca0a018e)

**Comment by infinite-persistence** [comment]
Collection Publish ... the "Additional Options" card is missing background

<img width="547" alt="image" src="https://github.com/OdyseeTeam/odysee-frontend/assets/64950861/44745683-f267-4689-a4c7-8631617f8fe0">

**Comment by infinite-persistence** [comment]
- [ ] Knight Rider effect (vertical spinner) when confirming in small layout.  Maybe intentional, though.
- [ ] Why Primary Color as the background?  Felt like an action button when it is not.
- [ ] Does the tooltip appear in mobile?  If not, can it appear on tap?

<img width="329" alt="image" src="https://github.com/OdyseeTeam/odysee-frontend/assets/64950861/8ad7cdac-9c4b-4e9a-a99d-6b8c1118f20d">

**Comment by infinite-persistence** [comment]
- [ ] Inversely, "Support" doesn't have a background as an action button (or is it a link/secondary action)
- [ ] When hovered, green-on-red feels hard to red.  

http://localhost:9090/$/playlist/3b5eb161c2fba258b1bf55eedfde7348b675772a

![image](https://github.com/OdyseeTeam/odysee-frontend/assets/64950861/450d0fab-915c-464e-8737-31d9528a3eb6)

**Comment by infinite-persistence** [comment]
Additional gap that only exists in medium layout.  Collection Publish Page

<img width="261" alt="image" src="https://github.com/OdyseeTeam/odysee-frontend/assets/64950861/8b53bd45-669b-496b-91fd-ce2292b7c005">

**Comment by infinite-persistence** [comment]
## Suggestion

<img width="99" alt="image" src="https://github.com/OdyseeTeam/odysee-frontend/assets/64950861/9d51f01b-721d-496c-8f29-468cc00b70b6">

This popup always makes me think a bit on what's going on.

Perhaps "that's you" and other unselectable ones can be displayed differentlty?
- Vary the font size and/or gray out the text (that's what GH does)
- Or bold
- Or different background color

**Comment by infinite-persistence** [comment]
https://odysee.com/@timeout:8/upcoming-livestream:0

Avatar position is off

<img width="361" alt="image" src="https://github.com/OdyseeTeam/odysee-frontend/assets/64950861/c00314e9-a9e8-4475-8a58-77f9f2d3e7bb">

**Comment by infinite-persistence** [comment]
https://odysee.com/@timeout:8/upcoming-video:3d  
Support tab misaligned again

<img width="395" alt="image" src="https://github.com/OdyseeTeam/odysee-frontend/assets/64950861/33bde46a-2501-42ec-bd50-ed0bc5584d4c">

**Comment by Abwasserrohr** [comment]
- [ ] Account selector on playlist looks odd when anonymous is selected, tested in both Firefox and Chrome:
![](https://github.com/OdyseeTeam/odysee-frontend/assets/44294954/2eef54c3-443e-4ff1-8cb4-ed6c0ebf3443)

**Comment by infinite-persistence** [comment]
Popout chat dark-on-dark

![image](https://github.com/OdyseeTeam/odysee-frontend/assets/64950861/d0cb2e85-87f6-4012-bbec-8cf371413048)

**Comment by keikari** [comment]
Different empty space between current livestream and upcoming section in home vs content tab

https://github.com/OdyseeTeam/odysee-frontend/assets/34790748/ba3c99d1-8354-4bb1-9891-2260a831d69a

**Comment by infinite-persistence** [comment]
Thoughts on this?  
- Preferred the original link version rather than giant button.
- Some languages don't follow the same structure, so having a giant button in the middle of a sentence is weird.

<img width="458" alt="image" src="https://github.com/OdyseeTeam/odysee-frontend/assets/64950861/14c6ae3f-4a31-48b8-9bcb-d9f71d680ea6">

**Comment by infinite-persistence** [comment]
name wrapped

https://odysee.com/$/report_content?claimId=a1cc1abb16f04b3a34681e0dd998e125747cb018&commentId=da6d2467a32571989bfa17a588e18604d8e8a0966189d3d8956b4d4532ca551f

<img width="334" alt="image" src="https://github.com/OdyseeTeam/odysee-frontend/assets/64950861/ebeee3e1-514a-4781-84e1-82eb0af614bc">

**Comment by infinite-persistence** [comment]
## Dim the creator handle?
Just a suggestion:  it's been a while ... I always have issues reading white text over bright red in creator's channel link, even in English characters.  

<img width="248" alt="image" src="https://github.com/OdyseeTeam/odysee-frontend/assets/64950861/a40bcebb-a609-4cba-8d18-01db19450bad">

The dimmed red in "Livestream Chat" and tabs is much better, but I argue dimming it even further would be nice (like using those soft highlight in IDEs <img width="119" alt="image" src="https://github.com/OdyseeTeam/odysee-frontend/assets/64950861/223eee24-d735-4c93-b39a-b8fe03b56bda">).  We just need to hint that he's the creator, not emphasize on it, right?

Feel free to close if disagree :+1:

**Comment by infinite-persistence** [comment]
A few css lint errors.  Seems legit?

![image](https://github.com/OdyseeTeam/odysee-frontend/assets/64950861/0943ef12-c43f-474a-b819-5a60c722a3aa)

![image](https://github.com/OdyseeTeam/odysee-frontend/assets/64950861/0b2cd977-f405-45c6-907d-6920a4666987)

![image](https://github.com/OdyseeTeam/odysee-frontend/assets/64950861/96537ed6-f5d5-400d-a5f5-987d84cc7731)

**Comment by keikari** [comment]
Long category names don't fit well. (Last letter is completely cut out)

Example on language "Suomi"
![translation](https://github.com/OdyseeTeam/odysee-frontend/assets/34790748/ffc5b76f-1e1b-4f4c-a4c1-c1ead73a73fa)

**Comment by infinite-persistence** [comment]
Mobile -- vertically off + no margin
<img width="372" alt="image" src="https://github.com/OdyseeTeam/odysee-frontend/assets/64950861/73ff99db-bf8a-48b3-ad9f-984ffa29dfde">

**Comment by keikari** [comment]
Long tags in list item make list edit page look odd in narrow window
Also makes the items when viewing list normally a bit longer, but less noticeable.

Can make happen by adding this into the list https://odysee.com/@AllThingsSecured:9/is-your-iphone-hacked-here's-the-best:8

![long](https://github.com/OdyseeTeam/odysee-frontend/assets/34790748/58059250-3571-403e-b743-6295bbddcd6a)

![long-tags](https://github.com/OdyseeTeam/odysee-frontend/assets/34790748/f871a40e-0491-4e9a-a4de-26fe9d86415c)

**Comment by infinite-persistence** [comment]
<img width="114" alt="image" src="https://github.com/OdyseeTeam/odysee-frontend/assets/64950861/70f959b3-04fe-4057-afb2-497b68dc199c">

Icon color contrast problem in tabs

**Comment by infinite-persistence** [comment]
Incognito.  Feels like clipped rather than missing a pad

<img width="334" alt="image" src="https://github.com/OdyseeTeam/odysee-frontend/assets/64950861/96367d42-f629-4625-8f62-bc825a14be0e">

**Comment by toshokanneko** [comment]
Continue here: https://github.com/OdyseeTeam/odysee-frontend/issues/2846
