### ISSUE TITLE
videos over 24 hours show wrong duration

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#2771]
Looks like we restart duration after 24 hrs. 

          "duration": 88318,

https://odysee.com/@cornbreadman:f/Colonel_Kurtz_LSA_05_06_2023_24H_SPECIAL:3

![image](https://github.com/OdyseeTeam/odysee-frontend/assets/8120721/ec51e49a-5a45-4cb8-8872-a89ad431cbf0)

**Comment by infinite-persistence** [comment]
If the resolved claim is showing `88318`, what should the front-end do?  Run `get` and edit the claim?
