### ISSUE TITLE
Copyright notice reverts to the default message on publish edit

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/odysee-frontend#2790]
The "Copyright notice" always defaults to "All rights reserved" text on edit.

![default-text](https://github.com/OdyseeTeam/odysee-frontend/assets/34790748/011235d6-d7d7-467e-8edf-85b7a024caee)

**Comment by infinite-persistence** [comment]
Will do it after unlisted merge to avoid potential conflict.  Would like to restore some code back into redux as well.

**Comment by tzarebczan** [comment]
We should also show the license info under the details somewhere (credit details?)
