### ISSUE TITLE
scheduled stream replay upload issues

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#2801]
- [x]  I think we used to default to "choose replay" option if they have replays (and the current time is after the scheduled time for scheduled ones...for anytime, maybe update only is fine...) ? 
- [x] Since it's on update only, there's a future date filled in. When you use the upload replay option (not select from replays), it keeps the date and the form says "Cannot set to a future date.". Using replay seems to clear it, so we should do the same here. 
    - <sub>Closed by #2816</sub>

**Comment by infinite-persistence** [comment]
> _I think we used to default to "choose replay" option if they have replays (and the current time is after the scheduled time for scheduled ones...for anytime, maybe update only is fine...) ?_

I think it is that way now because the replay-fetch takes time, so the radio selection could be bouncing around.  The fix would be to hide the entire section in a spinner until the fetch is done.  Can do that, but probably not much benefit?

**Comment by infinite-persistence** [comment]
> _I think we used to default to "choose replay" option if they have replays (and the current time is after the scheduled time for scheduled ones...for anytime, maybe update only is fine...) ?_

Ok, maybe I get what you mean now.  There is an odd difference between editing the same claim from Uploads Page vs  Livestream Setup page, where the latter works like what you described, and the former is totally "update only" without other choices.

Anyway, will make them both the same, and select "Use Replay" as the default if exists.
