### ISSUE TITLE
No clear way of deleting item from playlist

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/odysee-frontend#2815]
I think currently item can be only delete from playlist with these steps:
1. Click 3-dot menu on some list item
2. Click "Add to Playlist"
3. Uncheck the current list from there

**Comment by tzarebczan** [comment]
You should also see something like this in the 3 button menu: 
![image](https://github.com/OdyseeTeam/odysee-frontend/assets/8120721/dd0dc3a9-59be-42d5-84a0-3231e2369d07)

Should be able to do it from the playlist page, and from the content page too
