### ISSUE TITLE
Short Comments Not compatible with video or web links

### ISSUE THREAD

**Issue by juanpc2018** [OdyseeTeam/odysee-frontend#2826]
when you paste a Video link in Telegram, or Signal, or WhatsApp,
generates a preview image...

but Odysee.com fails, same as Github.com
![ThisIsaTest](https://youtu.be/O0xpTtdPD4w)
![ThisIsaTest](https :// youtu .be/O0xpTtdPD4w)

video preview image is a division of the video,
if video is 1920x1080, preview could be:
/10 = 192x108 
/8 = 240x135
/6 = 320x180
/5 = 384x216
/4 = 480x270
/3 = 640x360
/2 = 960x540

IF video is [4:3](https://en.wikipedia.org/wiki/Fullscreen_(aspect_ratio)) ![NTSC](https://en.wikipedia.org/wiki/NTSC) compatible for Cellphone vertical screen, needs other values.
https://en.wikipedia.org/wiki/NTSC
https://en.wikipedia.org/wiki/Fullscreen_(aspect_ratio)

the idea is to pass-through the link, Not give error,
and give a preview in Odysee Premium.
when preview image is clicked, grows to Box size like Yandex browser.

The problem is related to adding ! at the beginning,
just [...] (...) work fine, No !

Click New Comments:
https://odysee.com/@Happy:9/Howtocommentwithanimage:7

`Web link Automatic: https://en.wikipedia.org/wiki/Fullscreen_(aspect_ratio) <-- Error`
`Manual [without](https://en.wikipedia.org/wiki/Fullscreen_(aspect_ratio)) !,`
`and ![with](https://en.wikipedia.org/wiki/Fullscreen_(aspect_ratio)) !`
`Video Link: [without](https://youtu.be/O0xpTtdPD4w) !,`
 `and ![with](https://youtu.be/O0xpTtdPD4w) !`

**Comment by tzarebczan** [comment]
Don't plan to change anything here at this time, sorry.
