### ISSUE TITLE
Notifications History has a 10 month limit

### ISSUE THREAD

**Issue by juanpc2018** [OdyseeTeam/odysee-frontend#2828]
or a 52 Notifications limit,
https://odysee.com/$/notifications

if has less than 50 notifications, 10 month limit,
if has more than 50 notifications, also has a limit, could be 24 hours or 24 days.

**Comment by tzarebczan** [comment]
This is a backend issue mostly, we only send last 50 and don't have pagination. 

Nothing here will change for a bit, closing for now.
