### ISSUE TITLE
There is No "Your Comments History" like YT

### ISSUE THREAD

**Issue by juanpc2018** [OdyseeTeam/odysee-frontend#2829]
[Your Comment History] or [Watch History] Tab should be in:
https://odysee.com/$/watchhistory
also:
[Notifications] or [Your Comment History] Tab in:
https://odysee.com/$/notifications

to avoid unnecessary nested menus, or click in circles.
when clicking [your comment], should link to video.
should be only text, video name & comment, video preview is unnecessary.

**Comment by tzarebczan** [comment]
It's on the settings page currently
