### ISSUE TITLE
Browser compatibility broken

### ISSUE THREAD

**Issue by HT-7** [OdyseeTeam/odysee-frontend#2832]
Until a few weeks ago, Odysee was able to run on Firefox 52 ESR from 2017, a time before Mozilla scraped all XUL extensions with Firefox Quantum, and I was proud of Odysee for caring that much about backwards compatibility. Now, a blank page appears even on a browser released as recently as 2019, Google Chrome 73.

Now, one might ask "Hey! Why don't you just update your browser?"

I obviously use recent versions of web browsers most of the time since that is more secure and stable, however, people might be in situations where they are unable to update their browser, such as the Linux dependency hell, restrictions in a work environment, running an emergency Linux boot disc which has an older version of Firefox, and the necessity of features only older versions are equipped with, such as the ability to deactivate the highly annoying pull-to-refresh trap. 

Indeed, pull-to-refresh is more of a trap than anything remotely helpful. Since 2019, Google enforces the pull-to-refresh gesture on the mobile Google Chrome. New versions of Chrome do not give users the option to deactivate the anti-feature that is pull-to-refresh, so users who wish to use Chrome without pull-to-refresh are forced into using an earlier version which allows deactivating the pull-to-refresh annoyance through `chrome://flags`.

Ideally, browser updates would only bring improvements and have no unexpected negative side effects.

The unfortunate reality is that updates can and frequetly *do* break stuff. 

Therefore it would be beneficial to reinstate compatibility with earlier versions of web browsers. Many people would be silently thankful.

Please note as well that the mobile website of YouTube even works in Chrome version 43 from 2015, as I have tested out of curiosity.

**Comment by keikari** [comment]
Blank page can also happen in modern browsers, if it's happening for same reason few force reloads(Ctrl+f5) should fix it.

**Comment by HT-7** [comment]
It has actually been fixed! Odysee works again on browsers from 2019 and even 2017.

## Thank you, Odysee Team.

Thank you for your amazing work in creating that pretty user interface. And thank you for your outstanding browser compatibility.

**Comment by tzarebczan** [comment]
Woohoo!
