### ISSUE TITLE
Publish forms: Content restriction bugs

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/odysee-frontend#2835]
Tested these on kp/salt

* [x] Changing channel in form while restricted settings is expanded, allows selecting tiers with no "exclusive content" perk
    - <sub>Will be closed by #2860</sub>
    - https://github.com/OdyseeTeam/odysee-frontend/assets/34790748/6752dea9-673c-4ef8-8127-adc3f58083c8

--------------
* [ ] Inconsistent error/selections when toggling the restricted  content on/off. 

https://github.com/OdyseeTeam/odysee-frontend/assets/34790748/0c215fba-46a8-4a43-b2c7-2406973649f0

------
* [x] Livestream replay publishing/edit shows "access to livestream" tiers instead of "access to video" tiers
    - <sub>Will be closed by #2862</sub>
    - <img src="https://github.com/OdyseeTeam/odysee-frontend/assets/34790748/51328928-f5ec-449a-870b-c5728fc958c8" width="150">

------
* [ ] If upload is somehow added to tier that doesn't come with "exclusive content"-perk, it sticks through edit and can't be toggled off without disabling all restrictions for the file.  
![restri](https://github.com/OdyseeTeam/odysee-frontend/assets/34790748/d5d6d048-37c9-4ea5-9c60-f271f560364c)

**Comment by infinite-persistence** [comment]
> _Livestream replay publishing/edit shows "access to livestream" tiers instead of "access to video" tiers_

This seems intentional based on the originator's comment, and I think makes sense since it's a video and not a livestream placeholder?

```
// replays use 'exclusive content' perk, livestreams use 'exclusive livestreams'
```

**Comment by infinite-persistence** [comment]
> _Livestream replay publishing/edit shows "access to livestream" tiers instead of "access to video" tiers_

Looks like indirectly fixed from the recent changes.  Can confirm?
