### ISSUE TITLE
[mobile] Embed / play the video player directly into blog posts + function without floating player setting

### ISSUE THREAD

**Issue by Abwasserrohr** [OdyseeTeam/odysee-frontend#285]
**Is your feature request related to a problem? Please describe.**
I want to create a blog that contains videos of my contests, like these here: https://peakd.com/hive-107989/@immanuel94/minecraft-medieval-house-ideas-2021

The problem I currently have is that I can't embed Odysee videos directly in a post, it will just put a preview and link to the video directly, but I think it would be nice if the video could be played in the blog directly to not cut out of the flow of reading the blog, this is my test blog:

https://odysee.com/@skyrift:2/testing-stuff:2

**Describe the solution you'd like**
I would like to request that in level 0 posts (the one created on the top with no children), or don't know how they are called exactly, is embedded directly like it would on any external page similar to YT videos on peakd I do at the moment.

I also tried to use HTML, but the iframes are blocked, it seems.

**Comment by tzarebczan** [comment]
Are you doing this on mobile or desktop browser? We don't have mobile support yet, but desktop browsers will play your videos right in the blog.

**Comment by tzarebczan** [comment]
![image](https://user-images.githubusercontent.com/8120721/141804294-29d355a5-5f25-44c6-a470-73465a32dba3.png)

Will rename this issue to make it work on mobile in line...I forget what the challenge was.

**Comment by Abwasserrohr** [comment]
For me, it embeds the Odysee videos, but if I click on them, the viewer is redirected to the video itself and can't stay in the video.
This is on Desktop for me:
https://odysee.com/@skyrift:2/minecraft-train-station-ideas-2021:b

**Comment by Abwasserrohr** [comment]
> ![image](https://user-images.githubusercontent.com/8120721/141804294-29d355a5-5f25-44c6-a470-73465a32dba3.png)

This is how it looks for me:
![324jks](https://user-images.githubusercontent.com/44294954/141805132-eba6f1c1-3cb1-46fe-8a3c-22c9c7dba33e.png)

**Comment by tzarebczan** [comment]
Are you clicking the play button? Do you have the floating player enabled in settings?

**Comment by Abwasserrohr** [comment]
I click on the play button, I have not enabled the floating player.

**Comment by tzarebczan** [comment]
yea, we should be able to get both working.

**Comment by saltrafael** [comment]
Fixed @Abwasserrohr ?

**Comment by Abwasserrohr** [comment]
Looking into it

**Comment by Abwasserrohr** [comment]
It's fixed 👍
