### ISSUE TITLE
Fix tile CSS for slow menu drawer

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#286]
There is still some lag in the menu drawer.  This can be seen clearly by using "CPU 4x slowdown" in the  Performance tab, or on an older phone.  I had everything removed from the sidebar to remove other factors.  The last piece of bottleneck is probably with the CSS re-calculations of the tiles when the drawer toggles.

- In web, we can argue that we have no choice since the tiles need to be shrunk and moved (unless we make the full drawer mode "floating only" and never pinned).
- In mobile, where we need to toggle the drawer to navigate, it shouldn't have taken that long since the tiles remain unchanged (the drawer is floating on top).

I think doing this should help https://developers.google.com/web/fundamentals/performance/rendering/reduce-the-scope-and-complexity-of-style-calculations

**Comment by tzarebczan** [comment]
Was this addressed in the linked PR? I remember some discussion around it.

**Comment by infinite-persistence** [comment]
### Close
The placeholder animation turned out to be the bigger bottleneck than the scope recalculation, and we've removed it.
Should be good enough for now, plus major css changes coming with new Theme.
