### ISSUE TITLE
Livestreams: Use periodically updated frame from a stream as a thumbnail instead of static one

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/odysee-frontend#2870]
From discord
https://discord.com/channels/721806979928162404/914213136414953492/1116980905404276738
![preview](https://github.com/OdyseeTeam/odysee-frontend/assets/34790748/357f3764-1d75-4c28-a72b-4ad39b24a53c)

**Comment by TheRenegadist** [comment]
A simple checkbox under the Thumbnail settings for a stream that accomplishes this would be perfect.

**Comment by tzarebczan** [comment]
This would need backend support from the livestreamer to generate these. Great suggestion, but don't think it will happen anytime soon.
