### ISSUE TITLE
[Suggestion] Queue Uploads After 5 Videos

### ISSUE THREAD

**Issue by TheRenegadist** [OdyseeTeam/odysee-frontend#2871]
Hello, currently when uploading multiple videos to Odysee instead of only uploading the first 5 of many like YouTube does it instead uploads every single video no matter the upload count at the same time leading to slow upload times. An example is today I'm uploading 20 videos and all of them are uploading at the same exact time, given they're all several GB's each it's taking forever for all of them to upload.

Can Odysee implement a feature to where after 5 videos are uploading at the same time it pauses and queues all uploads after it so that only 5 are uploading at the same time? This would allow people to queue up large amounts of uploads without using bandwidth on all of them and probably lighten to the load on Odysee's servers.

**Comment by tzarebczan** [comment]
Thanks for the feedback, but this isn't something we'd plan to work on anytime soon.
