### ISSUE TITLE
Clear cached claim after edit is confirmed

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#2873]
If you edit a restricted claim, the control tag and several other values stayseven after confirmation.  This causes:
- [ ] the tile overlay to incorrectly show the padlock, and also causes the `mismatch in is_protected` with the backend.
- [ ] a "changed to anon" edit incorrectly showing the previous channel, even though the SDK call is correct.

**Comment by tzarebczan** [comment]
I also just published a new restricted livestream, and the publish form had all the claim data after the success modal.  Is that a bug or something intentional that's new (might be useful to upload with new name + existing data).

**Comment by infinite-persistence** [comment]
That's existing behavior.  Logged in a draft https://github.com/orgs/OdyseeTeam/projects/14?pane=issue&itemId=28870375, and also replicated in `salt` (old code).  Maybe just missing a `clear` call.  Will look tomorrow.

But that's different from this issue -- this one's for the tiles in Uplaods Page.
