### ISSUE TITLE
Crash on livestream creation

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/odysee-frontend#2877]
1. Have tiers with "exclusive streams"-perk
2. Try to publish a stream (tiers selected or not)
3. Click "Create" -> Crash

![stream-creation-1](https://github.com/OdyseeTeam/odysee-frontend/assets/34790748/7c4d5a7b-6c9c-4043-96fb-1ae619c48286)

Clicking the error directs here:
![332](https://github.com/OdyseeTeam/odysee-frontend/assets/34790748/f197dc09-98e4-442b-af61-c4b3d19f18dc)

**Comment by tzarebczan** [comment]
Hmm, a user was telling me this but i couldn't repro. Will try again. There was a patch overnight...

**Comment by infinite-persistence** [comment]
Can revert first if want

**Comment by keikari** [comment]
> Hmm, a user was telling me this but i couldn't repro. Will try again. There was a patch overnight...

Having "Publish confirmation" disabled seems to avoid the crash

**Comment by tzarebczan** [comment]
I tried both, hmm.

**Comment by tzarebczan** [comment]
I only have 1 membership, maybe that's why.

**Comment by tzarebczan** [comment]
Same after i created another. We can either revert or see if a fix is obvious from the code Miko linked.

**Comment by keikari** [comment]
I also got crash on new account with one membership.

It doesn't seem to crash on in my default browser session, not even after a few force reloads.
But does crash on fresh private session in brave/ff, on new/main account.
(Testing on kp)

**Comment by keikari** [comment]
Actually normal uploads are also crashing for me with same error. (Didn't realize to check earlier)
