### ISSUE TITLE
The Search Function is the Worst I Have Ever Encountered

### ISSUE THREAD

**Issue by VehementHam** [OdyseeTeam/odysee-frontend#2898]
# Problem
Okay, so if I want to search for a video, I am screwed. Let me just show you a comparison:
## Youtube
![image](https://github.com/OdyseeTeam/odysee-frontend/assets/75701545/ff90057d-65a9-4aec-98cd-700bfdaf2648)
## Odysee
![image](https://github.com/OdyseeTeam/odysee-frontend/assets/75701545/f90e7f66-6847-4e34-abd9-2ca933639ee2)

# Primary Solution
I think that the "Exact match" option is a big step in the right direction. The obvious solution is to make the search algorithm better. But that is easier said than done. 
# Secondary Solution
Now I am no authority when it comes to the technical process of how searches are executed, but I will do my best 'cause the feature request template asks me to. So I am thinking something more along the lines of searching with tags.  Maybe some options like search a certain creator or make certain keywords exact match only like you can with some search engines by using quotes
# Conclusion
Anyways, I think that this is the **main** thing driving users away from Odysee sending them crawling back to Youtube or at least it is for me. I think that this is where a much larger amount of development effort should be allocated to and prioritized above other issues due to the extremity of this issue.

**Comment by tzarebczan** [comment]
Thanks for the suggestion. There's a separate private repo for the search features and improvements are on the Todo list.
