### ISSUE TITLE
Own comments showing in own channel page, after viewing them in the ownComments page

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/odysee-frontend#2906]
1. Go to https://odysee.com/$/settings/ownComments
2. Go to your channel's "Community" tab
3. Own comments showing there (Refreshing fixes)

**Comment by antoniodebaca** [comment]
Can i work on this?

**Comment by tzarebczan** [comment]
Hey @antoniodebaca , welcome to the project! She's all yours.

**Comment by antoniodebaca** [comment]
If i change line 244 of ui/component/commentsList/view.jsx from "if (page === 0) {" to "if (page >= 0) {" it will reset our commentsList and get those comments to that view, where if the page is equal to zero, which it will never have been zero if they have visited their own comments. So is that the correct way of going about this. That means if you already have those comments loaded into state, we will have to do another fetch to the api to get those comments. So is there any chance of talking about best practices?

**Comment by toshokanneko** [comment]
d069aa0d8c1a620ebcad7d3227cc8bad5086530f
