### ISSUE TITLE
Article publishing

### ISSUE THREAD

**Issue by Xyncgas** [OdyseeTeam/odysee-frontend#2907]
On odysee, I can publish article of any length, but if editing an article I pasted before publishing, and that article is over 20k characters long, it lags so hard on every keystroke I can't edit my article.

It gets worse if I am editing an article of more character count, what's going on, hopefully you can let the browser venders know this to be fixed

**Comment by tzarebczan** [comment]
Please try again in an hour or so, we should have something up that's a bit better, but not perfect.

**Comment by Xyncgas** [comment]
Thanks for the fix it still lags but at least I can add my commas.
