### ISSUE TITLE
2 Factor Authentication. (Mail/TOTP/WebAuthm)

### ISSUE THREAD

**Issue by Killercat103** [OdyseeTeam/odysee-frontend#2930]
One or multiple methods of 2FA would be desirable to increase security of users and Odysee channels. All of these methods are well established offering varying security (WebAuthm being strongest and mail weakest) so I would expect there to be libraries available. Example of TOTP apps: Aegis, AndOTP, FreeOTP and GNOME Authenticator
Examples of security keys: OnlyKey, Solokey, Nitrokey.

**Comment by tzarebczan** [comment]
There are no plans at this time to implement this.

**Comment by Killercat103** [comment]
@tzarebczan May I ask why? One would argue that 2FA is almost essential in this day and age.  This is very useful for creators who may be specifically targeted. I use it on 3/4 of my account and seeing that Odysee does not support this was quite disappointing. It may give an impression that security is not taken seriously or the service lags behind in that area.
