### ISSUE TITLE
Livestream chat: Deleting comment that was already deleted by someone else, makes chat blank.

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/odysee-frontend#295]
Deleting already deleted comment makes livestream chat blank

**To Reproduce**
1. Have a  live stream with messages in chat
2. Open same live stream to another tab
3. Delete one message from any of the tabs
4. Delete same message from the remaining tab
5. Chat goes blank in the remaining tab. 
 (Sending a new message or reloading page will make chat visible again.)

**Comment by tzarebczan** [comment]
This should no longer be possible as we show a "removed" message. Can you confirm? Maybe still possible but doesn't fail?

**Comment by keikari** [comment]
Can still happen, the "[Removed]" message still has option to Delete.(And other 3-dot menu options)
