### ISSUE TITLE
[Feature] When changing from Unlisted > Public refresh creation date 

### ISSUE THREAD

**Issue by z2rec** [OdyseeTeam/odysee-frontend#2958]
**Is your feature request related to a problem? Please describe.**
I like to first publish my articles unlisted while I test around a bit and add more things over few days and when I decide it's finished I set it to public but the creation date goes back few days so followers might miss it.

**Describe the solution you'd like**
When you set article to Public, refresh the creation date so it appears as fresh content on the timeline.

**Comment by tzarebczan** [comment]
When you edit the post and choose public, you’ll see an option for release date in the additional options section to reset. 

Not sure this should happen automatically, could be unintended behavior. We can make it clearer that there’s a choice though.

**Comment by z2rec** [comment]
I thought this was only for Scheduled posts but now after clicking on Scheduled option and seeing the option. I see the difference. It was my mistake and in my opinion it is obvious enough (now). Thank you.
