### ISSUE TITLE
Send notification when tagging a channel in a comment

### ISSUE THREAD

**Issue by FinixFighter** [OdyseeTeam/odysee-frontend#2967]
**Is your feature request related to a problem? Please describe.**
At the moment, if the user tags a channel in a video comment (using the @ChannelName annotation), the tagged channel doesn't receive any notification.

**Describe the solution you'd like**
When tagging a channel in a comment, the tagged channel should receive a notification stating that it has been cited in a comment.

**Describe alternatives you've considered**
A setting for disabling this kind of notifications should be available (even for avoiding big channels being tagged a lot and receiving a bunch of notifications).

**Additional context**
![Screenshot from 2023-09-12 11-53-03](https://github.com/OdyseeTeam/odysee-frontend/assets/19877271/2b1349fb-f8f1-4a5a-9d79-1c9bcfa4a1cf)
This image is an example. The tagged channel won't know that I mentioned it.

**Comment by tzarebczan** [comment]
there's an open issue for the internally, the frontend work was done for it. No eta at this time.

**Comment by tzarebczan** [comment]
It's on the notifications side which relates to accounts, so that's an internal repo. 

Basically we needed to add settings for people to control, and things got stuck there.
