### ISSUE TITLE
Blank website

### ISSUE THREAD

**Issue by alexanderbkl** [OdyseeTeam/odysee-frontend#2968]
**Bug**
The website is totally blank, even though I use a VPN from multiple devices or access through Tor.

**To Reproduce**

1. Go to https://odysee.com

**Screenshots**
![image](https://github.com/OdyseeTeam/odysee-frontend/assets/28397938/f9ef171f-a888-46d9-b742-a60642b10a6f)

Getting HTML inside JS file:

![image](https://github.com/OdyseeTeam/odysee-frontend/assets/28397938/cfae363a-3c2b-43ce-a7e5-d002693dccc6)

**System Configuration**
Tried on Windows and Android

**Additional context**
This wasn't happening a couple days before, same happened to a guy from Switzerland 2 months ago but from his statements he could access through Tor.

**Comment by alexanderbkl** [comment]
no longer happens, but I think this is a concern for future due to the fact that it happened to me recently and to another use a couple months ago

**Comment by tzarebczan** [comment]
Should be working again for most users. 

if not:
Try an incognito session for now for quick access. Something bad was cached and some browsers won’t clear it properly.  

Another option: open dev tools with Ctrl-shift-I and then right click on the refresh button in the address bar: clear cache and hard reload.

last ditch scenario: find a way to clear all site data and cache in your browser for odysee.com or whole browser (will log you out everywhere)
