### ISSUE TITLE
Increase audio quality for low video quality presets (144/240p)

### ISSUE THREAD

**Issue by maddsua** [OdyseeTeam/odysee-frontend#2969]
**Is your feature request related to a problem? Please describe.**
When a video quality is set to it's minimum, you can clearly head the audio quality drop significantly too, to the point where it gets uncomfortable to listen to some videos.

**Describe the solution you'd like**
This does not happen on YouTube, and the audio stream is not that heavy anyway when the modern codecs are in use. I think that increasing the audio quality for 144/240p won't have any significant drawbacks in terms of performance or network load, but would benefit the listener experience. Or maybe add a listen-only mode to the player?

**Describe alternatives you've considered**
Well, YouTube does not have this problem. I'm sure they compress audio too, but it's barely noticeable if at all

**Comment by tzarebczan** [comment]
Can you provide some odysee link examples where this happens?

**Comment by maddsua** [comment]
Odysee link: https://odysee.com/@sea:1/collisions-of-the-early-solar-system-4k:4
YT link: https://www.youtube.com/watch?v=5cw0dO5RF-8

Simply set the quality to something low like 144p and compare the sound, Odysee feels a lot worse than youtube

**Comment by maddsua** [comment]
I get that not all the users only listen to videos, but a ton of creator are mostly talking anyway, and that's the way to still get entertained when let's say, you're driving somewhere and the internet connection is not great

**Comment by tzarebczan** [comment]
This should be live soon for newly transcoded videos. For older ones, there's not much we can do at this time. Thanks for pointing it out!

**Comment by maddsua** [comment]
> This should be live soon for newly transcoded videos. For older ones, there's not much we can do at this time. Thanks for pointing it out!

Sorry, did not see the reply earlier, thanks for the answer!
