### ISSUE TITLE
[feature] strip URL params on odysee side for api.na-backend.odysee.com

### ISSUE THREAD

**Issue by atomGit** [OdyseeTeam/odysee-frontend#2971]
**Is your feature request related to a problem? Please describe.**

here i'm using curl to attempt to find whether a video URL is valid (whether the video actually exists) on odysee.com by querying `api.na-backend.odysee.com`

in this case the JSON output correctly contains the text `"name": "NOT_FOUND"`:

`curl --header 'authority: api.na-backend.odysee.com' --header 'content-type: application/json-rpc' --data-raw '{"jsonrpc":"2.0","method":"resolve","params":{"urls":["@gonetothesnowdogs:d/no-video-here:5"]}}' --  'https://api.na-backend.odysee.com/api/v1/proxy?m=resolve'`

however if the URL contains a parameter (`@gonetothesnowdogs:d/no-video-here:5?param`), the result is not entirely expected:

`"error": "@gonetothesnowdogs:d/no-video-here:5?blah is not a valid url"`

**Describe the solution you'd like**

i would propose that it might be best if URL params were dealt with (ignored) on the odysee side rather than having to strip them beforehand

**Comment by tzarebczan** [comment]
We have a separate repo for the backend, but this issue probably won’t be tackled. That field is expecting an exact odysee or lbry url, which don’t have params natively. Best to do it on the client side before sending
