### ISSUE TITLE
Video: `m` to unmute not working completely

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#301]
1. Open a video page and play.
2. Pause it.  Mute it.
3. Refresh.  Click play if you had autoplay off.
    - The "Tap to unmute" should appear, and the volume icon should be crossed as usual.
    - [ ] Press `m`.  The audio is audible, but the "Tap to unmute" and crossed volume icon did not go away.

Sometimes, tapping "Tap to unmute" doesn't work, but I couldn't find a reliable step to reproduce.

**Comment by toshokanneko** [comment]
Fixed in my next PR. e1307cee83da005cc324cfc6d084e6ae63be4519
