### ISSUE TITLE
Freezes with a white screen on Android

### ISSUE THREAD

**Issue by es20490446e** [OdyseeTeam/odysee-frontend#3031]
Usually when I launch the app for the first time it just freezes with a white screen. It isn't till I close it and reopen it when it works properly.

- Odysee August 22, 2023
- Android 11
- Xiaomi Redmi Note 8T

**Comment by tzarebczan** [comment]
If you clear app data + uninstall and reinstall, is it any better then?

**Comment by tzarebczan** [comment]
Sounds good!

Another suggestion would be to try this APK vs the playstore version: https://apk.odysee.tv (requires removal of play store version)
