### ISSUE TITLE
Optimize backend calls (try to use non-auth and batching where possible)

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#306]
We use authenticated calls with include output / include purchase receipt to show ownership of content / purchase history. These also pass an x-auth-token. 

There's a few places where we can use unauthenticated calls, especially around comments/livestreams. 

We can also batch more resolves, mostly around comments, in more areas. These can be unauthenticated also. 

One example - when loading a livestream with hyperchats, the channels who tipped are resolved separately and authenticated. Can be batched and not auth. If you go to the full tip list, it batches, but doesn't need auth. 

Others:
- [ ] maybe if we know a channel we own is NOT in a claim search/resolve, don't use auth'd call
- [ ] batch search from search bar. Probably don't need to be auth'd.

**Comment by infinite-persistence** [comment]
Closed by #341
