### ISSUE TITLE
-media playback was aborted

### ISSUE THREAD

**Issue by elkaede** [OdyseeTeam/odysee-frontend#3139]
After a Few minutes of playback, it appears in some videos this message "The media playback was aborted due to a corruption problem or because the media used features your browser did not support."
![image](https://github.com/user-attachments/assets/c644e5d4-c5e4-44c7-b890-8091c4859a09)

I tried and it happens in edge, chrome and brave

**Comment by keikari** [comment]
Does that happen with all videos, or just some specific one?   
Can you share a link to some video with the issue?

**Comment by tzarebczan** [comment]
Closing this for now - please reach out to us at hello@odysee.com with more details on the above.
