### ISSUE TITLE
Download audio

### ISSUE THREAD

**Issue by patrickjohnson3** [OdyseeTeam/odysee-frontend#314]
If I'm viewing a video, I'd like for there to be an option after clicking ... to download the audio as an mp3.

![Screenshot_2021-11-17_13-28-47](https://user-images.githubusercontent.com/49662188/142263047-e1346008-4315-48dd-bbc5-77076657db7b.png)

**Comment by tzarebczan** [comment]
This is not possible at this time as there's no mp3 available and won't be for some time. We may transcode to audio in the future.

**Comment by patrickjohnson3** [comment]
Maybe ditch making it an automated process for now. Let the video author upload/attach the mp3 audio separately. If they did upload an mp3 then it would display Download Video followed by Download Audio.
