### ISSUE TITLE
Make Odysee livestreams end like other livestreams and add the video the channel's feed

### ISSUE THREAD

**Issue by myfirstnameispaul** [OdyseeTeam/odysee-frontend#3151]
**Is your feature request related to a problem? Please describe.**
Many livestreams never end and are "stuck" with the "@username isn't live right now, but the chat is! Check back later to watch the stream" message. I have messaged a couple of the livestreamers and they both told me that Odysee has some extra thing they have to do to end the livestream and then to make it appear in the regular feed.

**Describe the solution you'd like**
Add some additional option to make Odysee function the same as other sites function. Unfortunately, I am not familiar with livestreaming so I do not know the specific issue on the streamer side, but as a viewer I find this a very annoying problem that sends me away to other sites to view the content (which is readily available in the other sites' channel feed).

**Describe alternatives you've considered**
Not using Odysee for those livestreamers.

**Comment by tzarebczan** [comment]
Thanks for the issue Paul! How are you arriving on the livestreams that say it's not active - a link from the content creator elsewhere? 

It's up to the content creator to update the livestream with a replay if they'd like, or remove the livestream placehodler if it's no longer being used. 

We also support a use case where a creator may re-use the same placeholder and then publish the replays separately - hence we need to coninue having this page. 

You can email us more details at hello@odysee.com about the above.
