### ISSUE TITLE
Channel edit page placeholder doesn't hyperlink

### ISSUE THREAD

**Issue by rehandaphedar** [OdyseeTeam/odysee-frontend#3153]
**Bug**
Currently, the channel edit page has a placeholder for the website. Websites linked as per this placeholder (i.e. without `https://` will not be hyperlinked.

**To Reproduce**

1. Make a channel/Open an existing channel
2. Go to the edit channel page
3. Scroll down to "Contact -> Website"
4. Set a website similar to the placeholder (i.e. without `https://`)
5. Wait for changes to propagate
6. Open the channel page

**Expected behavior**
- The website should either be hyperlinked
- Or, the placeholder should include `https://` to better guide new users.

**Screenshots**
The placeholder:
![image](https://github.com/user-attachments/assets/c45ab1ca-410c-4f68-b4d8-ba51c581403a)

Example channel edit page:
![image](https://github.com/user-attachments/assets/b0b95fe0-3978-498b-a4c5-43c8489c4601)

Example channel page (Not hyperlinked):
![image](https://github.com/user-attachments/assets/107f3a73-5e86-491e-8801-6c347fd9cc10)

**System Configuration**
NA (Mostly irrelevant as this is not about the code)

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

**Additional context**
NA

**Comment by tzarebczan** [comment]
Thanks @rehandaphedar for the detailed issue. @keikari wanna take a quick shot at it? Can improve the placeholder + try to make old urls prepent https:// if it doesn't start with it.
