### ISSUE TITLE
Add IPv6 support for some Odysee FQDNs

### ISSUE THREAD

**Issue by ffrediani** [OdyseeTeam/odysee-frontend#3158]
Currently there is IPv6 support for Odysee CDN runs on FQDN **player.odycdn.com**, **thumbnails.odycdn.com** and **api.odysee.live** which is great as this is where most traffic flows to the users.

However there are some other FQDNs used by Odysse frontend that lack IPv6 support such as **odysee.com**, **watchman.na-backend.odysee.com**, **api.odysee.com**, **api.na-backend.odysee.com**, **sentry.odysee.tv**.

Having full IPv6 support makes it possible for connections with IPv6 support avoids having to pass trough CGNAT equipment which has been growing worldwide due to IPv4 exhaustion and improves user experience. CGNAT in certain cases may be an unnecessary bottleneck and can be easily avoided with IPv6 support.

Also full IPv6 support makes it more difficult for censorship scenarios due its characteristics compared to IPv4 and how people are used to block content.

Please check what is lacking for these FQDNs to have IPv6 support in order to enable it and have Odysee website to be able entirely on IPv6.

**Comment by tzarebczan** [comment]
Thanks for the report. Some of those backend services lack support for IPV6 and there are no plans currently to add it.

**Comment by ffrediani** [comment]
Hello @tzarebczan 
Why instead of closing the issue not come up with a plan to move stuff to other hosting services that have full IPv6 support ?

By closing it you indicate IPv6 has little significance and treats it as minor where in fact it does impact user experience.
Now a days not having IPv6 available is a bug has to be fixed, not a nice to have feature. In 2024 there are no more reasons at all for a service not have IPv6 support.

Isn't there anyone from the team that can look after and diz this issue ?

**Comment by tzarebczan** [comment]
Odysee is undergoing a larger transition in the future (see https://odysee.com/@Odysee:8/futureofodysee:e) which won't have this same limitation, and therefore we can't work on it at the moment. 

Majority of users still have ipv4 and have no problems accessing Odysee.

**Comment by ffrediani** [comment]
I can understand the limitations on what can be done thoughout this transitions, but justify that users have IPv4 and have the same access isn't something acceptable in this context really.

Hope this transition doesn't take that long and someone can take this one to fix. I can volunteer to put some extra hands in work to be done.

**Comment by UnderEu** [comment]
Is there any updates on this topic?

**Comment by ffrediani** [comment]
Unfortunately it doesn't even seem that IPv6 connectivity is understood entirely give the time it is sitting here and the missunderstanding above that IPv4 does the same.
