### ISSUE TITLE
Highlight chat message if your channel is mentioned

### ISSUE THREAD

**Issue by fluks** [OdyseeTeam/odysee-frontend#321]
**Is your feature request related to a problem? Please describe.**

You might not see that someone mentioned you in a chat message.

**Describe the solution you'd like**

Highlight the background of the message where you were mentioned.

**Describe alternatives you've considered**

\-

**Additional context**

\-

I can perhaps do this, since it's not difficult.

**Comment by tzarebczan** [comment]
Thanks for filing the suggestion, think it's a great idea!
