### ISSUE TITLE
Videos in the wrong positon

### ISSUE THREAD

**Issue by troler36** [OdyseeTeam/odysee-frontend#335]
**Bug**
Videos are shown in the wrong postion

**To Reproduce**
1. Go to 'Odysee.com'
2. Click on 'Video'
3. See error

**Expected behavior**
The video should be in a normal postion

**Screenshots**
![image](https://user-images.githubusercontent.com/39880578/142657765-defb2336-3db4-4428-96f7-d7cfa8ab88ba.png)

**System Configuration**

- Operating system: Linux troler-desktop 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Browser: Firefox 94.0 (64-bit)

**Note: all browsers have this bug**

**Comment by tzarebczan** [comment]
This will be fixed shortly, it's due to the bug at the top.
