### ISSUE TITLE
The site is inconvenient for people to use

### ISSUE THREAD

**Issue by KianBrose** [OdyseeTeam/odysee-frontend#338]
The thumbnails when searching for a video are way too small, it makes it really hard to see the thumbnail itself and important details/text. I think it wouldn't hurt to make each video widget 50-100% larger. On top of the fact that the thumbnail is tiny, the length of the video widget is MASSIVE when compared to the thumbnail which makes it even harder to see the thumbnail itself and hides a lot of details
![unknown (2)](https://user-images.githubusercontent.com/62078964/142705935-28e46633-82af-490b-9ceb-5bac55c3f189.png)
![unknown (1)](https://user-images.githubusercontent.com/62078964/142705940-dc1e4c32-cd81-42e4-af03-9f1cec390f9b.png)

In my opinion, thumbnails are essential to create a smooth & effortless watching experience since people tend to first see the thumbnail and then read the title, and since the thumbnail is so small you need to really tire yourself to see the details
![unknown (3)](https://user-images.githubusercontent.com/62078964/142706039-f316a85c-9cfe-4479-8139-4045cee93ad4.png)
The amount of effort that needs to be spent on actually choosing what to watch is considerably higher which leads to people leaving the site

Furthermore, I think pushing for a 6 video / line grid is very excessive on the home page and overloads the users with way too many choices, it's simply too cluttered
![unknown (4)](https://user-images.githubusercontent.com/62078964/142706134-4f113e22-88a0-4bf1-8613-f91da51b7efe.png)

Here's a quick mockup I made which I think is better (although it still needs a lot of work), but I hope it gets the point across
![unknown (5)](https://user-images.githubusercontent.com/62078964/142706166-a1e4361e-99c1-427f-a9dc-f95af89a04a0.png)

I really hope the site can improve so it's not a pain to use in terms of usability when compared to youtube

**Comment by tzarebczan** [comment]
Thanks for the feedback, we'll continue to improve on the design. Adding an option for the full thumbnails on the search page is a good idea, we'll add that as a separate issue.
