### ISSUE TITLE
Ad position is odd in `medium` layout

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#363]
![image](https://user-images.githubusercontent.com/64950861/143262670-13d23b0a-d4b1-4bd2-9565-66e5907e2738.png)

**Comment by tzarebczan** [comment]
The ad is meant to stay on screen, and it's external JS code, so don't think we have control over it. We can ask them to move over to the right maybe.

**Comment by mayeaux** [comment]
@infinite-persistence do you mean that it's cut off a bit on the left-hand side?

**Comment by infinite-persistence** [comment]
### Close
Didn't know it was supposed to float at the time of submission.
Aligning it somewhere else (like what Tom mentioned) might be nice, since left side typically has more data like title and description, but it's still annoying regardless where it is, so closing for now.
