### ISSUE TITLE
Enable to remove "Please Do Not Spam" on my channel's comments.

### ISSUE THREAD

**Issue by JYamihud** [OdyseeTeam/odysee-frontend#367]
I know the reason for the latest implementation of the comments "Please Do Not Spam" message, when people either type too much, or put a link to another odysee publication. But, there is a problem.

If you scroll down on [any of the articles in @blenderdumbass:f](https://odysee.com/@blenderdumbass:f/the-main-misconception-about-free-software:b) you will find a section like this:

![image](https://user-images.githubusercontent.com/27649397/143458552-e89c283b-2318-4c7e-948d-799e77237410.png)

This is an auto generated part, using a script, that looks at latest supported comments and shows them in the text of the article.

Sometimes, like for example here:

![image](https://user-images.githubusercontent.com/27649397/143458844-4722c1a8-7496-4e40-8bfb-b21809b98e4f.png)

...the person is linking another odysee ( LBRY ) publication. And I want it to be possible. It's basically an ads system that's totally decentralised. The script is Free Software and I link to it on each article, you can use it too.

# The problem

To avoid malicious spamming, you also removed legit linking of other interesting publications.

# The solution

Make a setting somewhere in the Channel settings, that will set a minimum support amount for commenting links. Spammers will have to pay to spam, so they will not do it. Legit advertises, though, will be able to advertise their things through my articles.

**Comment by troler36** [comment]
I think this is a great idea

**Comment by tzarebczan** [comment]
The spam message is shown when you post the same thing over and over on a single claim. If someone tips with it, i don't think it counts as spam. 

Does that sound right in terms of what is being posted? Let me know and we'll open the issue on the comment repo if needed.

**Comment by JYamihud** [comment]
I just tried posting a 5 lbc supported comment with a link on a publication. It had a link to one of my articles. Though, something during posting happened that might explain your take on it. I tried adding a sticker. And it posted a sticker as a comment, returning me to the text that I typed earlier. I tried posting the text and it kept repeating the same error. Until I posted it with FastLBRY without a support. ( Because FastLBRY does not support supported comments yet ).

[This is the publication](https://odysee.com/@tech-pixels:0/how-to-make-apng-and-avif:8). Funny that the sticker was posted twice for some reason. Once with a support and one without. Which is also a bug, I guess.

**Comment by Dunravin** [comment]
I just got this "please do not spam" pop up and I wasn't even typing too much or linking anything. I was pointing out the channel was promoting scam windows 10 pro keys with discount codes and referral links. Is odysee going full retard? Expect so.
