### ISSUE TITLE
Chrome has a issue with font-weight and changes emoji to glyphs

### ISSUE THREAD

**Issue by Abwasserrohr** [OdyseeTeam/odysee-frontend#369]
**Is your feature request related to a problem? Please describe.**
Some videos that have emojis have this black emoji instead of the system default ones. This is not bad, but the videos would look more inviting and also feel more home with the already known ones that the system uses by default. Sometimes, this already is the way it is, but for some emoji, it's not.

**Describe the solution you'd like**
It would be great if the default emojis are forced instead of the glyphs Chrome is using. 

The problem is caused by a recent update in Chrome:
`h2.claim-tile__title`: `font-weight: 600;`

I have seen that there is a [tutorial on how to fix this](https://dev.to/cartman720/simple-solution-for-the-recent-chrome-emoji-font-weight-issue-2lgf), I also don't know if Chromium will keep it this way or not.

![21lö](https://user-images.githubusercontent.com/44294954/143470376-4f07f0a3-8c3f-40c2-bc02-0a66b6fbef5a.png)

**Comment by tzarebczan** [comment]
This is happening for me on other sites, not only Odysee. Seems like chrome must have broken something recently.

**Comment by Abwasserrohr** [comment]
Yeah, I'm wondering if this is intended or how it will be from now on... 😅

**Comment by Abwasserrohr** [comment]
Seems to be fixed again.
