### ISSUE TITLE
Sync YouTube subscriptions over to Odysee automatically

### ISSUE THREAD

**Issue by Abwasserrohr** [OdyseeTeam/odysee-frontend#371]
**Is your feature request related to a problem? Please describe.**
I have seen some people in the comments on Odysee that they like Odysee itself, but they can't find videos from creators they like on Odysee. 

Using the [API](https://developers.google.com/youtube/v3/docs/subscriptions/list), it would be possible to allow users to move over all their YouTube subscriptions to Odysee with one click. I know, not every creator is on Odysee, but this could still be pretty good for people that are coming over and have subscribed to channels that are actually on Odysee.

This [addon](https://chrome.google.com/webstore/detail/watch-on-odysee/kofmhmemalhemmpkfjhjfkkhifonoann) already can do it, so maybe it's not even required to implement it into Odysee itself, but just link to it somewhere in the settings to let people know that this is a possible way, or is this already a thing and I have just missed it? 😅

**Comment by tzarebczan** [comment]
We don't plan to support this because we can't authenticate every single YouTube user, we have a limit on our API. This API works only with the user's key, and not ours, so they'd need to sign up for API access.

**Comment by Abwasserrohr** [comment]
Oh I see, then that's not possible I guess.
