### ISSUE TITLE
Please add TOTP (google authenticator/authy) 2 Factor Athentication

### ISSUE THREAD

**Issue by gamerseye123** [OdyseeTeam/odysee-frontend#374]
please add totp 2fa. i want my odysee account to be more secure. its pretty easy to implement so just do it.

thanks.

**Comment by tzarebczan** [comment]
This is coming in a few months, being worked in an internal repo

**Comment by Killercat103** [comment]
> This is coming in a few months, being worked in an internal repo

@tzarebczan, any updates regarding this?
