### ISSUE TITLE
Spammers still can bypass the filter somehow

### ISSUE THREAD

**Issue by Abwasserrohr** [OdyseeTeam/odysee-frontend#381]
I did open a similar issue (#266) a while ago and it seemed that it's been solved, but now the spammers are appearing again with the same links as before. I'm not really sure how they bypass the filter, maybe by editing posts?

Example comment (netpro is on my list too): https://odysee.com/@skyrift:2/barnyard-idea-minecraft-timelapse-2:9?lc=6ff9f44c7415d3746358bd0da3f094c17f074687083d50972a1076dfe27f5d1a

![](https://user-images.githubusercontent.com/44294954/141178162-1686c1a2-c74e-48e9-952a-e3fe5f21a181.png)

**Comment by tzarebczan** [comment]
Thanks, we're working on this  with another repo.

**Comment by tiger5226** [comment]
hmm, they bypassed it with case sensitivity. https://github.com/OdyseeTeam/commentron/issues/94
