### ISSUE TITLE
keep odysee open source

### ISSUE THREAD

**Issue by gamerseye123** [OdyseeTeam/odysee-frontend#383]
in a letter, it says "Odysee has chosen to continue to release code in an open-source fashion. However, Odysee is not bound to do this, and does not promise to do this." 

please keep odysee open source. if you dont, odysee will just become another youtube. the reason i switched to odysee was for privacy. close-sourcing it will make it good as compromised. it will become another youtube, with all the problems with it except you lied to us about the features odysee has.

you already are in hot water with the foss community. so please, for the love of Stallman, switch to the gpl licence and keep odysee open source.

**Comment by tzarebczan** [comment]
Thanks for the feedback, we don't have any plans to not being open source at this time.

**Comment by gamerseye123** [comment]
i mean to keep it foss forever, i know it is right now.

**Comment by mueenulit** [comment]
Odysee should remain open source forever ♾️ ... We are here to Support Odysee 💕
