### ISSUE TITLE
"Reload site?"-dialog loops, when signing out while having active uploads(On Chrome)

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/odysee-frontend#419]
**Bug**
"Reload site?"-dialog loops, when signing out while having active uploads.
Happens on Chrome.
Doesn't happen on Firefox.

**To Reproduce**
On Chrome
1.  Have an active upload 
2.  Click "Sign out"
3.  On "Reload site?"-pop-up, clicking anything makes pop-up to loop, and browser will be stuck in it.  
Checking "Prevent this page from creating additional dialogs" will let one continue.

Seems to only happen when signing out.
(Few times loop "broke" after few clicks.)

**Comment by tzarebczan** [comment]
@keikari does this still happen?

**Comment by infinite-persistence** [comment]
It does

**Comment by infinite-persistence** [comment]
It does.  A chicken-and-egg problem in `doSignOut` between the `reload` call and the `beforeunload` handler.
Might need to make the publish list not use `beforeunload`.  Not sure what's the best solution.
