### ISSUE TITLE
New video  in a channel - unseen dot

### ISSUE THREAD

**Issue by hermann-san** [OdyseeTeam/odysee-frontend#421]
**Is your feature request related to a problem? Please describe.**
My problem is that I have many channels I've subscribed to and in the "subscribed channels" list I do get a list of all video's of all channels. However, I'm used to watch unseen/unread video's from channels that I'm in the mood of watching. So I would look at my channel list and say, there is a new video from channel XYZ  and I would like to see a new video from that channel.  This is hard to do via "subscribed channels" if there are many new video's. 

**Describe the solution you'd like**
In the menu bar (reachable via the menu button/3 lines), there is a list of my subscribed channels.
I would be nice if there would be a "unread" dot next to the channel name. That would be sufficient for me to know that there is a new video available from this channel.  Once I've visited the channel, the "unread" or "unseen" dot can disappear.

**Describe alternatives you've considered**
I would have to check each channel manually and not knowing if there is a new video or not. 
Using the "subscribed channel" page doesn't show me specifically unseen video's. It's not practical with many subscribed channels
I don't like notifications. I rare case I use notifications for very important channels, but for most of the channels I prefer to visit them when I'm in the mood to do that. Also, some channels are uploading video's every day and fill up my notification list and suppress more important video's.

**Additional context**

In the below mock up example, the @lbry channel would have a new, unseen video - indicated by the blue dot. 
![grafik](https://user-images.githubusercontent.com/7679654/144691517-3503d53d-285a-46b8-a24c-78ba0e8c556c.png)

**Comment by tzarebczan** [comment]
Thanks for the feedback. We have a separate issue filed for watch history tracking, so after that's done, we can consider something similar to this. 

For now, your following page would be the best place to track latest videos.
