### ISSUE TITLE
Allow Original video quality to be selected

### ISSUE THREAD

**Issue by Abwasserrohr** [OdyseeTeam/odysee-frontend#422]
The original video is stored, but after encoding, it will no longer be available. Some videos look not good after encoding, I get it that the files are getting large quickly and transcoding should take care of it, but some 1080p videos are looking better on 480p YouTube.

I think it would be great to have at least the option to view the original size if a user want it, even if it will buffer because of limitations.

1080p on Odysee:
![encoding-quality](https://user-images.githubusercontent.com/44294954/144716898-dc404d6e-3e31-46d3-93ca-15fbedcd7b4c.png)

**Comment by tzarebczan** [comment]
It's not possible, but we will be improving the transcoded quality of the original format. Coming in the next few weeks
