### ISSUE TITLE
Latent space based weighted recommendations

### ISSUE THREAD

**Issue by Aras14HD** [OdyseeTeam/odysee-frontend#424]
**Is your feature request related to a problem? Please describe.**
YouTube's recommendation algorithm is still a lot better than Odysee's

**Describe the solution you'd like**
One option would be the following:
An AI would be trained to embed a video in a latent space (Video, description, Channel -> point in latent space)
Each user would save a few latent space points based on the watch history (for when the user is not already watching a video)
The videos would first be weighted based on how well they perform and user feedback.

When videos are recommended videos are additionally weighted in the following ways:
1. Distance (not linear maybe using bell curve)
2. Direction: the vectors of the previous videos to the videos watched next are weighted (newer more than older), combined and normalised (amplitude mapped to a smaller scale) the videos in the direction of the verctor are weighted more, the spread inversely depends on the amplitude (higher amplitude less spread)
3. Bubble pull correction: when on the edge of a bubble (place with a lot of similar videos) Videos inside the bubble are recommended more often tan ones outside, this can lead to radicalisation. To account for this, videos in a video sparse place have to be weighted more than videos in a video dense place.

Then videos are randomly selected (if a video is already currently in the recommended it will not be added a second time) partly based on the video and partly based on their saved points representing their interest.

**Comment by tzarebczan** [comment]
Appreciate the issue and feedback! We are actively working on a recommender system that will be personalized to users. Probably still a few weeks away.
