### ISSUE TITLE
Parse platform instead of Firebase on push notifications in a long run?

### ISSUE THREAD

**Issue by iamflorencejay** [OdyseeTeam/odysee-frontend#425]
**Describe the solution you'd like**
I've seen a firebase alternative that is self-hostable (on npm or yarn) and build an entire server via docker or node.js. It is called Parse. It is a well known, maintained by the community, open source application stack that will help for a long term if they **want to do it.** It is a well documented, dockerized and with a dashboard to crush this when it's necessary.

**Additional context**
Website - https://parseplatform.org/

**Comment by tzarebczan** [comment]
We don't plan to do this as we are using firebase in other apps already.
