### ISSUE TITLE
Mui: "Make sure you have customized the input component correctly"

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#464]
Happens every time we enter a claim page on debug

![image](https://user-images.githubusercontent.com/64950861/145520556-989281b2-dc13-48a3-8c1c-79a3e081d1a6.png)

**Comment by saltrafael** [comment]
https://github.com/mui-org/material-ui/issues/28687

**Comment by infinite-persistence** [comment]
`--Re-open--`
lol, I linked the wrong issue in 466
