### ISSUE TITLE
Don't dispose of video player on each new video

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#483]
Today we dispose and re-create the video player on each new video, instead of just switching sources. This is wasteful and causes issues for chromecast playback when switching between videos.

**Comment by mayeaux** [comment]
Can close this one too, https://github.com/OdyseeTeam/odysee-frontend/issues/484 is still 'in the works' I will try and get the work done for KP today so that switching between livestreams/videos doesn't require a dispose
