### ISSUE TITLE
Can't open app on Samsung Galaxy S20

### ISSUE THREAD

**Issue by calvinomiguel** [OdyseeTeam/odysee-frontend#487]
**Bug**
The app isn't opening on Samsung S20. I am using the Version 0.0.11 of the Odysee app. Following are the Phone details:
Model name: Galaxy S20
Model number: SM-G980F/DS
One UI version: 3.1
Android version: 11
Kernel version: 4.19.87-22520152

**To Reproduce**
1. Go to phone's home screen
2. Click on the Odysee app icon
3. App opens with dark screen, just to crash 2 seconds later

**Expected behavior**
I expected to see a splash screen with the Odysee logo. After loading I should enter the app and be able to interact with the UI. However I can't even open the app, as it always crashing.

**Screenshots**
I have no screenshots

**Comment by tzarebczan** [comment]
Which app are you referring to? Did you install the APK for Odysee or the Odysee web app installed via a browser? Try removing and re-adding the PWA app if so.
