### ISSUE TITLE
Warning on `auth_token`

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#491]
![image](https://user-images.githubusercontent.com/64950861/145995077-44a13b2d-754a-41f4-abee-cdb22992ab5d.png)

https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

**Comment by tzarebczan** [comment]
I think FF is just confused, see my original comments here: https://github.com/lbryio/lbry-desktop/issues/6845 (closing)
