### ISSUE TITLE
Show thumbail on downloadable content (non-playable/post)

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#503]
Right now we only show the download button and no thumbnail

Some users/creators would want to see the thumbnail associated with the download. This section can be collapsible/persisted for those that may not want to see it.

**Comment by tzarebczan** [comment]
@keikari wanna take a shot at this? Someone requested on Twitter.

**Comment by keikari** [comment]
Shot something. Is the collapsible part necessary? Images in the PR

**Comment by tzarebczan** [comment]
Should be fine without it, awesome! 

Maybe a hover on the thumbnail for download also? We can add that later too.
