### ISSUE TITLE
Can't remove deleted claim from Watch Later

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#510]
The owner deleted the claim, and seems like there's no way in the GUI to remove it from me list:

![image](https://user-images.githubusercontent.com/64950861/146330562-d0db9fe1-d2e2-4d43-be37-284add4ae500.png)

![image](https://user-images.githubusercontent.com/64950861/146330667-6330964d-fac6-4afd-b61c-957c96d11c11.png)

**Comment by tzarebczan** [comment]
It's on the desktop side too as it affects that one, just FYI..fine to leave in both. https://github.com/lbryio/lbry-desktop/issues/6699
