### ISSUE TITLE
Report CDN issues

### ISSUE THREAD

**Issue by robd003** [OdyseeTeam/odysee-frontend#538]
**Is your feature request related to a problem? Please describe.**
It would be great if there was a way to report issues with the CDN. I've had issues with recently published videos (24 hours old, ~1,500 views) that get stuck buffering every other second. Essentially the issue is [buffer underrun](https://en.wikipedia.org/wiki/Buffer_underrun) where the CDN can't deliver content to the browser fast enough.

**Describe the solution you'd like**
Either an automated way to report buffering problems or a manual "report low streaming quality" button.

**Describe alternatives you've considered**
The only way I've been able to resolve this is by using lbry-desktop instead of Odysee.
Another idea would be allowing Odysee.com users to "connect to a LBRY instance" on their own network and take advantage of the P2P network for streaming content.

Another idea is somehow dynamically increasing the rate limit set by the Caddy server if the client is experiencing buffering issues.

**Additional context**

**Comment by robd003** [comment]
Just looked at https://github.com/OdyseeTeam/odysee-api/tree/master/apps/watchman and it looks like you guys already record buffering issues.

It'd still be awesome to be able to use Odysee but rely on the P2P network (via a users own LBRY instance running somewhere) and not be stuck with the CDN servers only.

**Comment by tzarebczan** [comment]
Thanks for the feedback Rob. We don't use a CDN for content delivery, we've built our own. With the recent growth, we've got some beefing up to do and hope to have some improvements in later this week. 

At this time, we don't plan on using connections outside the centralized odysee services, but may in the future.

**Comment by robd003** [comment]
@tzarebczan is there any way that users could run their own streaming servers to help boost the Odysee service?

**Comment by tzarebczan** [comment]
Nope, not at this time, sorry.
