### ISSUE TITLE
Header fallout

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#550]
- [x] Component overlap still happening
    - ![image](https://user-images.githubusercontent.com/64950861/147017949-eb56cddb-4258-4e84-9447-51649ea55412.png)

**Comment by tzarebczan** [comment]
- [ ] Odysee logo disappears on some pages like https://odysee.com/@OdyseeHelp:b/uploadguide:1 - may take a couple seconds.

**Comment by infinite-persistence** [comment]
- [ ] Avatar transparent background is broken in dark mode
    - ![image](https://user-images.githubusercontent.com/64950861/147060807-76a91172-bed2-47fc-bed3-86a9a04a19d9.png)
    - ![image](https://user-images.githubusercontent.com/64950861/147060972-2eafd1fc-0093-4789-a768-582300fddccd.png)
    - ![image](https://user-images.githubusercontent.com/64950861/147061239-0a003213-1776-48d5-9398-b622c77a2674.png)
