### ISSUE TITLE
Submit button becomes grayed-out if editing the channel name after uploading the cover image and the preview text has appeared.

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/odysee-frontend#568]
1. Upload cover image
2. Wait for the "Uploaded image will be visible....." text
3. Type something in the name-field
4. Submit button becomes un-clickable

![grayed-out](https://user-images.githubusercontent.com/34790748/147512291-ccb0bc82-ee94-496b-af98-b6521ef457f8.png)

**Comment by tzarebczan** [comment]
If you type the name first, does it work then? Or if there's a title maybe?

**Comment by keikari** [comment]
Typing name first kind of works, but editing it will still disable the "Submit" button, when the "Uploaded image will be visisble...." image is there.
Text in title and description doesn't seem to make difference.

If the uploaded image shows instead, then issue doesn't happen.
