### ISSUE TITLE
Slow appearance of tiles

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#572]
This is a known (discussed) issue, filing before forget.

- Previous: show placeholder tiles asap (for LCP score) + do `claim_search` asap
- Current:  delay all of the above until livestream data is fetched

https://user-images.githubusercontent.com/64950861/147619813-b574de86-6380-435c-b1fc-a08d8d60081f.mp4

**Comment by infinite-persistence** [comment]
Oddly, I don't see the delay from Tom's screen during the meeting ...
Region-dependent I guess ... the delay is getting annoying.

**Comment by saltrafael** [comment]
I see it too from here

**Comment by infinite-persistence** [comment]
Ah, good to know it's not just my end.

It's also moving ads to the first tile:

<img src="https://user-images.githubusercontent.com/64950861/147796034-816e79b4-be85-4d83-806e-fe0d5df98f39.png" width="300">
