### ISSUE TITLE
Deleting some claims from channel's page doesn't work. "No associated support or claim with txid:"

### ISSUE THREAD

**Issue by keikari** [OdyseeTeam/odysee-frontend#577]
**Bug**
User reported that deleting publishes doesn't work. 

Trying to delete publishes or repost from the channel page doesn't happen when clicking "Ok" in the confirmation dialog. Only prints an error to the console.   
Doesn't seem to affect new(?) uploads.   
Deleting same claim using option under the video player works.  

**To Reproduce**
1. Go to channel page which has your publishes
2. Click on 3-dot menu -> Delete, in one of the publishes
3. Clicking "ok" seemingly does nothing, and error in screenshot appears in console.

**Screenshots**
![deleting-error](https://user-images.githubusercontent.com/34790748/147649015-93ba2c54-54c1-4e9b-894e-6de63e38453f.png)
txid: a28158f40f8e784b74a6d958b2ead259d3820c042512ff35db5be3a664d80f06

--------------------------
Not related to the issue, but does Odysee need the "Delete publish from the blockchain" check box?

**Comment by tzarebczan** [comment]
Dup of https://github.com/OdyseeTeam/odysee-frontend/issues/548, should get fixed soon
