### ISSUE TITLE
Don't animate sidebar unless transitioning a page?

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#594]
There are a few scenarios where you will see the Sidebar animate out unexpectedly.  Most notable is in Firefox Android when opening odysee.com (maybe need Incognito) ...  I see the Sidebar flash and slowly animate out.

I think the animation is only needed for:
- Explicitly changing sidebar state from pinned to minimized
- From a page with sidebar pinned, enter a File Page (where sidebar cannot be pinned).

**Comment by tzarebczan** [comment]
Hey @MaxKotlan, maybe this one would be up your sleeve. I notice this most on Firefox android also. No rush though!

**Comment by MaxKotlan** [comment]
Sure, I'd be happy to take a look at that. I can reproduce the issue on mobile too. I'll see what I can do to fix it.
