### ISSUE TITLE
Add pagination support to channel search

### ISSUE THREAD

**Issue by Abwasserrohr** [OdyseeTeam/odysee-frontend#605]
**Bug**
Sorry, if this is something that you guys are aware of.
Searching something on the channel page calls https://lighthouse.odysee.com, for example, if I want to search for `Mario` on [this](https://odysee.com/@GermanLetsPlay:6) channel, the site is going to call `https://lighthouse.odysee.com/search?s=Mario&channel_id=68470c7c5d53f24f4a8b6ecd9fad56f201cb21e8&nsfw=false&size=50&from=0`, but if I scroll down, instead of using `https://lighthouse.odysee.com`, it uses `https://api.na-backend.odysee.com/api/v1/proxy?m=claim_search`, which just loads more videos on the channel page outside of the search.

**To Reproduce**
1. Go to https://odysee.com/@GermanLetsPlay:6
2. Search for `Mario` on the channel search
3. Scroll down until more content should be loaded
4. No results for the channel search page are loaded, just more entries for the channel that are not displayed in the channel search page.

**Expected behavior**
The trigger for loading more channel contents should be disabled in the search area and replaced with a trigger for the search page, I think.

**Video**

https://user-images.githubusercontent.com/44294954/147853746-ed1dfb2b-b627-463d-a7a7-c0369b86cd6c.mp4

**System**
Logged in, latest version of Chrome

**Comment by tzarebczan** [comment]
Thanks for filing! I believe lighthouse does support pagination, so we can grab latter pages if they exist in this mode.

**Comment by tzarebczan** [comment]
The from + size parameters would allow for pagination.

Example: https://lighthouse.odysee.com/search?s=cosmology&size=20&from=0&nsfw=false&free_only=true
