### ISSUE TITLE
History Tab

### ISSUE THREAD

**Issue by OliverBrotchie** [OdyseeTeam/odysee-frontend#606]
**Is your feature request related to a problem? Please describe.**
A common usage pattern of consuming long content on YouTube is to come back to unfinished videos via the history tab. As far as I could tell, there is no "history" feature on Odysee despite videos resuming at your previous position.

**Describe the solution you'd like**
A history tab located in the sidebar where recently watched videos are cached locally.

**Describe alternatives you've considered**
It could also be located in the account drop-down as the sidebar is already quite cluttered for mobile users.

**Comment by tzarebczan** [comment]
Thank you! This would be handled under the work for https://github.com/OdyseeTeam/odysee-frontend/issues/168

**Comment by OliverBrotchie** [comment]
> Thank you! This would be handled under the work for #168

Great! Has there been any progress on this or is it an open issue that someone could contribute to?

**Comment by tzarebczan** [comment]
It requires some backend work before we hook things up, but some front end work to style / save progress locally would be up for the taking.
