### ISSUE TITLE
Add GIF support

### ISSUE THREAD

**Issue by troler36** [OdyseeTeam/odysee-frontend#639]
It would benefit Odysee if GIF support was added. Although it already existed and there were no complains of it's existence. Removal of GIFs has caused issues for those channels who relied on GIFs to create higher quality thumbnails.

If somehow Odysee doesn't want to have a feature that can be used as an argument for YouTubers to join Odysee. It would be appropriate if a reason of why such integral part of Odysee was removed.

**Comment by tzarebczan** [comment]
GIFs should still work , but there may be some issues with some files. Shoot me an email at tom@odysee.com with the gif you were trying. 

We are also going to add a size limit to GIFs...we can't be loading 10MB+ gifs on various pages.

**Comment by tzarebczan** [comment]
Right now the limit is 2MB but we may increase this in the future.
