### ISSUE TITLE
Opening the direct link to the YouTube sync page is not translating the site

### ISSUE THREAD

**Issue by Abwasserrohr** [OdyseeTeam/odysee-frontend#654]
**Bug**
If I open the link to https://odysee.com/$/youtube?reset_scroll=youtube, it shows me the English version of the page until I close that sync page window, even if I have set Odysee to another language.

**To Reproduce**
1. Set odysee.com to German
2. Visit https://odysee.com/$/youtube?reset_scroll=youtube
3. The site should be in German, but it is in English

**System Configuration**
Logged in, latest version of Chrome

**Comment by tzarebczan** [comment]
Can you see if this is still happening? We recently made some improvements to translation loading.

**Comment by Abwasserrohr** [comment]
It's fixed now. 👍
