### ISSUE TITLE
"Take a snapshot from your video" controls off-screen

### ISSUE THREAD

**Issue by frankhuurman** [OdyseeTeam/odysee-frontend#655]
**Bug**
When I want to add a thumbnail from video by clicking "Take a snapshot from your video" the modal that pops up has no controls to actually use a thumbnail. Controls seem to be off-screen and unusable.

**To Reproduce**
1. Be logged into Odysee with an account
2. Go to https://odysee.com/$/upload in a browser(I'm using Brave for example)
3. Add a video file with Browse
4. Scroll down to the Thumbnail section and click "Take a snapshot from your video"
5. The screen that pops up to select a thumbnail doesn't have controls to choose a thumbnail on it and seems zoomed in.

**Expected behavior**
I expected the popped up modal to be zoomed out a bit more so it doesn't overflow on the page and to have a button to select the thumbnail I want to use.

**Screenshots**
Below is after clicking on "Take a snapshot from your video":
![image](https://user-images.githubusercontent.com/19980966/148691992-79ffdae6-0d11-401a-99a6-aaba11e95f5b.png)

**System Configuration**

- LBRY Daemon version: Can't find it in the browser
- LBRY App version: Just visiting in my Brave browser version 1.34.80 Chromium: 97.0.4692.71
- LBRY Installation ID: Can't find it in the browser
- Operating system: Windows 10 Home 21H2

**Comment by tzarebczan** [comment]
Hey @frankhuurman , thanks for filing this. Are you using a portrait video as the source? My guess is that these won't work well for thumbnail purposes regardless, but we should get this looked into.

**Comment by tzarebczan** [comment]
Yea looks like it's related to portrait: https://github.com/lbryio/lbry-desktop/issues/6709
