### ISSUE TITLE
"Creative Arts" OG metadata

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#679]
- [x] Update `constants/pages.js` -- needed for page titles lookup.
- [x] Update `constants/pageTitles.js` -- needed so that the tab title says the category name.
- [x] Localize title strings -- needed so that sidebar changes per language.
- [ ] Update `web/src/category-metadata.js` -- needed so that we have the proper OG.  Requires image, though.
- [x] Update sitemap -- guides Google to show categories in search results.

**Comment by tzarebczan** [comment]
@dejanbr to work on this.
