### ISSUE TITLE
Embedded videos do not show play button

### ISSUE THREAD

**Issue by dhyanan73** [OdyseeTeam/odysee-frontend#689]
Embedded videos do not show play button.

**Comment by tzarebczan** [comment]
Can you give us an example of a link and what browser was being used? Tried one quickly and it seems to work here.

**Comment by dhyanan73** [comment]
> Can you give us an example of a link and what browser was being used? Tried one quickly and it seems to work here.

Firefox and Chrome. Maybe issue is just for audio content, not for videos. Here an example: https://bacheca.scienzacoscienza.com/complotti-misteri/bruno-mautone-morte-rino-gaetano/

**Comment by tzarebczan** [comment]
Yep, that must be it! @mayeaux take a look sometime to see why the play button would not show on audio.

**Comment by myfirstnameispaul** [comment]
It's actually there in the upper left corner, at least on FF desktop.

**Comment by dhyanan73** [comment]
> It's actually there in the upper left corner, at least on FF desktop.

This is not ok. It must be shown at the center.

**Comment by myfirstnameispaul** [comment]
Yes, I was just posting to better define the bug, not suggest it is acceptable (it's actually really hard to see without hovering over it with the mouse).
