### ISSUE TITLE
Newly posted creator videos days-old and deep in feed.

### ISSUE THREAD

**Issue by myfirstnameispaul** [OdyseeTeam/odysee-frontend#707]
**Bug**
A brand-new video from a creator appears days-old in my feed and I never see it without searching for it, directly viewing the channel, or enabling notifications.

**To Reproduce**
As best I can tell, this is related to dates in YouTube for live streams based on using YouTube RSS feed times.
1. Review datestamps on RSS schedule of YouTube channel.
2. Look at datestamps on video of actual livestream - can be days or more later.
3. Look at sync'd Odysee channel datestamps
4. Odysee channel datestamps match YouTube RSS feed times for date scheduled, not livestream date.

**Expected behavior**
Odysee video datestamp match datestamp of actual live stream.

**Notes**
Enabling notifications is not a good solution because not every video from a channel is scheduled livestreams, causing superfluous notifications resulting in ignored notifications and notifications list too long to be useful.

One simple solution is allow creators to repost a video. I have a tiny channel and the repost option for channel videos doesn't seem available.

Alternatively, don't use RSS datestamps.

**Comment by tzarebczan** [comment]
We recently fixed this for newer streams. Shoot us an email at hello@odysee.com if it continues to happen with specific examples. 

YouTube may take longer to process longer streams also, so those will be a bit delayed, but we'd rather still keep the original dates.
