### ISSUE TITLE
CPU at idle is high after displaying comments

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#72]
https://odysee.com/@Odysee:8/How-To-Stop-Misinformation:5 (load full layout)

After things settle, CPU usage is at 0.1%, which is good:
![image](https://user-images.githubusercontent.com/64950861/137268123-46925ee5-4fcb-4b5a-8e99-570e0c1377b7.png)

Scroll down to load 2 pages of comments, wait a while to let things settle.  CPU hovers at 10% (not good):
![image](https://user-images.githubusercontent.com/64950861/137268380-ebf1ec4b-d179-4169-8e3b-17f29f7d4c8a.png)
I thought it was due to to the perpetual spinner off-screen that's causing this, but ....

Load like 5-6 more pages of comments and let it settle.  CPU hovers at 30%.  I think there's only 1 spinner, so the guess might be wrong.
![image](https://user-images.githubusercontent.com/64950861/137268708-fa15ddd8-84a4-47e7-a41b-7ad9a8475e37.png)

Load all comments.  CPU hovers at 3% (not good, expecting back to 0% since spinner is gone).
![image](https://user-images.githubusercontent.com/64950861/137268875-28de2579-0cbf-4550-8687-de995fc1290c.png)

----

Profiler shows a bunch of animation frames from ReachUI, but can't tell from which component (or at least I'm not sure how).  We use Reach for tooltip and context menu, among other things.

![10-percent-cpu](https://user-images.githubusercontent.com/64950861/137270769-a63bfcfe-e5df-470c-b3eb-8aaf6d63b21c.png)

**Comment by tzarebczan** [comment]
@infinite-persistence can you confirm this is fixed? Reopen if not.
