### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by TheKylerKey** [OdyseeTeam/odysee-frontend#723]
In the future on Odysee do you think there will be a list of music/video clips you can choose from to play in the background of a video and pay a relatively a small amount/royalties to the creator of said music/clip?

It is a concept that intrigues me.

The idea is similar to how Tik Tok provides sounds and clips to its end users, only the difference is it is providing royalties to the original creator automatically from the user side.

Basically I would love to create music videos using using other peoples content, but I  just don't have a great way to doing it, because it's really hard to get a hold of whoever actually made it in a timely manner and I refuse to freeboot their content.

Essentially I see it as a way to mitigate free booting while still allowing freedom of expression.  It wouldn't eliminate freebooting by any means. But then they wouldn’t have a source to the clips they’re posting and would be obvious. 

Idk just food for thought. I’m sure this would be extremely difficult to implement code wise, but could be quite lucrative if done correctly.  Then you would also have a list of videos that used said clip.  Similar to a hashtag.  And could be an interesting way to consume content and may draw people in.

The idea is you have a list of content that is setup and deemed usable by the creator.  Then anyone can use it in a video or live stream for a small amount of LBC.  Depending on how it is setup potentially that person could also get royalties from the profits of that channel that posted it.  Something along those lines.

To further define the terminology.  Freebooting  Reposting someone else's content for your personal gain, without the creator's permission. Stealing views that would have otherwise gone to the creator.

The way I see it there is potentially a better way now, since there is essentially a ledger of who actually created the content, you can use this information to rightfully provide back to the original creator what is owed if that makes any sense.  Would work to solve a problem that exists with digital media as a whole.
Granted, nothing is stopping anyone from downloading and posting it to their own website or Facebook, so it's still kind of moot.  It's still a form of progress to make things better and a potential way to prevent future copyright issues.

**Comment by tzarebczan** [comment]
Thanks for the suggestion. I think they may be possible in the distant future, but not something we'll be focusing on anytime soon.
