### ISSUE TITLE
Use mobile horizontal scroll widget for upcoming livestreams on Wild west + Channel pages

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#728]
- [x] Add to wild west - needs show all button? Or just show all? 

- [ ] Add to channel page

**Comment by infinite-persistence** [comment]
> _ Add to wild west - needs show all button? Or just show all?_

@tzarebczan, the previous WW Livestream implementation tried to satisfy the need to only show 1 filter header + making it merge seamlessly with regular claims when "Show more livestream" is clicked. It was more of hack using 2 `ClaimListDiscover` to appear as one. 

**Is it ok if the 2 lists are not merged seamlessly?**

The 2-list design is bad (oops) ... hard to maintain and hard to extend to support the "use horizontal scroll on mobile layout".  Separating it might be easier to handle.

Also, horizontally scrolling a huge list might not be ideal anyway, so maybe "Show more livestreams" should now route to `/$/live` instead? (or just `/$/wildwest/live`)

**Comment by infinite-persistence** [comment]
> _ Add to wild west - needs show all button? Or just show all?_

@tzarebczan, is it ok if the livestream tiles are not seamlessly merged with the regular tiles, i.e. regular tiles will always start at new row? 

Getting rid of this requirement will simplify the code a bit, and makes it easier to add horizontal scroll to the mix.

**Comment by tzarebczan** [comment]
Yeah, that should be fine!

**Comment by infinite-persistence** [comment]
> _Add to channel page_

Seems like Upcoming is already swipeable in Channel Page.

<img width="323" alt="image" src="https://user-images.githubusercontent.com/64950861/156766207-017327a1-e846-4bfd-8f07-111201db4837.png">
