### ISSUE TITLE
Channel Page: CPU-usage not zero on idle

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#760]
On the homepage, the CPU usage hovers at 0 to 0.1% after things settle down (good).

In a Channel Page, it hovers at 2 - 10%.  Performance tab hints it is due to animation, but I couldn't pinpoint it ... `window.onanimationiteration = console.log;` didn't show anything.

_(my device was getting warm lately, so decided to check out CPU usage again)_

![image](https://user-images.githubusercontent.com/64950861/150779499-af060ad0-9cdd-4c6c-95c6-74b21590d5d8.png)

**Comment by AsadUmar** [comment]
Ill take this one, seems like a good place to start.

**Comment by infinite-persistence** [comment]
`Fixed`
