### ISSUE TITLE
DNS Issue from Cloudflare

### ISSUE THREAD

**Issue by robd003** [OdyseeTeam/odysee-frontend#770]
**Bug**
Odysee won't return DNS results when using VPN. All requests return SERVFAIL

**To Reproduce**
Connect to VPN, try to get A record or NS record for odysee.com

**Expected behavior**
Odysee should return DNS results. It worked yesterday...

**Screenshots**
![image](https://user-images.githubusercontent.com/571328/151246300-5e631ea8-56d7-4e96-8d34-9bcf214a1440.png)

**System Configuration**
Effects all systems, desktop and mobile.

**Comment by robd003** [comment]
DNS works for all other domains, it's only odysee.com that seems to be effected.

**Comment by tzarebczan** [comment]
It should come back up shortly, let us know if it doesn't. We just made a migration, so it's possible it hasn't propagated everywhere.

**Comment by robd003** [comment]
@tzarebczan If it's still down in an hour is there a way to report this to the ops team directly?
