### ISSUE TITLE
improve SEO on video tags and discoverability suggestion

### ISSUE THREAD

**Issue by somedu7** [OdyseeTeam/odysee-frontend#775]
I have been a content creator for many years on YT recently very successful on tiktok.
I noticed one major problem with odysee which would make it grow really fast
and that is if the video tags which you chose manually during upload would be properly indexed in search engines with friendly urls
like 
http://odysee.com/videos/asmr-whispering
http://odysee.com/videos/tag

because right now the tags just go to search but do not show a seo friendly url.
The problem with this is that a lot of users that search these keywords never end up on odysee which is a MASSIVE losing out of a potential audience. I wouldnt be surprised if that takes odysee really into mass usage

the title of the page showing should of course then be something like "asmr whispering videos"

The second thing is i really suggest pushing active content creators rather than synced youtube accounts that are not actively using odysee more. especially from the front page or even have a featured video from those active creators on the right top when you watch a video.

**Comment by tzarebczan** [comment]
I believe this would be covered under https://github.com/OdyseeTeam/odysee-frontend/issues/177 

There's also a search issue open to look at tags when searching also.
