### ISSUE TITLE
Ability to load content from LBRY P2P network

### ISSUE THREAD

**Issue by robd003** [OdyseeTeam/odysee-frontend#781]
**Is your feature request related to a problem? Please describe.**
Currently Odysee is growing like a weed which is fantastic, however loading videos can stall out and cause multiple 10 - 30 second delays while trying to play a video. If we could load content not just from Odysee's centralized servers, but the LBRY P2P network that could help alleviate the video buffering problem.

**Describe the solution you'd like**
Use WebRTC to load content from the LBRY P2P network. You could make this a user configurable opt-in feature.

**Describe alternatives you've considered**
The only alternative I can think of is to allow the community to host reflector hosts to help distribute load. However this has been shot down before :(

**Additional context**
A lot of the videos I try to watch end up stalling every 20 seconds and then take 10 seconds to buffer. It's not a great experience... Loading via LBRY has zero issues, but that only works on desktop computers and not mobile devices.

**Comment by tzarebczan** [comment]
Also, the data served will be from other Odysee peers, not the LBRY clients, at least until we can figure out how that would work. The LBRY blobs are encrypted and need to be reassembled in a special way to actually stream. and they would only support the original video format, without anything that's transcoded.
