### ISSUE TITLE
[Feature Request] Onion service for tor network

### ISSUE THREAD

**Issue by UnixPhonez** [OdyseeTeam/odysee-frontend#785]
**Is your feature request related to a problem? Please describe.**
We need an onion service for odysee, it would greatly benefit users privacy. If that's what you guys still care about... https://lemmy.ml/post/116308

**Describe the solution you'd like**
We would like a to see an v3 onion website for tor network users to be able to access and watch odysee content

**Describe alternatives you've considered**
There is no alternatives 

**Additional context**
None

**Comment by tzarebczan** [comment]
We don't plan to work on this, but others are free to try.
