### ISSUE TITLE
(Video) sitemaps for all contents and channels

### ISSUE THREAD

**Issue by Abwasserrohr** [OdyseeTeam/odysee-frontend#786]
**Is your feature request related to a problem? Please describe.**
I have seen that blog posts usually do not get not crawled by Google, but it would be great if Google would do that.
If Odysee could provide a sitemap for every content, then Google could index all the blog posts better.
Don't know if this already happens, but if it does, at least my blogs get not crawled and indexed in Google. 

**Describe the solution you'd like**
Generate a sitemap with all contents, there can be multiple sitemaps using a sitemap index.
Maybe [video sitemaps](https://developers.google.com/search/docs/advanced/sitemaps/video-sitemaps) for videos, to allow odysee videos to appear in the video tab of Google search?

**Comment by tzarebczan** [comment]
Sitemaps are already provided, but the blog content itself probably can't be because it's a piece of data that's not in the metadata. Is this may the confusion?

**Comment by Abwasserrohr** [comment]
I don't know, but it still would be cool if they get indexed by Google.
