### ISSUE TITLE
Consistent poor download speeds.

### ISSUE THREAD

**Issue by myfirstnameispaul** [OdyseeTeam/odysee-frontend#788]
**Bug**
This is not 100% of the time, but much of the time, playback caching cannot support 1.5x playback speed.

What happens is the rate of cache increase appears to be to deliver chunks of the video at a rate equal to 1x playback. When 1.5x playback hits the end of current cache, it requests delivery of next chunk, pausing for a second or two before beginning playback again, through the entire video regardless of how long it is.

**To Reproduce**

1. Play a video
2. Keep the mouse active over video to keep progress bar visible
3. Playback will reach the end of the cached section and freeze until the next few seconds of cache are delivered.

**Expected behavior**
Cache is always several chunks ahead of current location.

**System Configuration**
Web browsers Firefox, Brave, and Chromium all exhibit same behavior. I do not experience this problem on YouTube, BitChute, Rumble, or Locals.

**Additional context**
Pausing does not fix this problem because the playback eventually catches up with the caching because the caching is at 1x playback rate.

**Comment by tzarebczan** [comment]
Hey Paul, thanks for the feedback and detailed issue. I seem to be able to play it fine here, maybe it's an issue with playback bandwidth. Do you know what your up/down link is, and where you are located approximately? Can you link a video where this happens, or does it happen on all? There's some more popular videos that will have an Auto option in the bottom right - these are optimized by us - does it still happen on those?

**Comment by myfirstnameispaul** [comment]
I am in Las Vegas on Cox with a 480/10 mbps connection that reliably over WiFi is 70/10 mbps.

You have a problem on your end.  I see users on your platform complain about it. This is pretty much every video.

The only way to watch videos is to download them separately. The download URL is usually `player.odycdn.com`. Clicking the download option from the interface downloads at 300-500 KB/sec with the browser. Downloading from a hosted VPS using `wget` downloads at a rate ot 600 KB/sec - 3 MB/sec. So even here it looks like you've got issues on your end that somehow get a lot worse when going through a residential ISP. (The same VPS, BTW, can reliably download >100 MB/sec.) When I download the same videos from the hosted VPS the download rate over my WiFi is 5-6 MB/sec.

When I download from Odysee using `wget` from the hosted VPS, if I sit and watch the download, I can see it will occasionally drop to zero for several seconds, and this morning the download rate is 100-200 KB/sec with occasional spikes in the 300-500 KB/sec range.

**Comment by myfirstnameispaul** [comment]
For the past three days every video buffers constantly.

**Comment by myfirstnameispaul** [comment]
From Cox in Las Vegas, now every morning I can't get higher than 500 KB/second from Odysee for any video. This trend is perfectly consistent for me.
