### ISSUE TITLE
There is a bug in odysee on upload

### ISSUE THREAD

**Issue by ManoNeutro** [OdyseeTeam/odysee-frontend#796]
There is a bug in odysee, you can only schedule the video upload date in the past and not in the future, which doesn't make any sense. 
![1](https://user-images.githubusercontent.com/98792999/151908299-0a743fc9-dbd2-4943-ac10-6f9869a8e55e.png)

**Comment by tzarebczan** [comment]
It's not possible to schedule videos in the future yet. That feature requires a bunch of work further down our stack. Hope to have it later this year.
