### ISSUE TITLE
If you only have stripe transactions, can't see them

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#799]
This is unlikely, but if you don't have any LBC transactions, but do make a stripe one, we show the empty state: 
![image](https://user-images.githubusercontent.com/8120721/151990528-8b1118fc-6e59-4064-a6f1-5a053c5209e2.png)

**Comment by infinite-persistence** [comment]
Also end up in this screen when you clear up your Credits ...
