### ISSUE TITLE
A way to disable Google Analytics or GTM for embedded videos

### ISSUE THREAD

**Issue by ianevski** [OdyseeTeam/odysee-frontend#807]
**Is your feature request related to a problem? Please describe.**
Using GTM/GA on Odysee.com itself may be okay, but loading those on other sites that embed videos from Odysee compromises the privacy of visitors of those sites. If those sites are in Europe, there may also be [legal implications](https://www.wired.com/story/google-analytics-europe-austria-privacy-shield/).

**Describe the solution you'd like**
A query parameter or alternate domain to be used when embedding to configure Odysee for enhanced privacy and to not load GTM/GA or any other user tracking scripts.

YouTube has a "privacy-enhanced" domain of youtube-nocookie.com for similar purposes: https://support.google.com/youtube/answer/171780?hl=en#zippy=%2Cturn-on-privacy-enhanced-mode

**Describe alternatives you've considered**
There is no workaround. The scripts can be blocked by the use of ad-blocking extensions by the end-users, but the users embedding Odysee videos on their sites do not have an option to protect the privacy of their site's visitors if they choose to embed videos from Odysee.

**Additional context**
I had reported this issue to a creator with a fairly popular channel on Odysee (~120k subs), and they chose to embed videos from another host on their website.

Copying from the LBRY forums at https://forum.lbry.com/t/is-there-any-way-to-disable-google-analytics-for-odysee-embeds/560

**Comment by tzarebczan** [comment]
We don't plan to support this any time soon. Users who are generally privacy conscious about tracking will use blockers.

**Comment by ianevski** [comment]
...and screw everyone else.

Alright.
