### ISSUE TITLE
Video Player Window Resizing Bugs

### ISSUE THREAD

**Issue by david0178418** [OdyseeTeam/odysee-frontend#830]
**Bug**
When the window is resized between the thresholds for mobile and desktop view, the player restarts and picks up from the last saved point.  This is due to the player being torn down and reinstantiated in the toggle between desktop and mobile.  This can be a bit jarring, especially when the window interacts with desktop tiling behavior that temporarily makes the window smaller than you may ultimately intend it to be.

Additionally, the fullscreen toggle in "mobile" crashes the player.  This only occurs on desktop.  Not on actual mobile devices.

**To Reproduce**

1. Play video on desktop.
2. Shrink the window down to less than 900px.
3. Enlarge the window to greater than 900px

**Expected behavior**
Video plays continuously.

**Actual behavior**
Video restarts when going from large to small and stops when going small to large.

**System Configuration**

Windows 10 w/ Brave v1.35.100
Linux w/ Google Chrome 98.0.4758.80

**Additional context**

I did a git bisect to find that the behavior was introduced [with this commit](https://github.com/OdyseeTeam/odysee-frontend/commit/8c3e37687309e7316cff6fe7b0feb2e3c25c2db4) which refactored some of the mobile player logic.  When on a branch based on this commit, I was able to smooth out the switching by using and saving just the initial value returned from `useIsMobile` in `fileRenderInitiator/view.jsx` and `app/view.jsx`.  However, when applying this to master, this no longer worked.  With the additional changes since then, it may call for a more complete fix from someone with the full context.

Perhaps `useIsMobile` could check for touch events or use the `navigator.platform`? Though that may not be a simple switch if "mobile" is also used interchangeably with "small window layout" in some parts of the app.  This likely requires some discussion with your team.

As for the crash upon clicking "full screen" in the mobile view, this is due to no element with class `vjs-control-bar` being present.  However, this does not appear to be an issue on actual mobile, so depending on the route determined fro the above issue, this one may be fixed for free

![image](https://user-images.githubusercontent.com/128739/153124708-b6a6dc08-b7fa-4ab4-8527-b3cd48245dce.png)

**Comment by tzarebczan** [comment]
This is covered in https://github.com/OdyseeTeam/odysee-frontend/issues/813 as it was broken when we did that work. Will leave this one open as it's a good separate issue.

**Comment by tzarebczan** [comment]
(this will still happen on livestreams until we ship https://github.com/OdyseeTeam/odysee-frontend/pull/876)
