### ISSUE TITLE
RSS feeds should always include channel’s icon

### ISSUE THREAD

**Issue by IronMaltese** [OdyseeTeam/odysee-frontend#838]
**Is your feature request related to a problem? Please describe.**
My RSS feed looks disorganized because all the odysee icons don’t reflect the channels I’m subscribed to

**Describe the solution you'd like**
when a RSS feed is subscribed to, the icon should automatically be the channel’s icon

**Describe alternatives you've considered**

**Additional context**
Some channels do have icons, but most don’t, I’m not sure if this is an opt-in feature, but I don’t think it should be opt-in

**Comment by infinite-persistence** [comment]
I believe there is no field for us to define a favicon in the rss spec.  RSS readers will grab the favicon from the "site link" field.

If your creator has a website defined in the About page (`claim.value.website_url`) and the page has a favicon, then it will work. Otherwise, it uses the default Odysee favicon.

**Comment by tzarebczan** [comment]
Can you show us a screenshot of what you are seeing also?

**Comment by infinite-persistence** [comment]
<img width="589" alt="image" src="https://user-images.githubusercontent.com/64950861/153625345-c0e8b60b-56f3-4d45-9f50-40eb2ae94ec3.png">

**Comment by IronMaltese** [comment]
![0BBB5505-F67D-45F0-BDD1-35F0279AA873](https://user-images.githubusercontent.com/89056889/153624923-87bf086b-3c87-439b-aac9-07f23638ef32.png)

this is NetNewsWire on iOS, but he strange thing is that YouTube channels I’m subscribed to show the channels icon in their favicon

![6185E1BF-7BF7-4EA4-94E8-F5C8BF3169EB](https://user-images.githubusercontent.com/89056889/153625381-164ef870-8f43-4869-b5c9-3880f17213ce.png)

**Comment by tzarebczan** [comment]
Think it would work if we forced the odysee link into the website URL if they don't have one, or maybe the url link there. Can experiment soon and have you try again.

**Comment by IronMaltese** [comment]
I can confirm this issue has been fixed, thank you for the great work, keep it up!
