### ISSUE TITLE
Add setting to hide the use of LBC

### ISSUE THREAD

**Issue by belikor** [OdyseeTeam/odysee-frontend#847]
**Is your feature request related to a problem? Please describe.**
Some people don't want to deal with LBC at all. They think it's a distraction, and may be off-putting to absolute beginners to the platform. For example, https://odysee.com/@FraserValleyRoseFarm:e/OdyseeAdvice:6

**Describe the solution you'd like**
One suggestion is to hide everything about LBC manipulation. To publish a video obviously the user needs to have at least a small amount of LBC in the wallet. So to start publishing, he or she needs to make a one-time payment of $5 to fund the wallet. At the current price of 0.03 USD/LBC, this would be around 166 LBC, which is enough to publish hundreds of videos.

This amount of LBC will remain hidden, and won't be shown to the user. At the same time, the user won't be able to tip or support with LBC, only cash.

In this situation, Odysee will completely manage the wallet of the user. If the user publishes something (or creates a repost or playlist) Odysee will use a default and small bid value (0.01 LBC) to make sure the initial funding amount is sufficient to publish thousands of videos without running out of LBC.

A checkbox in the settings will activate the advanced mode, giving the user full control of the wallet, as it is today.

**Additional context**
Some things need to be thought out with this system, because if the user decides to use the basic mode with no LBC interaction, how would the user handle things like tips made to his or her wallet? Are those funds simply locked there? It could be a significant amount. Does this option imply that they no longer are eligible to receive tips and view rewards in LBC?

How would they handle synchronized videos from Youtube? Creators could fund their wallets depending on the number of videos that they have, say $5 for up to 100 videos, $10 for up to 1000 videos, $15 for up to 2500 videos, etc.

Also, since the videos would be published with a fixed and small bid (0.01 LBC), the videos would not be able to trend in the algorithm, as they would be displaced by videos that have a manual bid amount larger than the minimum.

**Comment by tzarebczan** [comment]
We don't plan to do something like this anytime soon.
