### ISSUE TITLE
Stray "tap to mute" button when switching to mobile layout

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#848]
1. Enable floating player.
2. Play and mute the video
3. Click on the header logo to return to homepage and invoke FP
4. Dock the window to the side (or resize until it becomes mobile layout)

<img width="373" alt="image" src="https://user-images.githubusercontent.com/64950861/153690334-93d0042c-cf24-4caa-9b6e-c1d5c5d145a6.png">

**Comment by toshokanneko** [comment]
Fixed. The button is now hidden in the mobile layout.

**Comment by infinite-persistence** [comment]
778940193e9830cc0fca0d29ec48c8e78b22ae5c
