### ISSUE TITLE
Bright Red Comment Button is really distracting

### ISSUE THREAD

**Issue by IronMaltese** [OdyseeTeam/odysee-frontend#851]
**Is your feature request related to a problem? Please describe.**

It’s really distracting when watching a video on mobile and outside of full screen mode and seeing a bright red comment bar all the way on the bottom of the screen

**Describe the solution you'd like**

change the red background in the comment button to the normal gray background, and make the text red (I don’t really care what it looks like, as long as it’s not distracting)

**Describe alternatives you've considered**
N/A

**Additional context**

Also, the new website redesign is phenomenal, keep up the amazing work!

**Comment by toshokanneko** [comment]
Thanks for the feedback. I agree with you and I've changed it.
