### ISSUE TITLE
Mobile-friendly test failures

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#860]
Mostly failing on DMCA'd pages

https://odysee.com/@Zonace:4/_Oye_Arnold___Temp_1__15____Olga_Regresa_a_Casa___El_Cometa_Sally__880097:3

<img width="948" alt="image" src="https://user-images.githubusercontent.com/64950861/153879804-7dbb6deb-47f1-4f7c-9623-4401554886fe.png">

**Comment by infinite-persistence** [comment]
The tests are still failing.
https://odysee.com/$/embed/stone15/ec4a60655acf5d48977e1c8adb6881ed468e54b4

<img width="330" alt="image" src="https://user-images.githubusercontent.com/64950861/156472127-aa5937c3-6bc7-4cfe-88f2-d798da93bdbe.png">

**Comment by infinite-persistence** [comment]
Getting more reports of this failure.

Also, getting "too close together" failures as well, but it didn't say which component.
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/64950861/167788648-8814bac8-9658-455b-95ce-bb984e5bfeaa.png">

**Comment by toshokanneko** [comment]
Can this be closed? I can only run this test manually on a specific url at a time and I haven't found any remaining issues. Unless there's a way to do a site-wide batch test or anything like that it is almost impossible for me to find any issues.
