### ISSUE TITLE
Odysee Exclusive Conent - Badge

### ISSUE THREAD

**Issue by Xseam** [OdyseeTeam/odysee-frontend#887]
It would be cool if there was a badge for Odysee Exclusive Content. Currently, it's very hard for new users to find really active channels that put more effort into growing on the platform. Many channels just use the Youtube sync to post content, but don't really comment.

This doesn't really encourage activity on the platform and isn't conducive to a community feel.
You would then also have the opportunity to better promote "Odysee Exclusive" creators.

**Comment by tzarebczan** [comment]
We don't plan to do this as there would be no way to confirm what's exclusive or not. But membership, creator, and verified badges will be coming in the future.
