### ISSUE TITLE
Make it easier to switch thumbnail CDNs

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#889]
The current code is hardcoded to a specific server (speech, vanwa), so it's not just a matter of switching URLs.  It needs to handle different output formats, plus speech requires extra input too.

- [ ] Figure out a way to make the switch easier (common interface?)
- [ ] Next, choose either auto fallback when one fails, or manually flip the switch

**Comment by tzarebczan** [comment]
I think a big part of the problem is a brave / adblock list that we turned up on. Maybe if we get the failed to fetch, we can mention to try disabling that. It's called "AdGuard Français" , and on Brave, it's on: brave://adblock/

**Comment by tzarebczan** [comment]
Since we have our own now, don't think this is important.
