### ISSUE TITLE
"Upcoming Livestreams" loads twice

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#903]
https://user-images.githubusercontent.com/64950861/154489995-a3a3c7df-0350-4d0d-8a3c-377a3edc772f.mp4

**Comment by tzarebczan** [comment]
Wasn't seeing this, at least on mobile. Maybe something with blocking?

**Comment by infinite-persistence** [comment]
Ah, yes, due to moderation + lots of channels, and also because "Upcoming Livestreams" is using `ClaimListDiscover`, which currently does not "use past results while searching" like `ClaimTileDiscover` does.

Consolidation would take some planning and lots of testing, so I guess we replicate the functionality for now.

Closing this;  will fix in #946 (same root-cause).
