### ISSUE TITLE
language refresh / selection issues

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#921]
- [x] Settings > set a language > refresh = language goes back to previous, but stuff is in the language you selected. 
     - <sub>_Closed by #972_</sub>
- [ ] settings > set a language > save. In a new tab, load an Odysee page - language is not set to what you just configured
    - Maybe we need to store language in wallet/local data?

**Comment by tzarebczan** [comment]
Also, not all areas are translated until you take an action: 
![image](https://user-images.githubusercontent.com/8120721/155810586-554e94f1-566c-4482-9eff-58d4f88e0799.png)

**Comment by gadabra** [comment]
Hi, I am a junior developer with 1.5 years of experience and a huge fan of this project. I decide to contribute. If I could join the team, it is a blessing for me.

I examined the codebase a little bit, starting with this issue. I am thinking about how language is implemented etc. I found out that `USER_STATE_POPULATE` action causes the problem, but I could not figure out the solution yet.

I have not analyzed @infinite-persistence 's solution yet, but I think the bug still exists. It behaves weirdly when changing language a second time. The previous language occurs in the select element.

**Comment by gadabra** [comment]
Changing language a second time causes this. Maybe it should be another task.  
https://www.loom.com/share/7f0a24ea397e4f99a3c1703babe4d0b3

**Comment by tzarebczan** [comment]
Hey @gadabra sorry for not replying earlier! Would Appreciate any help with this issue

**Comment by infinite-persistence** [comment]
The tab-sync PR alleviated the remaining issue, but I do see a design problem in that the following all try to set each other in various places:
- browser locale
- local storage
- redux

The slower API sync also causes conflicts between tabs.

- [ ] Resolve the settings in a proper (uni-directional) way.  Going through redux rules should do the trick, I think.

**Comment by infinite-persistence** [comment]
More notes:
- [ ] When localStorage is not available, the effective language doesn't match the drop-down selection (no-op)
- [ ] We might need to always check localStorage's availability
    - <img width="362" alt="image" src="https://user-images.githubusercontent.com/64950861/187882454-7ed3d3db-abda-4c4a-8cd6-3bfc38307b7d.png">
    - `localStorageAvailable` is a one-time eval of `Boolean(window.localStorage)`.  
    - The screenshot suggests that `window.localStorage` could later change to null, perhaps through browser settings or from the GDPR thing

**Comment by infinite-persistence** [comment]
It seems like the error message is a lie. If the below is true, `try-catch` is the only proper way to access local storage -- can't just check if it's defined, since it could later be full.

<img width="693" alt="image" src="https://user-images.githubusercontent.com/64950861/187886665-cdd9c0ce-430b-4c4c-9ccc-52b7813d0aa0.png">
