### ISSUE TITLE
The play symbol on the currently selected video in playlist is stretched

### ISSUE THREAD

**Issue by Abwasserrohr** [OdyseeTeam/odysee-frontend#932]
**Bug**
The currently played video is selected and has a play symbol on it's thumbnail, but it is stretched right now:
https://odysee.com/@GermanLetsPlay:6/das-ist-die-tollste-achterbahn-der-welt!:5?lid=b0c2bdf1a28b638f0883b3c846648e16efad65f0
![image](https://user-images.githubusercontent.com/44294954/155041223-cca5cce1-f9f6-40a1-b35c-285e9a747fe1.png)

**Comment by tzarebczan** [comment]
Looks fine on Chrome/Brave, but confirmed on Firefox

**Comment by Abwasserrohr** [comment]
For me, it's also stretched on Chrome. 😅
