### ISSUE TITLE
Use channel title instead of channel name in video cards

### ISSUE THREAD

**Issue by Abwasserrohr** [OdyseeTeam/odysee-frontend#945]
**Is your feature request related to a problem? Please describe.**
Sorry if this is a duplicate.
Since the last change, there are no `@` characters in front of channel names for video cards anymore. This is a cool change, but that said, I think now it would make sense to use the channel title instead of the name. The channel title is already sent in the claim search, most channel titles look better than just the channel name.

**Describe the solution you'd like**
Use the channel title instead of the channel name on video cards, since the `@` is now stripped, there is no reason to use the name anymore, I think. 😅

![image](https://user-images.githubusercontent.com/44294954/155331861-266c1d68-ee88-498e-bff9-62c7989c1085.png)

**Comment by tzarebczan** [comment]
I asked Julian about this and I think we want to keep the name. The name doesn't change also, which is a big positive. Twitter does names also, but both in other areas.
