### ISSUE TITLE
Improve FB card display

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#954]
Compare our cards to: https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fwww.bitchute.com%2Fvideo%2FmiKHYyfncjq3%2F

They have a bigger preview image. 

Maybe it's the size of the cards? I tried pushing up a a few things, didn't help (and don't think they hurt): 3d23c7f78b1dce361b433fe42f7308093afba7d7

**Comment by infinite-persistence** [comment]
Size of card depends on image's intrinsic size.
https://odysee-workspace.slack.com/archives/C02P8NNBFH7/p1645667714491869

**Comment by infinite-persistence** [comment]
Nick bumped up size

<img width="430" alt="image" src="https://user-images.githubusercontent.com/64950861/155444392-b1cfd9ba-b808-4b38-b8aa-17a5c4496d20.png">
