### ISSUE TITLE
Use titles vs names on channel claim previews, but show name in channel areas

### ISSUE THREAD

**Issue by tzarebczan** [OdyseeTeam/odysee-frontend#956]
I took a stab at this, start here if it made sense: e1a04f288d98876838ec242c30cbf5c3843985fe

On the places where we show both the title and name, (i.e. channel pages / search results, etc), went back to showing the full channel name with @, and the title above (like we used to - but stripping out @ for channels that don't have a title). I think this makes more sense vs hiding the channel name, because we have places like https://odysee.com/$/search?q=bret where showing the name would be desired. 

The trickier part was the side bar - not sure what the best way to get titles in there would be. Makes sense for it to match right? And then the search bar on sidebar would need to use this also. We can probably ship as is for now if this is harder.

And maybe this should be a setting eventually, similar how slack does full name vs nickname?

**Comment by infinite-persistence** [comment]
## Re: Sidebar filter
> _And then the search bar on sidebar would need to use this also_

We would need to resolve subscriptions to include _title_ in the filtering :(

**Comment by infinite-persistence** [comment]
## Re: Sidebar title + name
> _The trickier part was the side bar - not sure what the best way to get titles in there would be. Makes sense for it to match right?_

Here's my attempt on top of your branch:  https://github.com/OdyseeTeam/odysee-frontend/commit/49bbb087a65b77ca284c36860d1f72fbdf5eadd3

<img width="154" alt="image" src="https://user-images.githubusercontent.com/64950861/155483927-6dfab7f8-76c6-453d-b7ab-d8fd4a291a82.png">

**Comment by infinite-persistence** [comment]
> _don't we already resolve to get the thumbnails?_

Only when they are displayed, so we don't know the _titles_ for items hidden under "show more" for the search code to look up.
The prefs data only contains _uri_ and _name_.

**Comment by tzarebczan** [comment]
Ah, gotcha... I think it's fine to use the name search for now. If you can, get this into a PR.
