### ISSUE TITLE
Mini sidebar sometimes blank

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#966]
Sometimes I get a blank mini sidebar, and requires several refresh and/or window resize to fix.
Hard to reproduce ... I think happens on specific window sizes.

<img width="659" alt="image" src="https://user-images.githubusercontent.com/64950861/155685644-63276477-f550-4ce5-b430-a853671c6df8.png">

**Comment by tzarebczan** [comment]
Seen this happen a couple times also, but not a huge deal right now.

**Comment by tzarebczan** [comment]
With local homepage, does this happen less?

**Comment by infinite-persistence** [comment]
Still happened to me this morning.  Maybe not related to homepages but the sidebar CSS
