### ISSUE TITLE
Way to test videos are playable

### ISSUE THREAD

**Issue by apaxc** [OdyseeTeam/odysee-frontend#981]
**Is your feature request related to a problem? Please describe.**
I am having problems with some videos that I have uploaded on the odysee channel some 300 or so. And I would love to be able to tell which videos are able to be run and work and those that are broken and needing to reupload
The problem videos give the error message "The media could not be loaded, either because the server or network failed or because the format is not supported."
And yes I am aware of what causes it. That being ***me*** uploading the video incorrectly.

**Describe the solution you'd like**
A way to mass test if the video is able to be played, 

**Describe alternatives you've considered**
Tried looking around the github repos and reddit if anyone had a bot to do this, such as open the webpage wait for if the video loads, if not then getting an message and a mark to the broken video.

**Additional context**
![media format](https://user-images.githubusercontent.com/64091461/155897062-25aa16d3-f5d6-4665-b270-965fc567723e.png)

Thanks 😁🙌

**Comment by tzarebczan** [comment]
Why are they not playable, due to not being finished uploaded or due to format? You'll want to stick with h264 + AAC audio and they'll work. There's no better way around this.

**Comment by apaxc** [comment]
> Why are they not playable, due to not being finished uploaded or due to format? You'll want to stick with h264 + AAC audio and they'll work. There's no better way around this.

Due to using a mass uploader and having insufficient coins, 
Some of the videos work if not most but some dont and I cant tell which ones they are that dont work until someone comments telling me that the video is not working. 


I have some odd 300 videos uploaded and going one by one through all of them and trying and waiting for each to start playing is going to be long and tedious. And would be more or less guesswork on trying which work and those that don't

I would like to have something that automatically tells me that the video is having format or playback issues due to being incorrectly uploaded.


thanks

**Comment by tzarebczan** [comment]
Not having enough credits would result in no claim, not a non playable file. 

Don't see any other way of trying besides using some script to check each of the URLs. If you send us an email at hello@odysee.com and reference this, we can create a query to get to the mp4 for each file. Maybe that would get you a step closer.

**Comment by apaxc** [comment]
> we can create a query to get to the mp4 for each file. Maybe that would get you a step closer.

That is exactly what I had in mind. Contacted support hope to see this solved.
thanks
