### ISSUE TITLE
My Suggestion Is...

### ISSUE THREAD

**Issue by RobloxTea** [OdyseeTeam/odysee-frontend#983]
**When we are uploading Video on Odysee on a mobile app can we leave The app while the video is uploading cause it takes so long time to upload so can you Give us a permission to leave the app while it is uploading and Once the uploading is done it will give us a reminder telling us that the video is done uploading. On the Mobile app when it is uploading your phone screen need to be open if the screen is not open the uploading sign will restart all over again can you fix that so that when we close our phone it's still uploading.**

**Comment by tzarebczan** [comment]
If you're referring to odysee.com, that's an issue with some browsers potentially that don't allow a background process. Try something like Brave or Firefox. Not much control over that otherwise.

**Comment by RobloxTea** [comment]
How About On a mobile app why does it do that.

**Comment by tzarebczan** [comment]
There's no mobile app for Odysee that has upload support yet...
