### ISSUE TITLE
Reposting from Top Page doesn't fill in the fields

### ISSUE THREAD

**Issue by infinite-persistence** [OdyseeTeam/odysee-frontend#991]
https://odysee.com/$/top?name=bret

<img width="628" alt="image" src="https://user-images.githubusercontent.com/64950861/155992457-de913fea-e498-4484-8fe3-2c44c21dc781.png">

<img width="694" alt="image" src="https://user-images.githubusercontent.com/64950861/155992510-7cd36873-74e9-4216-95bb-052a094f381d.png">

**Comment by tzarebczan** [comment]
It fills in the repost url and amount (to win), but the content itself to repost is up to the user.
