### ISSUE TITLE
Is This Bug?

### ISSUE THREAD

**Issue by RobloxTea** [OdyseeTeam/odysee-frontend#996]
**Why in the website it show comment But on the app it show nothing like it show on photo one and it did not show on photo two and photo two is on the app and photo one is on the website.**
![2BA4E453-8679-4998-B0DC-BB9C3C90B4C2](https://user-images.githubusercontent.com/99421646/156087120-bd172a84-b4b5-43ca-942d-36be7bb59a5e.png)
![1F73B44D-F6BB-4312-A4EF-155754CD290B](https://user-images.githubusercontent.com/99421646/156087132-f1700d20-09c7-42f4-a08e-d78e7970c55c.png)

**Comment by tzarebczan** [comment]
Yes, it's filed on the iOS app repo, thank you for pointing that out!
