### ISSUE TITLE
Recommended videos being covered by player

### ISSUE THREAD

**Issue by LiftedStarfish** [OdyseeTeam/odysee-frontend#998]
**Bug**
If the browser window is too narrow, then the player will cover a portion of the recommended videos. This only on initial page load, and if the box for the recommended videos is too wide. Adjusting the window size after the page loads fixes the issue, but it returns if the page is reloaded.

**To Reproduce**
Because this bug is dependent on the specific text in the title of the videos in the recommended box, this one is actually extremely difficult to replicate. You can try the videos in my screenshots bellow, but It may not work. Bellow are the things that you should do if you manage to find a video where the bug is present.

1. On a video where the bug is present, make the horizontal size of your browser window narrower. I'm using a 2560x1080 monitor, and I've found that a little under half of my screen's width is enough with the window vertically maximized.
2. Reload the web page.

**Expected behavior**
There is no overlap.

**Screenshots**
The bug occurring on this video: https://odysee.com/@TheLinuxGamer:f/the-steam-deck's-software-still-needs:5

![overlap](https://user-images.githubusercontent.com/19557129/156154722-23df8dc0-5fb2-4464-b29e-f6deba1572aa.png)

The Bug *not* occuring on this video: https://odysee.com/@TheLinuxGamer:f/steam-deck-verified:5

![no_overlap](https://user-images.githubusercontent.com/19557129/156154915-be3a53b2-dbef-453d-a431-8b124a1d457b.png)

Note that both of the above images are taken with slightly different screen sizes, but I *have* tested it when they're both at the same size, and the issue still occurs, and when switching between tabs, it is *very* noticeable that the recommended section is wider for the video in the first image than it is for the video in the second.

**System Configuration**
- Browser: Brave Browser
- Operating system: Manjaro Linux KDE edition
- Kernel Version: 5.16.11-2-MANJARO (64-bit)

**Additional context**
I have not tested this in the 'application' version of Odysee, the one where you pop out the window as if it were its own kind of little app.

Also, you guys need to update your bug report template. It still has LBRY stuff there, and talks about the LBRY desktop app, when this is *not* what I'm trying to report about.

**Comment by mayeaux** [comment]
Yup I've noticed the same thing, that's for filing this

**Comment by tzarebczan** [comment]
This should be fixed now, please reopen if you still see it.
